using System;using System.IO;using System.Linq;using UnityEngine;using UnityEditor;using UnityEngine.SceneManagement;using UnityEditor.SceneManagement;using UnityEditor.Build.Reporting;using Object=UnityEngine.Object;
namespace MassEngine.Game.Editor {
 public static class Advance33Builder {
  const string Root="Assets/Game/Experiments/NavigationApproach",Source="Assets/Game/Experiments/DeploymentChecks",Logs="Logs/StripeFix-20261005";
  static readonly string[] Names={"Green","Autumn","Winter"};
  static void Check(bool b,string e){if(!b)throw new Exception(e);}
  static T Find<T>(Scene s)where T:Component{foreach(var g in s.GetRootGameObjects()){var c=g.GetComponentInChildren<T>(true);if(c!=null)return c;}throw new Exception("Missing "+typeof(T));}
  public static void Prepare(){Check(!Directory.Exists(Root),"Refuse existing Advance33");Directory.CreateDirectory(Root);Directory.CreateDirectory(Logs);AssetDatabase.Refresh();   var cat=Object.Instantiate(AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Source+"/Catalog.asset"));for(int i=0;i<3;i++)cat.entries[i].scenePath=Root+"/"+Names[i]+".unity";AssetDatabase.CreateAsset(cat,Root+"/Catalog.asset");AssetDatabase.SaveAssets();
   foreach(var name in Names){string path=Root+"/"+name+".unity";Check(AssetDatabase.CopyAsset(Source+"/"+name+".unity",path),"Copy scene");var s=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);cat=AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Root+"/Catalog.asset");var d=Find<WarSandboxRuntimeDeployment>(s);d.battlefieldCatalog=cat;EditorUtility.SetDirty(d);var manager=d.controller.manager;var system=Object.Instantiate(manager.systemConfig);var flow=Object.Instantiate(system.runtimeFlowConfig);flow.terrainLaneApproach33=true;AssetDatabase.CreateAsset(flow,Root+"/"+name+"-Flow.asset");system.runtimeFlowConfig=flow;AssetDatabase.CreateAsset(system,Root+"/"+name+"-System.asset");manager.systemConfig=system;EditorUtility.SetDirty(manager);ActorMaterialBuildGuard.RequireValid(s);EditorSceneManager.SaveScene(s);}
   Check(AssetDatabase.CopyAsset(Source+"/LaunchMenu.unity",Root+"/LaunchMenu.unity"),"Copy menu");var menu=EditorSceneManager.OpenScene(Root+"/LaunchMenu.unity",OpenSceneMode.Single);var session=Find<WarSandboxSceneSession>(menu);session.catalog=AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Root+"/Catalog.asset");EditorUtility.SetDirty(session);ActorMaterialBuildGuard.RequireValid(menu);EditorSceneManager.SaveScene(menu);AssetDatabase.SaveAssets();File.WriteAllText(Logs+"/prepare.json","{\"passed\":true,\"newScenes\":4,\"sceneOnlyOptIn\":true}");
  }
  [Serializable]class Receipt{public bool passed;public string buildGuid;public int errors,warnings;}
  public static void Build(){const string dir="Builds/AdvanceLanes-20261005-33";Check(!Directory.Exists(dir),"Refuse existing build33");Directory.CreateDirectory(dir);var r=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{Root+"/LaunchMenu.unity"}.Concat(Names.Select(n=>Root+"/"+n+".unity")).ToArray(),locationPathName=dir+"/WarSandbox.exe",target=BuildTarget.StandaloneWindows64,options=BuildOptions.Development});File.WriteAllText(Logs+"/build.json",JsonUtility.ToJson(new Receipt{passed=r.summary.result==BuildResult.Succeeded,buildGuid=r.summary.guid.ToString(),errors=(int)r.summary.totalErrors,warnings=(int)r.summary.totalWarnings},true));Check(r.summary.result==BuildResult.Succeeded,"Build33 failed");File.WriteAllText(dir+"/Start-Game.cmd","@echo off\r\ncd /d \"%~dp0\"\r\nstart \"\" \"WarSandbox.exe\" -screen-fullscreen 1 -window-mode exclusive -screen-width 1920 -screen-height 1080\r\n");}
 }
}
