using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.SceneManagement;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEditor.Build.Reporting;
using Object=UnityEngine.Object;
namespace MassEngine.Game.Editor {
 public static class Art21Builder {
  public const string Root="Assets/Game/Content/Battlefields/WoodlandDetail",Source="Assets/Game/Content/Battlefields/WoodlandArt",Battle=Root+"/ForestHills.unity",Menu=Root+"/LaunchMenu.unity",Logs="Logs/Art21-20261005";
  static Dictionary<string,Material> mats=new Dictionary<string,Material>();static Dictionary<string,Texture2D> textures=new Dictionary<string,Texture2D>();
  static List<Used> used=new List<Used>();static TerrainSurface surface;static System.Random rng=new System.Random(2005);
  [Serializable]class Used{public string prefab;public int instances;public long trianglesPerInstance;}
  [Serializable]class TextureInfo{public string path;public int width,height;public string format;}
  [Serializable]class Receipt{public bool passed;public int props,renderers,materials,textures,playableWidth=512;public long triangles;public Used[] sources;public TextureInfo[] textureInfo;public bool originalAssetsUntouched=true,collidersAdded=false;}
  static void Require(bool b,string e){if(!b)throw new Exception(e);}
  static T Find<T>(Scene s)where T:Component{foreach(var g in s.GetRootGameObjects()){var t=g.GetComponentInChildren<T>(true);if(t!=null)return t;}throw new Exception("Missing "+typeof(T).Name);}
  static T Clone<T>(T a,string name)where T:Object{var v=Object.Instantiate(a);v.name=name;AssetDatabase.CreateAsset(v,Root+"/"+name+".asset");return v;}
  static float Rand(float a,float b)=>a+(b-a)*(float)rng.NextDouble();
  static Texture2D TextureCopy(Texture t){if(t==null)return null;string path=AssetDatabase.GetAssetPath(t);if(string.IsNullOrEmpty(path)||!path.StartsWith("Assets/"))return null;if(textures.TryGetValue(path,out var known))return known;Require(!string.IsNullOrEmpty(path),"Texture without source");string dest=Root+"/Textures/T"+textures.Count+Path.GetExtension(path);Require(AssetDatabase.CopyAsset(path,dest),"Copy texture "+path);var importer=AssetImporter.GetAtPath(dest) as TextureImporter;Require(importer!=null,"Missing texture importer");importer.maxTextureSize=512;importer.mipmapEnabled=true;importer.isReadable=false;importer.textureCompression=TextureImporterCompression.Compressed;importer.crunchedCompression=false;importer.anisoLevel=2;var platform=importer.GetPlatformTextureSettings("Standalone");platform.overridden=true;platform.maxTextureSize=512;platform.format=TextureImporterFormat.Automatic;platform.textureCompression=TextureImporterCompression.Compressed;importer.SetPlatformTextureSettings(platform);importer.SaveAndReimport();var tex=AssetDatabase.LoadAssetAtPath<Texture2D>(dest);Require(tex.width<=512&&tex.height<=512,"Texture over budget");textures[path]=tex;return tex;}
  static Material MaterialCopy(Material original,bool far){string key=original.GetInstanceID()+":"+far;Require(original!=null,"Missing source material");if(mats.TryGetValue(key,out var result))return result;result=new Material(Shader.Find(far?"MassEngine/Art21 Distant Foliage":"Universal Render Pipeline/Lit"));result.name="21 "+original.name;result.enableInstancing=true;Texture t=original.HasProperty("_BaseMap")?original.GetTexture("_BaseMap"):null;if(t==null&&original.HasProperty("_MainTex"))t=original.GetTexture("_MainTex");if(t==null)t=original.mainTexture;result.SetTexture("_BaseMap",TextureCopy(t));Color c=original.HasProperty("_BaseColor")?original.GetColor("_BaseColor"):original.HasProperty("_Color")?original.GetColor("_Color"):Color.white;result.SetColor("_BaseColor",c);if(result.HasProperty("_Smoothness"))result.SetFloat("_Smoothness",.06f);if(result.HasProperty("_Metallic"))result.SetFloat("_Metallic",0);bool leaves=(original.name.ToLower().Contains("leave")||original.shader.name.Contains("Foliage")||original.name.ToLower().Contains("foliage"));bool clip=leaves||(original.HasProperty("_AlphaClip")&&original.GetFloat("_AlphaClip")>.5f)||original.IsKeywordEnabled("_ALPHATEST_ON");if(clip){result.SetFloat("_AlphaClip",1);result.SetFloat("_Cutoff",.45f);if(!far)result.EnableKeyword("_ALPHATEST_ON");result.SetOverrideTag("RenderType","TransparentCutout");result.renderQueue=2450;result.SetFloat("_Cull",0);}AssetDatabase.CreateAsset(result,Root+"/Materials/M"+mats.Count+".mat");mats[key]=result;return result;}
  static GameObject Place(string path,float x,float z,float height,float yaw,Transform parent,bool far=false){
   var prefab=AssetDatabase.LoadAssetAtPath<GameObject>(path);Require(prefab!=null,"Missing "+path);var go=(GameObject)PrefabUtility.InstantiatePrefab(prefab,parent);PrefabUtility.UnpackPrefabInstance(go,PrefabUnpackMode.Completely,InteractionMode.AutomatedAction);go.name="21 "+prefab.name;go.transform.rotation=Quaternion.Euler(0,yaw,0);
   // Keep an actual authored lower LOD, never simultaneously draw all LOD levels.
   foreach(var group in go.GetComponentsInChildren<LODGroup>(true)){var lods=group.GetLODs();int level=Math.Min(far?2:1,lods.Length-1);if(level>=0){var keep=new HashSet<Renderer>(lods[level].renderers.Where(r=>r!=null));foreach(var rr in lods.SelectMany(l=>l.renderers).Where(r=>r!=null).Distinct().ToArray())if(!keep.Contains(rr))Object.DestroyImmediate(rr.gameObject);}if(group!=null)Object.DestroyImmediate(group);}
   foreach(var col in go.GetComponentsInChildren<Collider>(true))Object.DestroyImmediate(col);foreach(var rb in go.GetComponentsInChildren<Rigidbody>(true))Object.DestroyImmediate(rb);foreach(var script in go.GetComponentsInChildren<MonoBehaviour>(true))if(script!=null)Object.DestroyImmediate(script);
   var renderers=go.GetComponentsInChildren<MeshRenderer>(true);Require(renderers.Length>0,"No renderers "+path);foreach(var r in renderers){r.enabled=true;r.gameObject.SetActive(true);}
   long triangles=go.GetComponentsInChildren<MeshFilter>(true).Sum(f=>Scene18AssetAudit.Triangles(f.sharedMesh));Require(triangles<=(path.Contains("Mountain")?2000:1000),"Per prop mesh budget exceeded: "+path+" "+triangles);
   Bounds bounds=renderers[0].bounds;foreach(var r in renderers)bounds.Encapsulate(r.bounds);go.transform.localScale*=height/Mathf.Max(.01f,bounds.size.y);bounds=renderers[0].bounds;foreach(var r in renderers)bounds.Encapsulate(r.bounds);float y=TerrainScaleBounds.BackdropHeight(surface,x,z);go.transform.position+=new Vector3(x,y,z)-new Vector3(bounds.center.x,bounds.min.y,bounds.center.z);
   bounds=renderers[0].bounds;foreach(var r in renderers){bounds.Encapsulate(r.bounds);r.sharedMaterials=r.sharedMaterials.Select(m=>MaterialCopy(m,far)).ToArray();r.shadowCastingMode=height>8&&!far&&used.Sum(u=>u.instances)%3==0?ShadowCastingMode.On:ShadowCastingMode.Off;r.receiveShadows=true;r.lightProbeUsage=LightProbeUsage.Off;r.reflectionProbeUsage=ReflectionProbeUsage.Off;GameObjectUtility.SetStaticEditorFlags(r.gameObject,StaticEditorFlags.BatchingStatic);}
   Require(!(bounds.min.x<242&&bounds.max.x> -242&&bounds.min.z<220&&bounds.max.z> -220),"Decoration intersects playable area: "+path);
   if(path.Contains("Mountain"))go.transform.position-=Vector3.up*height*.20f;var cull=go.AddComponent<LODGroup>();cull.SetLODs(new[]{new LOD(height<3?.006f:.0035f,renderers)});cull.RecalculateBounds();var u=used.FirstOrDefault(v=>v.prefab==path&&v.trianglesPerInstance==triangles);if(u==null){u=new Used{prefab=path,trianglesPerInstance=triangles};used.Add(u);}u.instances++;return go;
  }
  static string SC(string tail)=>"Assets/ThirdParty/Supercyan Free Forest Sample/Prefabs/Mobile/"+tail+".prefab";
  static string PT(string tail)=>"Assets/ThirdParty/Polytope Studio/Lowpoly_Environments/Prefabs/"+tail+".prefab";
  static string PP(string tail)=>"Assets/ThirdParty/Pure Poly/Free Low Poly Nature Pack/Prefabs/"+tail+".prefab";

  static Texture2D GroundTexture(string source,string name,int max){string dest=Root+"/Textures/"+name+".png";Require(AssetDatabase.CopyAsset(source,dest),"Ground texture missing");var imp=(TextureImporter)AssetImporter.GetAtPath(dest);imp.maxTextureSize=max;imp.mipmapEnabled=true;imp.anisoLevel=4;imp.textureCompression=TextureImporterCompression.Compressed;imp.crunchedCompression=false;imp.isReadable=false;var p=imp.GetPlatformTextureSettings("Standalone");p.overridden=true;p.maxTextureSize=max;p.format=TextureImporterFormat.Automatic;p.textureCompression=TextureImporterCompression.Compressed;imp.SetPlatformTextureSettings(p);imp.SaveAndReimport();var t=AssetDatabase.LoadAssetAtPath<Texture2D>(dest);Require(t.width<=max&&t.height<=max,"Ground texture cap");return t;}
  static bool Spaced(List<Vector2> taken,Vector2 p,float distance){return taken.All(q=>(q-p).sqrMagnitude>distance*distance);}
  [Serializable]class LayoutAudit{public bool passed,navigationUnchanged,groundMeshUnchanged,noDecorationInPlayableRegion;public int trees,props,renderers,materials,groundTextures=3;public long decorationTriangles;public string surfacePath,groundMeshPath;public Used[] sources;public TextureInfo[] textures;}
  static Dictionary<Material,Material> copied=new Dictionary<Material,Material>();
  static Material CopyExisting(Material source){if(copied.TryGetValue(source,out var m))return m;m=new Material(source);if(m.shader.name=="MassEngine/Art20 Distant Foliage")m.shader=Shader.Find("MassEngine/Art21 Distant Foliage");m.name="21 "+source.name;AssetDatabase.CreateAsset(m,Root+"/Materials/Inherited"+copied.Count+".mat");copied.Add(source,m);return m;}
  static Bounds BoundsOf(GameObject go){var rs=go.GetComponentsInChildren<Renderer>();var b=rs[0].bounds;foreach(var r in rs)b.Encapsulate(r.bounds);return b;}
  static bool Clear(Bounds b)=>!(b.min.x<242&&b.max.x> -242&&b.min.z<220&&b.max.z> -220);
  static Texture2D Bake(string name,Color[] colors,bool mip){var t=new Texture2D(512,512,TextureFormat.RGBA32,false,true);t.SetPixels(colors);t.Apply();string p=Root+"/Textures/"+name+".png";File.WriteAllBytes(p,t.EncodeToPNG());Object.DestroyImmediate(t);AssetDatabase.ImportAsset(p);var i=(TextureImporter)AssetImporter.GetAtPath(p);i.sRGBTexture=false;i.maxTextureSize=512;i.mipmapEnabled=mip;i.wrapMode=TextureWrapMode.Clamp;i.textureCompression=TextureImporterCompression.Compressed;i.SaveAndReimport();return AssetDatabase.LoadAssetAtPath<Texture2D>(p);}
  static void Stamp(Color[] a,Vector3 center,float rx,float rz,bool rock,bool contact=false){int xmin=Mathf.Max(0,Mathf.FloorToInt((center.x-rx+640)/1280*512)),xmax=Mathf.Min(511,Mathf.CeilToInt((center.x+rx+640)/1280*512));int zmin=Mathf.Max(0,Mathf.FloorToInt((center.z-rz+640)/1280*512)),zmax=Mathf.Min(511,Mathf.CeilToInt((center.z+rz+640)/1280*512));for(int z=zmin;z<=zmax;z++)for(int x=xmin;x<=xmax;x++){float wx=(x+.5f)*2.5f-640,wz=(z+.5f)*2.5f-640;float q=Mathf.Sqrt(Mathf.Pow((wx-center.x)/rx,2)+Mathf.Pow((wz-center.z)/rz,2));float k=(1-Mathf.SmoothStep(.25f,1,q))*(.55f+.45f*Mathf.PerlinNoise(wx*.11f+8,wz*.11f+37));int j=z*512+x;if(contact)a[j].b=Mathf.Max(a[j].b,k);else if(rock)a[j].g=Mathf.Max(a[j].g,k);else a[j].r=Mathf.Max(a[j].r,k);}}
  [Serializable]class Audit21 {public bool passed,navigationUnchanged,groundMeshUnchanged,backdropGeometryUnchanged,noDecorationInPlayableRegion;public int props,renderers,treesWidened,broadleafReplacements,addedProps,seamVertices,textureMax=1024;public long decorationTriangles;public float maxSeamPositionError,maxSeamNormalError;public string groundMeshPath;}
  public static void Prepare(){
   Require(!Directory.Exists(Root),"Refuse overwrite21");Directory.CreateDirectory(Root+"/Materials");Directory.CreateDirectory(Root+"/Textures");Directory.CreateDirectory(Logs);AssetDatabase.Refresh();ShaderUtil.allowAsyncCompilation=false;
   Require(AssetDatabase.CopyAsset(Source+"/ForestHills.unity",Battle),"Copy scene");var scene=EditorSceneManager.OpenScene(Battle,OpenSceneMode.Single);var manager=Find<MassEngineManager>(scene);Require(manager.TryGetTerrainContext(out surface,out var nav,out var error),error);var originalSurface=manager.terrainSurfaceAsset;Require(surface.Size==new Vector2(512,512),"Wrong size");
   var d=Find<WarSandboxRuntimeDeployment>(scene);var catalog=Clone(d.battlefieldCatalog,"Catalog");d.battlefieldCatalog=catalog;foreach(var e in catalog.entries){e.id="forest-art21";e.scenePath=Battle;e.displayName="林间旷野 · 丰茂林缘";e.description="宽树冠 / 林下草丛 / 自然地表过渡\n开阔战场保留，默认2048人。";e.briefing="林缘按近中远分层，岩石周围铺开低矮草丛和灌木；地表加入林下土色与细纹理。\n512地图、布阵空间及导航不变，不新增碰撞障碍。\n普通景观贴图512，主草地1024；高人数仍仅作压力试验。";}catalog.defaultEntryId="forest-art21";
   var root=GameObject.Find("20 Artful Woodland - visual only outside navigation");Require(root!=null,"Missing source scenery");root.name="21 Artful Woodland - visual only outside navigation";foreach(var r in root.GetComponentsInChildren<Renderer>())r.sharedMaterials=r.sharedMaterials.Select(CopyExisting).ToArray();
   var ground=GameObject.Find("Plan B - Shared Render And Navigation Surface");var back=GameObject.Find("Visual Only Backdrop - No navigation or colliders");var gm=ground.GetComponent<MeshFilter>().sharedMesh;var bm=back.GetComponent<MeshFilter>().sharedMesh;var report=new Audit21{groundMeshPath=AssetDatabase.GetAssetPath(gm)};
   // Inspect the exact shared boundary before touching appearance. Geometry stays untouched.
   var gv=gm.vertices;var gn=gm.normals;var bv=bm.vertices;var bn=bm.normals;for(int j=0;j<bv.Length;j++){var v=bv[j];if(Mathf.Abs(v.x)>256||Mathf.Abs(v.z)>256||(Mathf.Abs(v.x)!=256&&Mathf.Abs(v.z)!=256))continue;int k=Mathf.RoundToInt((v.z+256)/2)*257+Mathf.RoundToInt((v.x+256)/2);report.maxSeamPositionError=Mathf.Max(report.maxSeamPositionError,Vector3.Distance(back.transform.TransformPoint(v),ground.transform.TransformPoint(gv[k])));report.maxSeamNormalError=Mathf.Max(report.maxSeamNormalError,Vector3.Distance(bn[j],gn[k]));report.seamVertices++;}Require(report.seamVertices==1024&&report.maxSeamPositionError<.001f,"Geometry gap requires separate review");
   var material=new Material(ground.GetComponent<Renderer>().sharedMaterial);material.shader=Shader.Find("MassEngine/Art21 Ground");AssetDatabase.CreateAsset(material,Root+"/Ground.mat");ground.GetComponent<Renderer>().sharedMaterial=material;back.GetComponent<Renderer>().sharedMaterial=material;
   // A single world-space normal field removes dependence on the 2m vs 32m visual mesh tessellation.
   var normals=new Color[512*512];for(int z=0;z<512;z++)for(int x=0;x<512;x++){float wx=(x+.5f)*3-768,wz=(z+.5f)*3-768;float dx=TerrainScaleBounds.BackdropHeight(surface,wx+1,wz)-TerrainScaleBounds.BackdropHeight(surface,wx-1,wz),dz=TerrainScaleBounds.BackdropHeight(surface,wx,wz+1)-TerrainScaleBounds.BackdropHeight(surface,wx,wz-1);var n=new Vector3(-dx,2,-dz).normalized;normals[z*512+x]=new Color(n.x*.5f+.5f,n.y*.5f+.5f,n.z*.5f+.5f,1);}material.SetTexture("_SurfaceNormals",Bake("WorldSurfaceNormals",normals,true));
   var wood=GameObject.Find("Asymmetric forest belts").transform;var trees=wood.Cast<Transform>().Select(t=>t.gameObject).ToArray();var leaf=trees.First(t=>t.name.Contains("leaf"));int index=0;foreach(var tree in trees){var old=BoundsOf(tree);var scale=tree.transform.localScale;if(tree.name.Contains("Pine")||tree.name.Contains("fir")){tree.transform.localScale=Vector3.Scale(scale,new Vector3(tree.name.Contains("Pine")?1.95f:1.35f,.92f,tree.name.Contains("Pine")?1.95f:1.35f));var now=BoundsOf(tree);tree.transform.position+=new Vector3(old.center.x-now.center.x,old.min.y-now.min.y,old.center.z-now.center.z);if(!Clear(BoundsOf(tree))){tree.transform.localScale=scale;now=BoundsOf(tree);tree.transform.position+=new Vector3(old.center.x-now.center.x,old.min.y-now.min.y,old.center.z-now.center.z);}else report.treesWidened++;}
    if(tree.name.Contains("Pine")&&index++%5==0&&old.center.z> -220&&Mathf.Max(Mathf.Abs(old.center.x),Mathf.Abs(old.center.z))>295){var go=Object.Instantiate(leaf,wood);go.name="21 broadleaf canopy";go.transform.rotation=Quaternion.Euler(0,Rand(0,360),0);var b=BoundsOf(go);go.transform.localScale*=Rand(19,28)/b.size.y;b=BoundsOf(go);go.transform.position+=new Vector3(old.center.x,old.min.y,old.center.z)-new Vector3(b.center.x,b.min.y,b.center.z);if(Clear(BoundsOf(go))){foreach(var r in go.GetComponentsInChildren<Renderer>()){r.sharedMaterials=r.sharedMaterials.Select(m=>MaterialCopy(m,true)).ToArray();r.shadowCastingMode=ShadowCastingMode.Off;}Object.DestroyImmediate(tree);report.broadleafReplacements++;}else Object.DestroyImmediate(go);}}
   var detail=new GameObject("21 Grouped understory and trail verges").transform;detail.SetParent(root.transform);var anchors=new List<Vector2>();foreach(var tree in wood.Cast<Transform>().Where((t,i)=>i%3==0)){var b=BoundsOf(tree.gameObject);if(Mathf.Max(Mathf.Abs(b.center.x),Mathf.Abs(b.center.z))<335)anchors.Add(new Vector2(b.center.x,b.center.z));}anchors.AddRange(new[]{new Vector2(-285,-155),new Vector2(-292,31),new Vector2(-295,162),new Vector2(131,273),new Vector2(248,276),new Vector2(278,90),new Vector2(-272,52)});
   int count=0;foreach(var anchor in anchors){for(int j=0;j<12;j++){float a=Rand(0,6.283f),radius=Rand(4,15);var p=anchor+new Vector2(Mathf.Cos(a)*radius,Mathf.Sin(a)*radius*.65f);if(Mathf.Abs(p.x)<253&&Mathf.Abs(p.y)<234)continue;if(Mathf.Abs(p.y-16*Mathf.Sin(p.x/54))<17||Mathf.Abs(p.y-(90+8*Mathf.Sin(p.x/40)))<7)continue;string path=j%8==0?PT("Shrubs/PT_Generic_Shrub_01_green"):j%7==0?SC("Foliage/Mushroom/Mobile_forestpack_foliage_mushroom_red_small"):j%5==0?PT("Flowers/PT_Poppy_02"):SC(j%2==0?"Foliage/Grass/Mobile_forestpack_foliage_grassPatch_small_1":"Foliage/Grass/Mobile_forestpack_foliage_grassPatch_small_2");float height=j%8==0?Rand(1.6f,2.8f):j%7==0?Rand(.45f,.9f):j%5==0?Rand(.7f,1.3f):Rand(.75f,1.45f);Place(path,p.x,p.y,height,Rand(0,360),detail);count++;}}report.addedProps=count;
   var mask=new Color[512*512];foreach(Transform t in wood){var b=BoundsOf(t.gameObject);Stamp(mask,b.center,Mathf.Max(9,b.size.x*.8f),Mathf.Max(9,b.size.z*.8f),false);}var ridge=GameObject.Find("Rock shelves and far ridgeline");foreach(Transform t in ridge.transform){if(t.name.Contains("Mountain"))continue;var b=BoundsOf(t.gameObject);Stamp(mask,b.center,b.size.x*.75f+5,b.size.z*.75f+5,true);}material.SetTexture("_DetailMask",Bake("ForestFloorMask",mask,true));EditorUtility.SetDirty(material);
   var all=root.GetComponentsInChildren<Renderer>();foreach(var r in all)Require(Clear(r.bounds),"Decoration intrudes: "+r.name);Require(root.GetComponentsInChildren<Collider>(true).Length==0,"Unexpected collider");report.renderers=all.Length;report.props=root.transform.Cast<Transform>().Sum(t=>t.childCount);report.decorationTriangles=root.GetComponentsInChildren<MeshFilter>().Sum(f=>Scene18AssetAudit.Triangles(f.sharedMesh));Require(report.decorationTriangles<380000,"Decoration budget exceeded");Require(nav.IsFootprintWalkable(new Vector2(-130,0),new Vector2(212,424))&&nav.IsFootprintWalkable(new Vector2(130,0),new Vector2(212,424)),"Deployment navigation changed");Require(manager.terrainSurfaceAsset==originalSurface&&ground.GetComponent<MeshFilter>().sharedMesh==gm&&back.GetComponent<MeshFilter>().sharedMesh==bm,"Geometry changed");ActorMaterialBuildGuard.RequireValid(scene);
   report.passed=report.navigationUnchanged=report.groundMeshUnchanged=report.backdropGeometryUnchanged=report.noDecorationInPlayableRegion=true;File.WriteAllText(Logs+"/prepare.json",JsonUtility.ToJson(report,true));EditorUtility.SetDirty(d);EditorUtility.SetDirty(catalog);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();CapturePreview(Camera.main,catalog);
   Require(AssetDatabase.CopyAsset(Source+"/LaunchMenu.unity",Menu),"Copy menu");var menu=EditorSceneManager.OpenScene(Menu,OpenSceneMode.Single);Find<WarSandboxSceneSession>(menu).catalog=catalog;ActorMaterialBuildGuard.RequireValid(menu);EditorSceneManager.SaveScene(menu);AssetDatabase.SaveAssets();
  }
  static void CapturePreview(Camera camera,WarSandboxBattlefieldCatalog catalog){var rt=new RenderTexture(1280,720,24);var image=new Texture2D(1280,720,TextureFormat.RGB24,false);var old=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;image.ReadPixels(new Rect(0,0,1280,720),0,0);image.Apply();File.WriteAllBytes(Root+"/Preview.png",image.EncodeToPNG());File.WriteAllBytes(Logs+"/editor-overview.png",image.EncodeToPNG());}finally{camera.targetTexture=old;RenderTexture.active=active;rt.Release();Object.DestroyImmediate(rt);Object.DestroyImmediate(image);}AssetDatabase.ImportAsset(Root+"/Preview.png");var imp=(TextureImporter)AssetImporter.GetAtPath(Root+"/Preview.png");imp.maxTextureSize=512;imp.SaveAndReimport();foreach(var e in catalog.entries)e.preview=AssetDatabase.LoadAssetAtPath<Texture2D>(Root+"/Preview.png");EditorUtility.SetDirty(catalog);AssetDatabase.SaveAssets();}

  static float VisualHeight(Mesh mesh,float x,float z){var v=mesh.vertices;int n=Mathf.RoundToInt(Mathf.Sqrt(v.Length));Require(n*n==v.Length,"Unexpected backdrop layout");int ix=0,iz=0;while(ix<n-2&&v[ix+1].x<x)ix++;while(iz<n-2&&v[(iz+1)*n].z<z)iz++;int a=iz*n+ix;float tx=Mathf.InverseLerp(v[a].x,v[a+1].x,x),tz=Mathf.InverseLerp(v[a].z,v[a+n].z,z);return tx>=tz?(1-tx)*v[a].y+(tx-tz)*v[a+1].y+tz*v[a+n+1].y:(1-tz)*v[a].y+(tz-tx)*v[a+n].y+tx*v[a+n+1].y;}
  [Serializable]class RefineAudit21{public bool passed;public int groundedProps;public float maximumVisualPlacementCorrection;public bool gameGeometryUnchanged=true;}
  public static void Refine(){Require(!File.Exists(Logs+"/refine.json"),"Refine already completed");var scene=EditorSceneManager.OpenScene(Battle,OpenSceneMode.Single);Require(Find<MassEngineManager>(scene).TryGetTerrainContext(out surface,out _,out var error),error);var root=GameObject.Find("21 Artful Woodland - visual only outside navigation");var mesh=GameObject.Find("Visual Only Backdrop - No navigation or colliders").GetComponent<MeshFilter>().sharedMesh;var a=new RefineAudit21();foreach(Transform group in root.transform)foreach(Transform t in group){var b=BoundsOf(t.gameObject);if(Mathf.Max(Mathf.Abs(b.center.x),Mathf.Abs(b.center.z))<=256)continue;float delta=VisualHeight(mesh,b.center.x,b.center.z)-TerrainScaleBounds.BackdropHeight(surface,b.center.x,b.center.z);t.position+=Vector3.up*delta;a.maximumVisualPlacementCorrection=Mathf.Max(a.maximumVisualPlacementCorrection,Mathf.Abs(delta));a.groundedProps++;}
   var wood=GameObject.Find("Asymmetric forest belts");var ridge=GameObject.Find("Rock shelves and far ridgeline");var colors=new Color[512*512];foreach(Transform t in wood.transform){var b=BoundsOf(t.gameObject);Stamp(colors,b.center,Mathf.Max(9,b.size.x*.8f),Mathf.Max(9,b.size.z*.8f),false);Stamp(colors,b.center,3,3,false,true);}foreach(Transform t in ridge.transform){if(t.name.Contains("Mountain"))continue;var b=BoundsOf(t.gameObject);Stamp(colors,b.center,b.size.x*.75f+5,b.size.z*.75f+5,true);Stamp(colors,b.center,b.size.x*.4f+2,b.size.z*.4f+2,false,true);foreach(var rr in t.GetComponentsInChildren<Renderer>())rr.shadowCastingMode=ShadowCastingMode.On;}
   foreach(var m in root.GetComponentsInChildren<Renderer>().SelectMany(r=>r.sharedMaterials).Distinct()){if(m.shader.name!="Universal Render Pipeline/Lit")continue;var tex=m.GetTexture("_BaseMap");if(tex!=null&&AssetDatabase.GetAssetPath(tex)=="Assets/Game/Content/Battlefields/WoodlandArt/Textures/T4.png"){Require(AssetDatabase.GetAssetPath(m).StartsWith(Root+"/"),"Shared source material");m.SetColor("_BaseColor",new Color(.64f,.70f,.63f,1));EditorUtility.SetDirty(m);}}
   var mat=GameObject.Find("Plan B - Shared Render And Navigation Surface").GetComponent<Renderer>().sharedMaterial;mat.SetTexture("_DetailMask",Bake("ForestFloorMask",colors,true));EditorUtility.SetDirty(mat);a.passed=true;File.WriteAllText(Logs+"/refine.json",JsonUtility.ToJson(a,true));EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();CapturePreview(Camera.main,Find<WarSandboxRuntimeDeployment>(scene).battlefieldCatalog);Review();}
  public static void FinishVisuals(){Require(!File.Exists(Logs+"/layout-final.json"),"Already finalized");var scene=EditorSceneManager.OpenScene(Battle,OpenSceneMode.Single);Require(Find<MassEngineManager>(scene).TryGetTerrainContext(out surface,out _,out var error),error);var back=GameObject.Find("Visual Only Backdrop - No navigation or colliders").GetComponent<MeshFilter>().sharedMesh;var group=GameObject.Find("21 Grouped understory and trail verges").transform;var old=group.Cast<Transform>().Where(t=>t.name.Contains("grassPatch")).ToArray();rng=new System.Random(2107);int added=0;foreach(var source in old)for(int k=0;k<2;k++){var b=BoundsOf(source.gameObject);float angle=Rand(0,6.283f);var p=b.center+new Vector3(Mathf.Cos(angle)*Rand(.9f,2.4f),0,Mathf.Sin(angle)*Rand(.9f,2.4f));var go=Object.Instantiate(source.gameObject,group);go.name="21 clustered grass";go.transform.rotation=Quaternion.Euler(0,Rand(0,360),0);go.transform.localScale*=Rand(.65f,.95f);var nb=BoundsOf(go);float h=Mathf.Max(Mathf.Abs(p.x),Mathf.Abs(p.z))>256?VisualHeight(back,p.x,p.z):TerrainScaleBounds.BackdropHeight(surface,p.x,p.z);go.transform.position+=new Vector3(p.x,h-.06f,p.z)-new Vector3(nb.center.x,nb.min.y,nb.center.z);if(!Clear(BoundsOf(go))){Object.DestroyImmediate(go);continue;}added++;}
   var root=GameObject.Find("21 Artful Woodland - visual only outside navigation");var report=JsonUtility.FromJson<Audit21>(File.ReadAllText(Logs+"/prepare.json"));report.addedProps+=added;report.props=root.transform.Cast<Transform>().Sum(t=>t.childCount);report.renderers=root.GetComponentsInChildren<Renderer>().Length;report.decorationTriangles=root.GetComponentsInChildren<MeshFilter>().Sum(f=>Scene18AssetAudit.Triangles(f.sharedMesh));Require(report.decorationTriangles<380000,"Final budget exceeded");Require(root.GetComponentsInChildren<Collider>(true).Length==0,"Unexpected collisions");foreach(var r in root.GetComponentsInChildren<Renderer>())Require(Clear(r.bounds),"Final bounds intrude");ActorMaterialBuildGuard.RequireValid(scene);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();File.WriteAllText(Logs+"/layout-final.json",JsonUtility.ToJson(report,true));CapturePreview(Camera.main,Find<WarSandboxRuntimeDeployment>(scene).battlefieldCatalog);Review();}
  public static void FinishWood(){Require(!File.Exists(Logs+"/wood-finish.json"),"Wood already done");var scene=EditorSceneManager.OpenScene(Battle,OpenSceneMode.Single);var group=GameObject.Find("Irregular forest floor and trail landmarks").transform;var fences=group.Cast<Transform>().Where(t=>t.name.IndexOf("Fence",StringComparison.OrdinalIgnoreCase)>=0).ToArray();Require(fences.Length==7,"Fence count mismatch");var mat=new Material(Shader.Find("Universal Render Pipeline/Lit"));mat.name="21 warm timber - intentional solid color";mat.SetColor("_BaseColor",new Color(.28f,.16f,.075f,1));mat.SetFloat("_Smoothness",.04f);mat.enableInstancing=true;AssetDatabase.CreateAsset(mat,Root+"/Materials/WarmTimber.mat");foreach(var f in fences)foreach(var r in f.GetComponentsInChildren<Renderer>())r.sharedMaterials=r.sharedMaterials.Select(m=>mat).ToArray();EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();CapturePreview(Camera.main,Find<WarSandboxRuntimeDeployment>(scene).battlefieldCatalog);Review();File.WriteAllText(Logs+"/wood-finish.json","{\"passed\":true,\"fences\":7,\"intentionalSolidWoodColor\":true}");}
  static void ReviewShot(Camera c,string name){var rt=new RenderTexture(1280,720,24);var t=new Texture2D(1280,720,TextureFormat.RGB24,false);var old=c.targetTexture;var active=RenderTexture.active;try{c.targetTexture=rt;c.Render();RenderTexture.active=rt;t.ReadPixels(new Rect(0,0,1280,720),0,0);t.Apply();File.WriteAllBytes(Logs+"/"+name+".png",t.EncodeToPNG());}finally{c.targetTexture=old;RenderTexture.active=active;rt.Release();Object.DestroyImmediate(rt);Object.DestroyImmediate(t);}}
  public static void Review(){ShaderUtil.allowAsyncCompilation=false;var s=EditorSceneManager.OpenScene(Battle,OpenSceneMode.Single);var c=Camera.main;c.transform.position=new Vector3(-190,48,-316);c.transform.LookAt(new Vector3(-115,15,-238));ReviewShot(c,"editor-seam");c.transform.position=new Vector3(-276,19,-9);c.transform.LookAt(new Vector3(-307,9,29));ReviewShot(c,"editor-understory");var floor=GameObject.Find("21 Grouped understory and trail verges").transform.Cast<Transform>().Where(t=>t.name.Contains("grassPatch")).OrderBy(t=>(new Vector2(t.position.x,t.position.z)-new Vector2(-272,52)).sqrMagnitude).First();var target=floor.GetComponentInChildren<Renderer>().bounds.center;c.transform.position=target+new Vector3(10,7,-12);c.transform.LookAt(target+Vector3.up);ReviewShot(c,"editor-floor");var materials=GameObject.Find("21 Artful Woodland - visual only outside navigation").GetComponentsInChildren<Renderer>().SelectMany(r=>r.sharedMaterials).Concat(new[]{GameObject.Find("Plan B - Shared Render And Navigation Surface").GetComponent<Renderer>().sharedMaterial}).Distinct().ToArray();var tex=materials.SelectMany(m=>m.GetTexturePropertyNames().Select(p=>m.GetTexture(p))).OfType<Texture2D>().Distinct().ToArray();Require(tex.All(t=>t.width<=1024&&t.height<=1024),"Texture max cap exceeded");File.WriteAllText(Logs+"/texture-audit.json",JsonUtility.ToJson(new TextureAudit21{passed=true,materials=materials.Length,textures=tex.Select(t=>new TextureInfo{path=AssetDatabase.GetAssetPath(t),width=t.width,height=t.height,format=t.format.ToString()}).ToArray()},true));}
  [Serializable]class TextureAudit21{public bool passed;public int materials;public TextureInfo[] textures;}
  [Serializable]class BuildRow{public bool passed;public string buildGuid;public int errors,warnings;}
  public static void Build(){const string dir="Builds/WoodlandArt-20261005-21";Require(!Directory.Exists(dir),"Refuse overwrite21 build");Directory.CreateDirectory(dir);var r=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{Menu,Battle},locationPathName=dir+"/WarSandbox.exe",target=BuildTarget.StandaloneWindows64,options=BuildOptions.Development});File.WriteAllText(Logs+"/build.json",JsonUtility.ToJson(new BuildRow{passed=r.summary.result==BuildResult.Succeeded,buildGuid=r.summary.guid.ToString(),errors=(int)r.summary.totalErrors,warnings=(int)r.summary.totalWarnings},true));Require(r.summary.result==BuildResult.Succeeded,"Build21 failed");File.WriteAllText(dir+"/Start-Terrain.cmd","@echo off\r\ncd /d \"%~dp0\"\r\nstart \"\" \"WarSandbox.exe\" -screen-fullscreen 1 -window-mode exclusive -screen-width 1920 -screen-height 1080\r\n");}
 }
}
