using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.SceneManagement;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEditor.Build.Reporting;
using Object=UnityEngine.Object;
namespace MassEngine.Game.Editor {
 public static class Art20Builder {
  public const string Root="Assets/Game/Content/Battlefields/WoodlandArt",Source="Assets/Game/Experiments/MaterialFix",Battle=Root+"/ForestHills.unity",Menu=Root+"/LaunchMenu.unity",Logs="Logs/Art20-20261005";
  static Dictionary<string,Material> mats=new Dictionary<string,Material>();static Dictionary<string,Texture2D> textures=new Dictionary<string,Texture2D>();
  static List<Used> used=new List<Used>();static TerrainSurface surface;static System.Random rng=new System.Random(2005);
  [Serializable]class Used{public string prefab;public int instances;public long trianglesPerInstance;}
  [Serializable]class TextureInfo{public string path;public int width,height;public string format;}
  [Serializable]class Receipt{public bool passed;public int props,renderers,materials,textures,playableWidth=512;public long triangles;public Used[] sources;public TextureInfo[] textureInfo;public bool originalAssetsUntouched=true,collidersAdded=false;}
  static void Require(bool b,string e){if(!b)throw new Exception(e);}
  static T Find<T>(Scene s)where T:Component{foreach(var g in s.GetRootGameObjects()){var t=g.GetComponentInChildren<T>(true);if(t!=null)return t;}throw new Exception("Missing "+typeof(T).Name);}
  static T Clone<T>(T a,string name)where T:Object{var v=Object.Instantiate(a);v.name=name;AssetDatabase.CreateAsset(v,Root+"/"+name+".asset");return v;}
  static float Rand(float a,float b)=>a+(b-a)*(float)rng.NextDouble();
  static Texture2D TextureCopy(Texture t){if(t==null)return null;string path=AssetDatabase.GetAssetPath(t);if(string.IsNullOrEmpty(path)||!path.StartsWith("Assets/"))return null;if(textures.TryGetValue(path,out var known))return known;Require(!string.IsNullOrEmpty(path),"Texture without source");string dest=Root+"/Textures/T"+textures.Count+Path.GetExtension(path);Require(AssetDatabase.CopyAsset(path,dest),"Copy texture "+path);var importer=AssetImporter.GetAtPath(dest) as TextureImporter;Require(importer!=null,"Missing texture importer");importer.maxTextureSize=512;importer.mipmapEnabled=true;importer.isReadable=false;importer.textureCompression=TextureImporterCompression.Compressed;importer.crunchedCompression=false;importer.anisoLevel=2;var platform=importer.GetPlatformTextureSettings("Standalone");platform.overridden=true;platform.maxTextureSize=512;platform.format=TextureImporterFormat.Automatic;platform.textureCompression=TextureImporterCompression.Compressed;importer.SetPlatformTextureSettings(platform);importer.SaveAndReimport();var tex=AssetDatabase.LoadAssetAtPath<Texture2D>(dest);Require(tex.width<=512&&tex.height<=512,"Texture over budget");textures[path]=tex;return tex;}
  static Material MaterialCopy(Material original,bool far){string key=original.GetInstanceID()+":"+far;Require(original!=null,"Missing source material");if(mats.TryGetValue(key,out var result))return result;result=new Material(Shader.Find(far?"MassEngine/Art20 Distant Foliage":"Universal Render Pipeline/Lit"));result.name="20 "+original.name;result.enableInstancing=true;Texture t=original.HasProperty("_BaseMap")?original.GetTexture("_BaseMap"):null;if(t==null&&original.HasProperty("_MainTex"))t=original.GetTexture("_MainTex");if(t==null)t=original.mainTexture;result.SetTexture("_BaseMap",TextureCopy(t));Color c=original.HasProperty("_BaseColor")?original.GetColor("_BaseColor"):original.HasProperty("_Color")?original.GetColor("_Color"):Color.white;result.SetColor("_BaseColor",c);if(result.HasProperty("_Smoothness"))result.SetFloat("_Smoothness",.06f);if(result.HasProperty("_Metallic"))result.SetFloat("_Metallic",0);bool leaves=(original.name.ToLower().Contains("leave")||original.shader.name.Contains("Foliage"));bool clip=leaves||(original.HasProperty("_AlphaClip")&&original.GetFloat("_AlphaClip")>.5f)||original.IsKeywordEnabled("_ALPHATEST_ON");if(clip){result.SetFloat("_AlphaClip",1);result.SetFloat("_Cutoff",.45f);if(!far)result.EnableKeyword("_ALPHATEST_ON");result.SetOverrideTag("RenderType","TransparentCutout");result.renderQueue=2450;result.SetFloat("_Cull",0);}AssetDatabase.CreateAsset(result,Root+"/Materials/M"+mats.Count+".mat");mats[key]=result;return result;}
  static GameObject Place(string path,float x,float z,float height,float yaw,Transform parent,bool far=false){
   var prefab=AssetDatabase.LoadAssetAtPath<GameObject>(path);Require(prefab!=null,"Missing "+path);var go=(GameObject)PrefabUtility.InstantiatePrefab(prefab,parent);PrefabUtility.UnpackPrefabInstance(go,PrefabUnpackMode.Completely,InteractionMode.AutomatedAction);go.name="20 "+prefab.name;go.transform.rotation=Quaternion.Euler(0,yaw,0);
   // Keep an actual authored lower LOD, never simultaneously draw all LOD levels.
   foreach(var group in go.GetComponentsInChildren<LODGroup>(true)){var lods=group.GetLODs();int level=Math.Min(far?2:1,lods.Length-1);if(level>=0){var keep=new HashSet<Renderer>(lods[level].renderers.Where(r=>r!=null));foreach(var rr in lods.SelectMany(l=>l.renderers).Where(r=>r!=null).Distinct().ToArray())if(!keep.Contains(rr))Object.DestroyImmediate(rr.gameObject);}if(group!=null)Object.DestroyImmediate(group);}
   foreach(var col in go.GetComponentsInChildren<Collider>(true))Object.DestroyImmediate(col);foreach(var rb in go.GetComponentsInChildren<Rigidbody>(true))Object.DestroyImmediate(rb);foreach(var script in go.GetComponentsInChildren<MonoBehaviour>(true))if(script!=null)Object.DestroyImmediate(script);
   var renderers=go.GetComponentsInChildren<MeshRenderer>(true);Require(renderers.Length>0,"No renderers "+path);foreach(var r in renderers){r.enabled=true;r.gameObject.SetActive(true);}
   long triangles=go.GetComponentsInChildren<MeshFilter>(true).Sum(f=>Scene18AssetAudit.Triangles(f.sharedMesh));Require(triangles<=(path.Contains("Mountain")?2000:1000),"Per prop mesh budget exceeded: "+path+" "+triangles);
   Bounds bounds=renderers[0].bounds;foreach(var r in renderers)bounds.Encapsulate(r.bounds);go.transform.localScale*=height/Mathf.Max(.01f,bounds.size.y);bounds=renderers[0].bounds;foreach(var r in renderers)bounds.Encapsulate(r.bounds);float y=TerrainScaleBounds.BackdropHeight(surface,x,z);go.transform.position+=new Vector3(x,y,z)-new Vector3(bounds.center.x,bounds.min.y,bounds.center.z);
   bounds=renderers[0].bounds;foreach(var r in renderers){bounds.Encapsulate(r.bounds);r.sharedMaterials=r.sharedMaterials.Select(m=>MaterialCopy(m,far)).ToArray();r.shadowCastingMode=height>8&&!far&&used.Sum(u=>u.instances)%3==0?ShadowCastingMode.On:ShadowCastingMode.Off;r.receiveShadows=true;r.lightProbeUsage=LightProbeUsage.Off;r.reflectionProbeUsage=ReflectionProbeUsage.Off;GameObjectUtility.SetStaticEditorFlags(r.gameObject,StaticEditorFlags.BatchingStatic);}
   Require(!(bounds.min.x<242&&bounds.max.x> -242&&bounds.min.z<220&&bounds.max.z> -220),"Decoration intersects playable area: "+path);
   if(path.Contains("Mountain"))go.transform.position-=Vector3.up*height*.20f;var cull=go.AddComponent<LODGroup>();cull.SetLODs(new[]{new LOD(height<3?.006f:.0035f,renderers)});cull.RecalculateBounds();var u=used.FirstOrDefault(v=>v.prefab==path&&v.trianglesPerInstance==triangles);if(u==null){u=new Used{prefab=path,trianglesPerInstance=triangles};used.Add(u);}u.instances++;return go;
  }
  static string SC(string tail)=>"Assets/ThirdParty/Supercyan Free Forest Sample/Prefabs/Mobile/"+tail+".prefab";
  static string PT(string tail)=>"Assets/ThirdParty/Polytope Studio/Lowpoly_Environments/Prefabs/"+tail+".prefab";
  static string PP(string tail)=>"Assets/ThirdParty/Pure Poly/Free Low Poly Nature Pack/Prefabs/"+tail+".prefab";

  static Texture2D GroundTexture(string source,string name,int max){string dest=Root+"/Textures/"+name+".png";Require(AssetDatabase.CopyAsset(source,dest),"Ground texture missing");var imp=(TextureImporter)AssetImporter.GetAtPath(dest);imp.maxTextureSize=max;imp.mipmapEnabled=true;imp.anisoLevel=4;imp.textureCompression=TextureImporterCompression.Compressed;imp.crunchedCompression=false;imp.isReadable=false;var p=imp.GetPlatformTextureSettings("Standalone");p.overridden=true;p.maxTextureSize=max;p.format=TextureImporterFormat.Automatic;p.textureCompression=TextureImporterCompression.Compressed;imp.SetPlatformTextureSettings(p);imp.SaveAndReimport();var t=AssetDatabase.LoadAssetAtPath<Texture2D>(dest);Require(t.width<=max&&t.height<=max,"Ground texture cap");return t;}
  static bool Spaced(List<Vector2> taken,Vector2 p,float distance){return taken.All(q=>(q-p).sqrMagnitude>distance*distance);}
  [Serializable]class LayoutAudit{public bool passed,navigationUnchanged,groundMeshUnchanged,noDecorationInPlayableRegion;public int trees,props,renderers,materials,groundTextures=3;public long decorationTriangles;public string surfacePath,groundMeshPath;public Used[] sources;public TextureInfo[] textures;}
  public static void Prepare(){
   Require(!Directory.Exists(Root),"Refuse overwrite20");Directory.CreateDirectory(Root+"/Textures");Directory.CreateDirectory(Root+"/Materials");Directory.CreateDirectory(Logs);AssetDatabase.Refresh();mats.Clear();textures.Clear();used.Clear();rng=new System.Random(2005);
   Require(AssetDatabase.CopyAsset(Source+"/ForestHills.unity",Battle),"Copy battle");var scene=EditorSceneManager.OpenScene(Battle,OpenSceneMode.Single);var manager=Find<MassEngineManager>(scene);var deployment=Find<WarSandboxRuntimeDeployment>(scene);Require(manager.TryGetTerrainContext(out surface,out _,out var error),error);Require(surface.Size==new Vector2(512,512),"Map changed");
   var catalog=Clone(deployment.battlefieldCatalog,"Catalog");deployment.battlefieldCatalog=catalog;foreach(var entry in catalog.entries){entry.id="forest-art20";entry.scenePath=Battle;entry.displayName="林间旷野 · 林缘与岩坡";entry.description="手绘地表 / 自然林缘 / 岩坡远山\n开阔战场保留，默认2048人。";entry.briefing="草地、磨损道路与石质坡面分层；外围成片疏密林缘、岩坡和远山取代均匀小树团。\n512地图和中央布阵/导航不变，立体装饰均在原禁行带与背景区。\n低面数素材，贴图512为主，主草地1024；十万人仍仅为高负载试验。";}catalog.defaultEntryId="forest-art20";
   var old=GameObject.Find("18 Lightweight Store Scenery - outside navigation");Require(old!=null,"Missing old scenery root");Object.DestroyImmediate(old);
   var ground=GameObject.Find("Plan B - Shared Render And Navigation Surface");var groundMesh=ground.GetComponent<MeshFilter>().sharedMesh;var originalSurface=manager.terrainSurfaceAsset;
   var grass=GroundTexture("Assets/ThirdParty/Supercyan Free Forest Sample/Textures/Ground/forestpack_moss_light_tile_diffuse.png","Ground-Grass",1024);var dirt=GroundTexture("Assets/ThirdParty/Supercyan Free Forest Sample/Textures/Ground/forestpack_road_tile_diffuse.png","Ground-Road",512);var stoneTex=GroundTexture("Assets/ThirdParty/Supercyan Free Forest Sample/Textures/Ground/forestpack_texture_rock_tile_diffuse.png","Ground-Rock",512);
   var gm=new Material(Shader.Find("MassEngine/Art20 Ground"));Require(gm.shader!=null,"Missing terrain shader");gm.SetTexture("_Grass",grass);gm.SetTexture("_Road",dirt);gm.SetTexture("_Rock",stoneTex);gm.SetColor("_GrassTint",new Color(.9f,1,.83f));gm.SetColor("_RoadTint",new Color(1,.95f,.82f));gm.SetVector("_HazeColor",new Vector4(.38f,.57f,.62f,1));AssetDatabase.CreateAsset(gm,Root+"/Ground.mat");ground.GetComponent<MeshRenderer>().sharedMaterial=gm;GameObject.Find("Visual Only Backdrop - No navigation or colliders").GetComponent<MeshRenderer>().sharedMaterial=gm;
   var scenery=new GameObject("20 Artful Woodland - visual only outside navigation");var woodland=new GameObject("Asymmetric forest belts");woodland.transform.SetParent(scenery.transform);var geology=new GameObject("Rock shelves and far ridgeline");geology.transform.SetParent(scenery.transform);var understory=new GameObject("Irregular forest floor and trail landmarks");understory.transform.SetParent(scenery.transform);
   string pine=PT("Trees/PT_Pine_Tree_03_green"),fir=SC("Tree/Fir/Mobile_forestpack_tree_fir_tall"),leaf=SC("Tree/Leaf/Normal/Mobile_forestpack_tree_1_leaf_1"),rock=SC("Stone/Mobile_forestpack_stone_large_1"),moss=PP("PP_Rock_Moss_Grown_11");
   // Poisson-like thinning of a noise-shaped perimeter, not a repeated ring of identical islands.
   var trees=new List<Vector2>();for(int attempt=0;attempt<14000&&trees.Count<260;attempt++){
    var p=new Vector2(Rand(-380,380),Rand(-370,390));if(Mathf.Abs(p.x)<266&&Mathf.Abs(p.y)<249)continue;if(Mathf.Abs(p.x)>355&&Mathf.Abs(p.y)>340)continue;
    float density=.28f+.58f*Mathf.PerlinNoise(p.x*.014f+32,p.y*.014f+71);if(p.y< -270)density*=.55f;if(Mathf.Abs(p.y-16*Mathf.Sin(p.x/54))<23&&Mathf.Abs(p.x)>245)continue;
    if(Rand(0,1)>density||!Spaced(trees,p,10.8f))continue;trees.Add(p);bool far=Mathf.Max(Mathf.Abs(p.x),Mathf.Abs(p.y))>305;float h=far?Rand(22,34):Rand(17,27);if(p.y< -260)h*=.85f;int kind=rng.Next(10);Place(far?pine:kind<2?leaf:kind<6?fir:pine,p.x,p.y,h,Rand(0,360),woodland.transform,far);
   }Require(trees.Count>=220,"Forest sampling too sparse");
   // A distant band has lower geometry, softer atmospheric color, and varied spacing.
   for(int k=0;k<54;k++){float a=Rand(.12f,Mathf.PI-.12f),rad=Rand(420,525);var p=new Vector2(Mathf.Cos(a)*rad,Mathf.Sin(a)*rad);if(Mathf.Max(Mathf.Abs(p.x),Mathf.Abs(p.y))<330)continue;Place(pine,p.x,p.y,Rand(22,38),Rand(0,360),woodland.transform,true);}
   // West rocky shoulder and north-east outcrops are offset, not a symmetrical rock wall.
   for(int k=0;k<18;k++){float z=-180+k*21+Rand(-8,8),x=-306+12*Mathf.Sin(z/57);Place(k%3==0?moss:rock,x,z,Rand(6,12),Rand(0,360),geology.transform);}
   for(int k=0;k<14;k++){float x=105+k*13+Rand(-6,6),z=281+17*Mathf.Sin(x/44);Place(k%3==0?moss:rock,x,z,Rand(4,9),Rand(0,360),geology.transform);}
   // Mountains are few large silhouettes (1830/1946 triangles), not high-poly forest assets.
   foreach(var p in new[]{new Vector3(-475,70,630),new Vector3(-270,100,560),new Vector3(-90,115,660),new Vector3(115,84,615),new Vector3(320,92,560),new Vector3(610,65,390),new Vector3(-650,65,150),new Vector3(650,64,-150)})Place(PP(rng.Next(2)==0?"PP_Forest_Mountain_Moss_01":"PP_Forest_Mountain_Moss_02"),p.x,p.z,p.y,Rand(0,360),geology.transform,true);
   var details=new List<Vector2>();for(int attempt=0;attempt<5000&&details.Count<210;attempt++){
    var p=new Vector2(Rand(-340,340),Rand(-315,345));if(Mathf.Abs(p.x)<253&&Mathf.Abs(p.y)<232)continue;if(!Spaced(details,p,4.5f))continue;float n=Mathf.PerlinNoise(p.x*.034f+13,p.y*.034f+17);if(n<.43f)continue;details.Add(p);int t=details.Count%6;string prefab=t==0?moss:t==1?rock:t==2?PT("Shrubs/PT_Generic_Shrub_01_green"):t==3?PT("Plants/PT_Grass_02"):t==4?PT("Flowers/PT_Poppy_02"):SC("Tree/Treestump/Mobile_forestpack_tree_stump_1");float height=t<2?Rand(1.7f,3.8f):t==2?Rand(1.2f,2.1f):t==5?Rand(1,1.8f):Rand(.6f,1.2f);Place(prefab,p.x,p.y,height,Rand(0,360),understory.transform);}
   // Trail-side timber and a broken boundary fence: readable landmarks, no gameplay blockers.
   Place(SC("Sign/Mobile_forestpack_roadSign_westEast_1"),-258,35,4.2f,80,understory.transform);
   for(int k=0;k<4;k++)Place(PT("Trees/PT_Fruit_Tree_01_logs"),275+k*4,93+Rand(-5,5),Rand(1.5f,2.5f),Rand(55,115),understory.transform);
   for(int k=0;k<7;k++)Place("Assets/ThirdParty/Polytope Studio/Lowpoly_Village/Prefabs/Modular/Fence/PT_Modular_Fence_Wood_01.prefab",-265,55+k*7,2.1f,90+Rand(-7,7),understory.transform);
   Require(manager.terrainSurfaceAsset==originalSurface&&ground.GetComponent<MeshFilter>().sharedMesh==groundMesh,"Geometry/nav altered");Require(scenery.GetComponentsInChildren<Collider>(true).Length==0,"Decoration collision changed");ActorMaterialBuildGuard.RequireValid(scene);
   EditorUtility.SetDirty(deployment);EditorUtility.SetDirty(catalog);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();CapturePreview(Camera.main,catalog);
   var allTex=AssetDatabase.FindAssets("t:Texture2D",new[]{Root+"/Textures"}).Select(AssetDatabase.GUIDToAssetPath).Select(AssetDatabase.LoadAssetAtPath<Texture2D>).ToArray();Require(allTex.All(t=>t.width<=1024&&t.height<=1024),"Texture cap exceeded");long triangles=used.Sum(u=>u.instances*u.trianglesPerInstance);Require(triangles<360000,"Scenery triangle budget exceeded");var report=new LayoutAudit{passed=true,navigationUnchanged=true,groundMeshUnchanged=true,noDecorationInPlayableRegion=true,trees=used.Where(u=>u.prefab.Contains("_tree_fir_")||u.prefab.Contains("_tree_1_leaf_")||u.prefab.Contains("PT_Pine_Tree_03_green")).Sum(u=>u.instances),props=used.Sum(u=>u.instances),renderers=scenery.GetComponentsInChildren<Renderer>().Length,materials=mats.Count+1,decorationTriangles=triangles,surfacePath=AssetDatabase.GetAssetPath(originalSurface),groundMeshPath=AssetDatabase.GetAssetPath(groundMesh),sources=used.ToArray(),textures=allTex.Select(t=>new TextureInfo{path=AssetDatabase.GetAssetPath(t),width=t.width,height=t.height,format=t.format.ToString()}).ToArray()};File.WriteAllText(Logs+"/prepare.json",JsonUtility.ToJson(report,true));
   Require(AssetDatabase.CopyAsset(Source+"/LaunchMenu.unity",Menu),"Copy menu");var menu=EditorSceneManager.OpenScene(Menu,OpenSceneMode.Single);Find<WarSandboxSceneSession>(menu).catalog=catalog;ActorMaterialBuildGuard.RequireValid(menu);EditorSceneManager.SaveScene(menu);AssetDatabase.SaveAssets();Debug.Log("ART20_PREPARED");
  }
  static void CapturePreview(Camera camera,WarSandboxBattlefieldCatalog catalog){var rt=new RenderTexture(1280,720,24);var image=new Texture2D(1280,720,TextureFormat.RGB24,false);var old=camera.targetTexture;var active=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;image.ReadPixels(new Rect(0,0,1280,720),0,0);image.Apply();File.WriteAllBytes(Root+"/Preview.png",image.EncodeToPNG());File.WriteAllBytes(Logs+"/editor-overview.png",image.EncodeToPNG());}finally{camera.targetTexture=old;RenderTexture.active=active;rt.Release();Object.DestroyImmediate(rt);Object.DestroyImmediate(image);}AssetDatabase.ImportAsset(Root+"/Preview.png");var imp=(TextureImporter)AssetImporter.GetAtPath(Root+"/Preview.png");imp.maxTextureSize=512;imp.SaveAndReimport();foreach(var e in catalog.entries)e.preview=AssetDatabase.LoadAssetAtPath<Texture2D>(Root+"/Preview.png");EditorUtility.SetDirty(catalog);AssetDatabase.SaveAssets();}

  static void MoveVisual(GameObject go,float x,float z,float height,float yaw,bool mountain){var rr=go.GetComponentsInChildren<Renderer>();go.transform.rotation=Quaternion.Euler(0,yaw,0);var b=rr[0].bounds;foreach(var r in rr)b.Encapsulate(r.bounds);float factor=height/b.size.y;go.transform.localScale*=factor;if(mountain){var v=go.transform.localScale;go.transform.localScale=new Vector3(v.x*1.7f,v.y,v.z*1.5f);}b=rr[0].bounds;foreach(var r in rr)b.Encapsulate(r.bounds);go.transform.position+=new Vector3(x,TerrainScaleBounds.BackdropHeight(surface,x,z)-height*(mountain?.24f:.07f),z)-new Vector3(b.center.x,b.min.y,b.center.z);b=rr[0].bounds;foreach(var r in rr)b.Encapsulate(r.bounds);Require(!(b.min.x<242&&b.max.x> -242&&b.min.z<220&&b.max.z> -220),"Refined landmark enters playable area");if(mountain)foreach(var r in rr)foreach(var m in r.sharedMaterials){Require(AssetDatabase.GetAssetPath(m).StartsWith(Root+"/"),"Refuse shared source edit");m.SetFloat("_MountainGrade",1);EditorUtility.SetDirty(m);}}
  public static void Refine(){Require(!File.Exists(Logs+"/refine.json"),"Refine already done");File.Copy(Battle,Logs+"/draft01-scene.unity",false);File.Copy(Logs+"/editor-overview.png",Logs+"/draft01-overview.png",false);var scene=EditorSceneManager.OpenScene(Battle,OpenSceneMode.Single);Require(Find<MassEngineManager>(scene).TryGetTerrainContext(out surface,out _,out var error),error);rng=new System.Random(2006);var ridge=GameObject.Find("Rock shelves and far ridgeline").transform;Require(ridge.childCount==40,"Unexpected landmark layout");var west=new[]{new Vector2(-306,-146),new Vector2(-318,25),new Vector2(-308,162)};for(int k=0;k<18;k++){var p=west[k/6];int n=k%6;float a=n*2.4f+Rand(-.2f,.2f),d=n==0?0:Rand(6,17);MoveVisual(ridge.GetChild(k).gameObject,p.x+Mathf.Cos(a)*d,p.y+Mathf.Sin(a)*d,n==0?Rand(11,14):Rand(4,9),Rand(0,360),false);}var north=new[]{new Vector2(130,289),new Vector2(250,291)};for(int k=0;k<14;k++){var p=north[k/7];int n=k%7;float a=n*2.4f,d=n==0?0:Rand(6,18);MoveVisual(ridge.GetChild(18+k).gameObject,p.x+Mathf.Cos(a)*d,p.y+Mathf.Sin(a)*d*.65f,n==0?Rand(9,12):Rand(3,8),Rand(0,360),false);}var peaks=new[]{new Vector3(-355,50,555),new Vector3(-220,65,598),new Vector3(-72,92,620),new Vector3(73,74,598),new Vector3(230,59,555),new Vector3(372,47,530),new Vector3(-650,60,150),new Vector3(650,58,-150)};for(int k=0;k<8;k++){var p=peaks[k];MoveVisual(ridge.GetChild(32+k).gameObject,p.x,p.z,p.y,Rand(0,360),true);}EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();CapturePreview(Camera.main,Find<WarSandboxRuntimeDeployment>(scene).battlefieldCatalog);File.WriteAllText(Logs+"/refine.json","{\"passed\":true,\"landmarksRepositioned\":40,\"groundColorGraded\":true,\"playableBoundsPreserved\":true}");}
  [Serializable]class BuildRow{public bool passed;public string buildGuid;public int errors,warnings;}
  public static void Build(){const string dir="Builds/WoodlandArt-20261005-20";Require(!Directory.Exists(dir),"Refuse overwrite20 build");Directory.CreateDirectory(dir);var r=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{Menu,Battle},locationPathName=dir+"/WarSandbox.exe",target=BuildTarget.StandaloneWindows64,options=BuildOptions.Development});File.WriteAllText(Logs+"/build.json",JsonUtility.ToJson(new BuildRow{passed=r.summary.result==BuildResult.Succeeded,buildGuid=r.summary.guid.ToString(),errors=(int)r.summary.totalErrors,warnings=(int)r.summary.totalWarnings},true));Require(r.summary.result==BuildResult.Succeeded,"Build20 failed");File.WriteAllText(dir+"/Start-Terrain.cmd","@echo off\r\ncd /d \"%~dp0\"\r\nstart \"\" \"WarSandbox.exe\" -screen-fullscreen 1 -window-mode exclusive -screen-width 1920 -screen-height 1080\r\n");}
 }
}
