using System;using System.IO;using System.Linq;using UnityEngine;using UnityEditor;using UnityEngine.SceneManagement;using UnityEditor.SceneManagement;using UnityEditor.Build.Reporting;using Object=UnityEngine.Object;
namespace MassEngine.Game.Editor {
 public static class Camera24Builder {
  const string Root="Assets/Game/Content/Battlefields/CameraTerrain",Source="Assets/Game/Experiments/MenuFlow",Logs="Logs/Camera24-20261005";
  static readonly string[] Names={"Green","Autumn","Winter"};
  static void Check(bool b,string e){if(!b)throw new Exception(e);}
  static T Find<T>(Scene s)where T:Component{foreach(var g in s.GetRootGameObjects()){var c=g.GetComponentInChildren<T>(true);if(c!=null)return c;}throw new Exception("Missing "+typeof(T));}
  public static void Prepare(){Check(!Directory.Exists(Root),"Refuse existing Camera24");Directory.CreateDirectory(Root);Directory.CreateDirectory(Logs);AssetDatabase.Refresh();var mesh=AssetDatabase.LoadAssetAtPath<Mesh>("Assets/Game/Content/Battlefields/ForestTerrain/Backdrop.asset");var vertices=mesh.vertices;int n=Mathf.RoundToInt(Mathf.Sqrt(vertices.Length));Check(n*n==vertices.Length,"Unexpected backdrop topology");var field=ScriptableObject.CreateInstance<CameraGround24>();field.coordinates=vertices.Take(n).Select(v=>v.x).ToArray();field.heights=vertices.Select(v=>v.y).ToArray();for(int z=0;z<n;z++)for(int x=0;x<n;x++)Check(Mathf.Abs(vertices[z*n+x].x-field.coordinates[x])<.001f&&Mathf.Abs(vertices[z*n+x].z-field.coordinates[z])<.001f,"Grid order");var playable=AssetDatabase.LoadAssetAtPath<Mesh>("Assets/Game/Content/Battlefields/ForestTerrain/GroundMesh.asset");float err=0;foreach(var v in playable.vertices)err=Mathf.Max(err,Mathf.Abs(field.Height(v.x,v.z)-v.y));Check(err<.001f,"Ground height bake mismatch");AssetDatabase.CreateAsset(field,Root+"/VisualGround.asset");
   var cat=Object.Instantiate(AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Source+"/Catalog.asset"));for(int i=0;i<3;i++)cat.entries[i].scenePath=Root+"/"+Names[i]+".unity";AssetDatabase.CreateAsset(cat,Root+"/Catalog.asset");AssetDatabase.SaveAssets();
   foreach(var name in Names){string path=Root+"/"+name+".unity";Check(AssetDatabase.CopyAsset(Source+"/"+name+".unity",path),"Copy scene");var s=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);cat=AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Root+"/Catalog.asset");var d=Find<WarSandboxRuntimeDeployment>(s);d.battlefieldCatalog=cat;EditorUtility.SetDirty(d);var owner=Find<MyCameraManager>(s);Check(owner.GetComponent<BattlefieldCameraComfort24>()==null,"Duplicate controller");var comfort=owner.gameObject.AddComponent<BattlefieldCameraComfort24>();comfort.owner=owner;comfort.ground=AssetDatabase.LoadAssetAtPath<CameraGround24>(Root+"/VisualGround.asset");comfort.envelope=Find<TerrainScaleBounds>(s);Check(comfort.envelope.maximumHorizontalRadius==480&&comfort.envelope.maximumDistance==720,"Unexpected envelope");comfort.envelope.enabled=false;EditorUtility.SetDirty(comfort.envelope);Check(owner.ControlledCamera!=null,"Missing camera");ActorMaterialBuildGuard.RequireValid(s);EditorUtility.SetDirty(comfort);EditorSceneManager.SaveScene(s);}
   Check(AssetDatabase.CopyAsset(Source+"/LaunchMenu.unity",Root+"/LaunchMenu.unity"),"Copy menu");var menu=EditorSceneManager.OpenScene(Root+"/LaunchMenu.unity",OpenSceneMode.Single);var session=Find<WarSandboxSceneSession>(menu);session.catalog=AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Root+"/Catalog.asset");EditorUtility.SetDirty(session);ActorMaterialBuildGuard.RequireValid(menu);EditorSceneManager.SaveScene(menu);AssetDatabase.SaveAssets();File.WriteAllText(Logs+"/prepare.json","{\"passed\":true,\"newScenes\":4,\"visualGrid\":"+n+",\"maximumHeightBakeError\":"+err.ToString(System.Globalization.CultureInfo.InvariantCulture)+",\"onlyNewScenesOptIn\":true}");
  }
  [Serializable]class Receipt{public bool passed;public string buildGuid;public int errors,warnings;}
  public static void Build(){const string dir="Builds/CameraComfort-20261005-24";Check(!Directory.Exists(dir),"Refuse existing build24");Directory.CreateDirectory(dir);var r=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{Root+"/LaunchMenu.unity"}.Concat(Names.Select(n=>Root+"/"+n+".unity")).ToArray(),locationPathName=dir+"/WarSandbox.exe",target=BuildTarget.StandaloneWindows64,options=BuildOptions.Development});File.WriteAllText(Logs+"/build.json",JsonUtility.ToJson(new Receipt{passed=r.summary.result==BuildResult.Succeeded,buildGuid=r.summary.guid.ToString(),errors=(int)r.summary.totalErrors,warnings=(int)r.summary.totalWarnings},true));Check(r.summary.result==BuildResult.Succeeded,"Build24 failed");File.WriteAllText(dir+"/Start-Game.cmd","@echo off\r\ncd /d \"%~dp0\"\r\nstart \"\" \"WarSandbox.exe\" -screen-fullscreen 1 -window-mode exclusive -screen-width 1920 -screen-height 1080\r\n");}
 }
}
