using System;using System.IO;using System.Linq;using UnityEngine;using UnityEditor;using UnityEngine.SceneManagement;using UnityEditor.SceneManagement;using UnityEditor.Build.Reporting;using Object=UnityEngine.Object;
namespace MassEngine.Game.Editor {public static class Flow23Builder {
 const string Root="Assets/Game/Experiments/MenuFlow",Source="Assets/Game/Content/Battlefields/WinterContrast",Logs="Logs/Flow23-20261005";
 static readonly string[] Names={"Green","Autumn","Winter"};
 static T Find<T>(Scene s) where T:Component {foreach(var g in s.GetRootGameObjects()){var c=g.GetComponentInChildren<T>(true);if(c!=null)return c;}throw new Exception("Missing "+typeof(T));}
 public static void Prepare(){if(Directory.Exists(Root))throw new Exception("Refuse overwrite Flow23");Directory.CreateDirectory(Root);Directory.CreateDirectory(Logs);AssetDatabase.Refresh();var cat=Object.Instantiate(AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Source+"/Catalog.asset"));for(int i=0;i<3;i++)cat.entries[i].scenePath=Root+"/"+Names[i]+".unity";AssetDatabase.CreateAsset(cat,Root+"/Catalog.asset");AssetDatabase.SaveAssets();foreach(var n in Names){if(!AssetDatabase.CopyAsset(Source+"/"+n+".unity",Root+"/"+n+".unity"))throw new Exception("Copy scene");var s=EditorSceneManager.OpenScene(Root+"/"+n+".unity",OpenSceneMode.Single);cat=AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Root+"/Catalog.asset");var d=Find<WarSandboxRuntimeDeployment>(s);d.battlefieldCatalog=cat;d.controller.gameObject.AddComponent<FlowPolish23>();EditorUtility.SetDirty(d);ActorMaterialBuildGuard.RequireValid(s);EditorSceneManager.SaveScene(s);}if(!AssetDatabase.CopyAsset(Source+"/LaunchMenu.unity",Root+"/LaunchMenu.unity"))throw new Exception("Copy menu");var m=EditorSceneManager.OpenScene(Root+"/LaunchMenu.unity",OpenSceneMode.Single);var session=Find<WarSandboxSceneSession>(m);session.catalog=AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Root+"/Catalog.asset");EditorUtility.SetDirty(session);ActorMaterialBuildGuard.RequireValid(m);EditorSceneManager.SaveScene(m);AssetDatabase.SaveAssets();File.WriteAllText(Logs+"/prepare.json","{\"passed\":true,\"newScenes\":4,\"sceneOnlyOptIn\":true}");}
 [Serializable]class Receipt {public bool passed;public string buildGuid;public int errors,warnings;}
 public static void Build(){const string dir="Builds/FlowPolish-20261005-23";if(Directory.Exists(dir))throw new Exception("Refuse existing build");Directory.CreateDirectory(dir);var r=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{Root+"/LaunchMenu.unity"}.Concat(Names.Select(n=>Root+"/"+n+".unity")).ToArray(),locationPathName=dir+"/WarSandbox.exe",target=BuildTarget.StandaloneWindows64,options=BuildOptions.Development});File.WriteAllText(Logs+"/build.json",JsonUtility.ToJson(new Receipt{passed=r.summary.result==BuildResult.Succeeded,buildGuid=r.summary.guid.ToString(),errors=(int)r.summary.totalErrors,warnings=(int)r.summary.totalWarnings},true));if(r.summary.result!=BuildResult.Succeeded)throw new Exception("Build failed");File.WriteAllText(dir+"/Start-Game.cmd","@echo off\r\ncd /d \"%~dp0\"\r\nstart \"\" \"WarSandbox.exe\" -screen-fullscreen 1 -window-mode exclusive -screen-width 1920 -screen-height 1080\r\n");}
}}
