// Editor-only supplemental integration probe. No player scripts/assets or victory data are changed.
using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using UnityEngine;using UnityEngine.UI;using UnityEditor;using UnityEditor.SceneManagement;using static UnityEngine.Object;
namespace MassEngine.Game.Editor {
 [InitializeOnLoad]public static class NaturalResult27ProbeDriver {
  const string Key="NaturalResult27ProbeActive";
  static NaturalResult27ProbeDriver(){EditorApplication.playModeStateChanged+=Changed;}
  public static void Begin(){if(EditorApplication.isPlayingOrWillChangePlaymode)throw new Exception("Refuse existing Play Mode");string p=NaturalResult27Probe.Output; if(Directory.Exists(p))throw new Exception("Refuse existing probe evidence");Directory.CreateDirectory(p);SessionState.SetBool(Key,true);EditorBuildSettings.scenes=new[]{"LaunchMenu","Green","Autumn","Winter"}.Select(n=>new EditorBuildSettingsScene("Assets/Game/Experiments/BattleResults/"+n+".unity",true)).ToArray();EditorSceneManager.OpenScene("Assets/Game/Experiments/BattleResults/LaunchMenu.unity",OpenSceneMode.Single);EditorApplication.EnterPlaymode();}
  static void Changed(PlayModeStateChange state){if(state!=PlayModeStateChange.EnteredPlayMode||!SessionState.GetBool(Key,false))return;SessionState.SetBool(Key,false);new NaturalResult27Probe().StartProbe();}
 }
 public sealed class NaturalResult27Probe {
  public static string Output=>Path.GetFullPath("Logs/Results27-20261005/natural-editor-probe-02");
  [Serializable]class Round{public string reason,phase;public int winner,initial0,initial1,survivors0,survivors1;public float realSeconds,battleSeconds,averageFps;}
  [Serializable]class Receipt{public bool passed,editorPlayMode=true,osInputTest=false,naturalVictoryTest,forcedVictory=false,highCountStress=false;public string stage,error;public int units=2048;public Round[] rounds;public string[] checks;}
  Receipt r=new Receipt();List<Round> rounds=new List<Round>();List<string> checks=new List<string>();WarSandboxBattleController c;WarSandboxRuntimeDeployment d;WarSandboxDeploymentEntry[] expected;int firstFrame;Stack<IEnumerator> stack;
  static void Check(bool b,string e){if(!b)throw new Exception(e);}
  static Button B(string n)=>FindObjectsByType<Button>(FindObjectsSortMode.None).Single(b=>b.name==n&&b.gameObject.activeInHierarchy);
  static string Txt(string n)=>GameObject.Find(n).GetComponentInChildren<Text>().text;
  void Shot(string name)=>ScreenCapture.CaptureScreenshot(Path.Combine(Output,name+".png"));
  public void StartProbe(){stack=new Stack<IEnumerator>();stack.Push(Run());EditorApplication.update+=Pump;}
  void Pump(){try{if(!EditorApplication.isPlaying)throw new Exception("Play mode ended before probe completed");while(stack.Count>0){if(!stack.Peek().MoveNext()){stack.Pop();continue;}var n=stack.Peek().Current;if(n is IEnumerator nested){stack.Push(nested);continue;}return;}r.passed=true;Finish(0);}catch(Exception e){r.error=e.ToString();Finish(1);}}
  void Finish(int code){EditorApplication.update-=Pump;r.rounds=rounds.ToArray();r.checks=checks.ToArray();File.WriteAllText(Path.Combine(Output,"receipt.json"),JsonUtility.ToJson(r,true));Debug.Log("NATURAL27_RESULT "+JsonUtility.ToJson(r));EditorApplication.Exit(code);}
  void CompareDraft(){var a=d.Draft.Snapshot();Check(a.Length==expected.Length,"Draft size changed");for(int i=0;i<a.Length;i++){var e=expected[i];Check(a[i].template==e.template&&a[i].Name==e.Name&&a[i].teamId==e.teamId&&a[i].count==e.count,"Draft identity/count changed");Check(Vector3.Distance(a[i].center,e.center)<.001f&&Mathf.Abs(a[i].density-e.density)<.0001f&&Mathf.Abs(a[i].aspect-e.aspect)<.0001f&&Vector3.Distance(a[i].manualSize,e.manualSize)<.001f,"Draft placement/formation changed");}}
  void CompareRuntime(){Check(WarSandboxDeploymentDraft.TryCapture(c.manager.scenarioConfig,out var draft,out var error),error);var a=draft.Snapshot();Check(a.Length==expected.Length,"Runtime size changed");for(int i=0;i<a.Length;i++){var e=expected[i];Check(a[i].count==e.count&&a[i].teamId==e.teamId&&a[i].Name==e.Name,"Runtime identity/count changed");Check(Vector2.Distance(new Vector2(a[i].center.x,a[i].center.z),new Vector2(e.center.x,e.center.z))<.001f,"Runtime placement changed");Check(Mathf.Abs(a[i].density-e.density)<.0001f&&Mathf.Abs(a[i].aspect-e.aspect)<.0001f&&Vector3.Distance(a[i].manualSize,e.manualSize)<.001f,"Runtime formation changed");}}
  IEnumerator WaitForNatural(int number){r.stage="natural-round-"+number;B("battle-tools").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);B("speed-3").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("battle-tools").onClick.Invoke();Check(Mathf.Abs(c.SimulationSpeed-4)<.001f,"4x UI failed");float begin=Time.realtimeSinceStartup,next=begin;firstFrame=Time.frameCount;
   while(!c.BattleResult.valid){float elapsed=Time.realtimeSinceStartup-begin;Check(elapsed<180,"Natural battle did not settle within 180s; not forced");if(elapsed>10)Check((Time.frameCount-firstFrame)/elapsed>=10,"Default-count FPS under safety floor; stopped, no extra pressure");if(Time.realtimeSinceStartup>=next){Debug.Log("NATURAL27_PROGRESS round="+number+" elapsed="+elapsed+" survivors="+c.GetAliveUnitCount(0)+"/"+c.GetAliveUnitCount(1));next=Time.realtimeSinceStartup+15;}yield return new WaitForSecondsRealtime(.5f);}
   Check(c.BattleResult.victoryReason!=WarSandboxVictoryReason.ManualEnd,"Unexpected manual settlement");Check(c.BattleResult.TryGetArmy(0,out var a)&&c.BattleResult.TryGetArmy(1,out _),"Result armies missing");c.BattleResult.TryGetArmy(1,out var b);Check(a.initial==expected[0].count&&b.initial==expected[1].count,"Natural result lost initial counts");Check(a.survivors+a.Casualties==a.initial&&b.survivors+b.Casualties==b.initial,"Result totals inconsistent");rounds.Add(new Round{reason=c.BattleResult.victoryReason.ToString(),phase=c.Phase.ToString(),winner=c.BattleResult.winnerTeamId,initial0=a.initial,initial1=b.initial,survivors0=a.survivors,survivors1=b.survivors,realSeconds=Time.realtimeSinceStartup-begin,battleSeconds=c.BattleResult.battleSeconds,averageFps=(Time.frameCount-firstFrame)/Mathf.Max(.001f,Time.realtimeSinceStartup-begin)});r.naturalVictoryTest=true;yield return new WaitForSecondsRealtime(.4f);Check(Txt("result-next-note").Contains("已应用编成"),"Result continuation note missing");Shot("natural-result-"+number);yield return new WaitForSecondsRealtime(.4f);checks.Add("Round "+number+" settled by real simulation without manual end, stat changes or telemetry injection");
  }
  IEnumerator Run(){r.stage="load";yield return new WaitForSecondsRealtime(3);var session=WarSandboxSceneSession.Instance;B("home-play").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);B("card-0").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);B("card-0-enter").onClick.Invoke();float deadline=Time.realtimeSinceStartup+120;while(session.IsLoading&&Time.realtimeSinceStartup<deadline)yield return null;Check(session.State==WarSandboxEntryState.Battle,"Battle load failed: "+session.Error);yield return new WaitForSecondsRealtime(1);c=session.Controller;d=c.GetComponent<WarSandboxRuntimeDeployment>();Check(BattleResult27.Active(c)&&d.IsEditing&&d.Draft.Count==2,"Not Results27 initial deployment");for(int i=0;i<2;i++){var e=d.Draft[i];e.count=i==0?1100:948;e.center.z+=i==0?18:-18;d.Draft.Set(i,e);}expected=d.Draft.Snapshot();Check(expected.Sum(e=>e.count)==2048&&d.TryValidate(out _),"Invalid modified default-count draft");yield return new WaitForSecondsRealtime(.3f);B("deployment-start").onClick.Invoke();yield return new WaitForSecondsRealtime(.4f);CompareRuntime();yield return WaitForNatural(1);
   r.stage="natural-result-to-edit";B("result-edit").onClick.Invoke();yield return new WaitForSecondsRealtime(.5f);Check(d.IsEditing&&c.Phase==WarSandboxBattlePhase.Setup&&!c.BattleResult.valid&&!c.GetComponent<WarSandboxDeploymentHUD>().Confirming,"Natural result return-to-editor failed");CompareDraft();checks.Add("Natural result returns committed 1100/948 draft, template identity, placement and formation without a redundant end dialog");Shot("natural-restored-draft");yield return new WaitForSecondsRealtime(.4f);B("deployment-start").onClick.Invoke();yield return new WaitForSecondsRealtime(.4f);CompareRuntime();yield return WaitForNatural(2);
   r.stage="natural-result-restart";B("result-restart").onClick.Invoke();yield return new WaitForSecondsRealtime(.4f);Check(c.Phase==WarSandboxBattlePhase.Running&&!c.BattleResult.valid&&!d.IsEditing,"Natural result restart failed");CompareRuntime();Check(Mathf.Abs(c.SimulationSpeed-1)<.001f&&c.GetMoveRoutePointCount(0)==0&&c.GetMoveRoutePointCount(1)==0,"Restart retained speed/routes");Check(!c.GetComponent<CommandFeedback25>().HasTarget&&GameObject.Find("result-card")==null,"Stale result marker");checks.Add("Natural result restart preserves applied configuration and clears result/routes/speed/transient target");Shot("natural-restarted");yield return new WaitForSecondsRealtime(.4f);r.stage="complete";
  }
 }
}
