// Editor-only supplemental data roundtrip: switched template, local stats, rules, undo and cancel.
using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using UnityEngine;using UnityEngine.UI;using UnityEditor;using UnityEditor.SceneManagement;using static UnityEngine.Object;
namespace MassEngine.Game.Editor {
 [InitializeOnLoad]public static class PlanRoundtrip28ProbeDriver {
  const string Key="PlanRoundtrip28ProbeActive";
  static PlanRoundtrip28ProbeDriver(){EditorApplication.playModeStateChanged+=Changed;}
  public static void Begin(){if(EditorApplication.isPlayingOrWillChangePlaymode)throw new Exception("Refuse existing Play Mode");if(Directory.Exists(PlanRoundtrip28Probe.Output))throw new Exception("Refuse existing evidence");Directory.CreateDirectory(PlanRoundtrip28Probe.Output);SessionState.SetBool(Key,true);EditorBuildSettings.scenes=new[]{"LaunchMenu","Green","Autumn","Winter"}.Select(n=>new EditorBuildSettingsScene("Assets/Game/Experiments/PlanLibrary/"+n+".unity",true)).ToArray();EditorSceneManager.OpenScene("Assets/Game/Experiments/PlanLibrary/LaunchMenu.unity",OpenSceneMode.Single);EditorApplication.EnterPlaymode();}
  static void Changed(PlayModeStateChange state){if(state!=PlayModeStateChange.EnteredPlayMode||!SessionState.GetBool(Key,false))return;SessionState.SetBool(Key,false);new PlanRoundtrip28Probe().StartProbe();}
 }
 public sealed class PlanRoundtrip28Probe {
  public static string Output=>Path.GetFullPath("Logs/Plans28-20261005/data-editor-probe-02");
  [Serializable]class Receipt{public bool passed,editorPlayMode=true,osInputTest=false,isolatedPlanDirectory=true;public string stage,error,originalTemplate,storedTemplate,storedTemplateId;public int first=1100,second=948;public float attackDamage=57,captureSeconds=37;public string[] checks;}
  Receipt r=new Receipt();List<string> checks=new List<string>();Stack<IEnumerator> stack;
  static void Check(bool b,string e){if(!b)throw new Exception(e);}
  static Button B(string n)=>FindObjectsByType<Button>(FindObjectsSortMode.None).Single(b=>b.name==n&&b.gameObject.activeInHierarchy);
  public void StartProbe(){stack=new Stack<IEnumerator>();stack.Push(Run());EditorApplication.update+=Pump;}
  void Pump(){try{if(!EditorApplication.isPlaying)throw new Exception("Play Mode ended early");while(stack.Count>0){if(!stack.Peek().MoveNext()){stack.Pop();continue;}var n=stack.Peek().Current;if(n is IEnumerator nested){stack.Push(nested);continue;}return;}r.passed=true;Finish(0);}catch(Exception e){r.error=e.ToString();Finish(1);}}
  void Finish(int code){EditorApplication.update-=Pump;r.checks=checks.ToArray();File.WriteAllText(Path.Combine(Output,"receipt.json"),JsonUtility.ToJson(r,true));Debug.Log("PLAN_DATA28_RESULT "+JsonUtility.ToJson(r));EditorApplication.Exit(code);}
  IEnumerator Run(){r.stage="load";yield return new WaitForSecondsRealtime(3);var session=WarSandboxSceneSession.Instance;B("home-play").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);B("card-0").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);B("card-0-enter").onClick.Invoke();float deadline=Time.realtimeSinceStartup+120;while(session.IsLoading&&Time.realtimeSinceStartup<deadline)yield return null;Check(session.State==WarSandboxEntryState.Battle,"Load failed: "+session.Error);yield return new WaitForSecondsRealtime(1);var c=session.Controller;var d=c.GetComponent<WarSandboxRuntimeDeployment>();var state=PlanState28.For(c);Check(d.IsEditing&&state!=null,"Not Plans28 draft");d.PlanStore=new WarSandboxLocalPlanStore(Path.Combine(Output,"isolated-plans"));var original=d.Draft[0].template;var alternate=d.ChoiceTemplates.First(t=>t!=original&&t!=d.Draft[1].template);r.originalTemplate=original.name;r.storedTemplate=alternate.name;Check(d.battlefieldCatalog.TryGetTemplateId(alternate,out r.storedTemplateId,out _),"Alternate lacks stable ID");
   r.stage="switched-template-save";Check(d.SelectTemplate(0,alternate),"Cannot switch template");for(int i=0;i<2;i++){var e=d.Draft[i];e.count=i==0?1100:948;e.center.z=i==0?18:-18;e.aspect=i==0?1.2f:e.aspect;d.Draft.Set(i,e);}var rules=d.Draft.Rules;rules.controlPointCaptureSeconds=37;d.Draft.Replace(d.Draft.Snapshot(),rules,d.Draft.Stats);Check(d.Draft.SetStat(alternate,WarSandboxUnitStat.AttackDamage,57),"Local stat unsupported");Check(d.TryValidate(out var error),error);yield return new WaitForSecondsRealtime(.3f);Check(state.NeedsLeaveWarning&&!state.CurrentStored,"Switched draft not dirty");Check(d.TrySavePlan("DATA28","Isolated alternate template",false,out error),error);string saved=state.Current;Check(state.CurrentStored&&state.DraftChanged,"Saved draft auto-applied or not clean");var fresh=new WarSandboxLocalPlanStore(d.PlanStore.DirectoryPath);Check(fresh.TryLoad("DATA28",out var disk,out error),error);Check(disk.entries[0].templateId==r.storedTemplateId&&disk.entries[0].count==1100&&disk.entries[1].count==948&&disk.statOverrides!=null&&disk.statOverrides.Length==1,"Disk did not contain switched ID/count/stats");checks.Add("Real file stores alternate stable template ID, 1100/948, positions, aspect, local damage and rules");
   r.stage="semantic-dirty-and-undo";Check(d.Draft.SetStat(alternate,WarSandboxUnitStat.AttackDamage,58),"Stat edit failed");Check(!state.CurrentStored,"Stat-only edit not detected");Check(d.Draft.Undo()&&!d.Draft.TryGetStat(alternate,WarSandboxUnitStat.AttackDamage,out _)&&!state.CurrentStored,"Coalesced stat undo incorrectly marked saved");Check(d.Draft.Redo()&&d.Draft.TryGetStat(alternate,WarSandboxUnitStat.AttackDamage,out var redone)&&redone==58&&!state.CurrentStored,"Coalesced stat redo incorrect");Check(d.Draft.SetStat(alternate,WarSandboxUnitStat.AttackDamage,57)&&state.CurrentStored,"Restoring exact saved stat content did not become clean");rules=d.Draft.Rules;rules.controlPointCaptureSeconds=39;d.Draft.Replace(d.Draft.Snapshot(),rules,d.Draft.Stats);Check(!state.CurrentStored,"Rules-only edit not detected");Check(d.Draft.Undo()&&state.CurrentStored,"Rules undo failed");Check(d.SelectTemplate(0,original)&&!state.CurrentStored,"Template-only edit not detected");checks.Add("Stat/rule/template-only changes are dirty; existing stat coalescing retained, exact saved values and rule Undo regain clean state");
   r.stage="reload-full-content";Check(d.TryLoadPlan("DATA28",out error),error);Check(state.Current==saved&&state.CurrentStored&&d.Draft[0].template==alternate&&d.Draft.TryGetStat(alternate,WarSandboxUnitStat.AttackDamage,out var damage)&&damage==57&&d.Draft.Rules.controlPointCaptureSeconds==37,"Full persisted state did not roundtrip");Check(d.Draft.Undo()&&d.Draft[0].template==original&&!state.CurrentStored,"Load not one undo step");Check(d.Draft.Redo()&&state.Current==saved&&state.CurrentStored,"Redo did not recover saved content");checks.Add("Reload restores full canonical content and actual alternate template; Undo/Redo remains correct");
   r.stage="cancel-unapplied";d.CancelEditing();yield return new WaitForSecondsRealtime(.3f);Check(!state.NeedsLeaveWarning&&!state.CurrentStored&&!d.IsEditing,"Cancel did not restore default committed baseline");Check(File.Exists(Path.Combine(d.PlanStore.DirectoryPath,"DATA28.json")),"Cancel deleted saved plan");Check(d.TryBeginEdit(false,out error)&&d.TryLoadPlan("DATA28",out error),error);Check(state.Current==saved,"Reopen/load lost saved draft");Check(d.TryApply(out error),error);yield return new WaitForSecondsRealtime(.3f);Check(state.CurrentStored&&!state.NeedsLeaveWarning&&state.Applied&&!d.IsEditing,"Applied alternate/stat plan differs from saved original coordinates");checks.Add("Cancel before Apply restores initial default but leaves file; later load+apply matches saved signature");
   r.stage="cancel-applied-edit";Check(d.TryBeginEdit(false,out error),error);var changed=d.Draft[0];changed.count=1090;d.Draft.Set(0,changed);Check(!state.CurrentStored,"Second draft edit not dirty");d.CancelEditing();yield return new WaitForSecondsRealtime(.3f);Check(state.CurrentStored&&!state.NeedsLeaveWarning&&state.Current==saved,"Cancel did not restore previously applied saved configuration");checks.Add("Cancel after prior saved Apply restores committed saved configuration without false dirtiness");r.stage="complete";
  }
 }
}
