using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.SceneManagement;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEditor.Build.Reporting;
using Object=UnityEngine.Object;
namespace MassEngine.Game.Editor {
 public static class Scene18Builder {
  public const string Root="Assets/Game/Experiments/ForestScenery",Source="Assets/Game/Content/Battlefields/FormationSetup",Battle=Root+"/ForestHills.unity",Menu=Root+"/LaunchMenu.unity",Logs="Logs/Scene18-20261004";
  static Dictionary<Material,Material> mats=new Dictionary<Material,Material>();static Dictionary<string,Texture2D> textures=new Dictionary<string,Texture2D>();
  static List<Used> used=new List<Used>();static TerrainSurface surface;static System.Random rng=new System.Random(1804);
  [Serializable]class Used{public string prefab;public int instances;public long trianglesPerInstance;}
  [Serializable]class TextureInfo{public string path;public int width,height;public string format;}
  [Serializable]class Receipt{public bool passed;public int props,renderers,materials,textures,playableWidth=512;public long triangles;public Used[] sources;public TextureInfo[] textureInfo;public bool originalAssetsUntouched=true,collidersAdded=false;}
  static void Require(bool b,string e){if(!b)throw new Exception(e);}
  static T Find<T>(Scene s)where T:Component{foreach(var g in s.GetRootGameObjects()){var t=g.GetComponentInChildren<T>(true);if(t!=null)return t;}throw new Exception("Missing "+typeof(T).Name);}
  static T Clone<T>(T a,string name)where T:Object{var v=Object.Instantiate(a);v.name=name;AssetDatabase.CreateAsset(v,Root+"/"+name+".asset");return v;}
  static float Rand(float a,float b)=>a+(b-a)*(float)rng.NextDouble();
  static Texture2D TextureCopy(Texture t){if(t==null)return null;string path=AssetDatabase.GetAssetPath(t);if(string.IsNullOrEmpty(path)||!path.StartsWith("Assets/"))return null;if(textures.TryGetValue(path,out var known))return known;Require(!string.IsNullOrEmpty(path),"Texture without source");string dest=Root+"/Textures/T"+textures.Count+Path.GetExtension(path);Require(AssetDatabase.CopyAsset(path,dest),"Copy texture "+path);var importer=AssetImporter.GetAtPath(dest) as TextureImporter;Require(importer!=null,"Missing texture importer");importer.maxTextureSize=512;importer.mipmapEnabled=true;importer.isReadable=false;importer.textureCompression=TextureImporterCompression.Compressed;importer.crunchedCompression=false;importer.anisoLevel=2;var platform=importer.GetPlatformTextureSettings("Standalone");platform.overridden=true;platform.maxTextureSize=512;platform.format=TextureImporterFormat.Automatic;platform.textureCompression=TextureImporterCompression.Compressed;importer.SetPlatformTextureSettings(platform);importer.SaveAndReimport();var tex=AssetDatabase.LoadAssetAtPath<Texture2D>(dest);Require(tex.width<=512&&tex.height<=512,"Texture over budget");textures[path]=tex;return tex;}
  static Material MaterialCopy(Material original){Require(original!=null,"Missing source material");if(mats.TryGetValue(original,out var result))return result;result=new Material(Shader.Find("Universal Render Pipeline/Lit"));result.name="18 "+original.name;result.enableInstancing=true;Texture t=original.HasProperty("_BaseMap")?original.GetTexture("_BaseMap"):null;if(t==null&&original.HasProperty("_MainTex"))t=original.GetTexture("_MainTex");if(t==null)t=original.mainTexture;result.SetTexture("_BaseMap",TextureCopy(t));Color c=original.HasProperty("_BaseColor")?original.GetColor("_BaseColor"):original.HasProperty("_Color")?original.GetColor("_Color"):Color.white;result.SetColor("_BaseColor",c);result.SetFloat("_Smoothness",.06f);result.SetFloat("_Metallic",0);bool leaves=(original.name.ToLower().Contains("leave")||original.shader.name.Contains("Foliage"));bool clip=leaves||(original.HasProperty("_AlphaClip")&&original.GetFloat("_AlphaClip")>.5f)||original.IsKeywordEnabled("_ALPHATEST_ON");if(clip){result.SetFloat("_AlphaClip",1);result.SetFloat("_Cutoff",.45f);result.EnableKeyword("_ALPHATEST_ON");result.SetOverrideTag("RenderType","TransparentCutout");result.renderQueue=2450;result.SetFloat("_Cull",0);}AssetDatabase.CreateAsset(result,Root+"/Materials/M"+mats.Count+".mat");mats[original]=result;return result;}
  static GameObject Place(string path,float x,float z,float height,float yaw,Transform parent,bool far=false){
   var prefab=AssetDatabase.LoadAssetAtPath<GameObject>(path);Require(prefab!=null,"Missing "+path);var go=(GameObject)PrefabUtility.InstantiatePrefab(prefab,parent);PrefabUtility.UnpackPrefabInstance(go,PrefabUnpackMode.Completely,InteractionMode.AutomatedAction);go.name="18 "+prefab.name;go.transform.rotation=Quaternion.Euler(0,yaw,0);
   // Keep an actual authored lower LOD, never simultaneously draw all LOD levels.
   foreach(var group in go.GetComponentsInChildren<LODGroup>(true)){var lods=group.GetLODs();int level=Math.Min(far?2:1,lods.Length-1);if(level>=0){var keep=new HashSet<Renderer>(lods[level].renderers.Where(r=>r!=null));foreach(var rr in lods.SelectMany(l=>l.renderers).Where(r=>r!=null).Distinct().ToArray())if(!keep.Contains(rr))Object.DestroyImmediate(rr.gameObject);}if(group!=null)Object.DestroyImmediate(group);}
   foreach(var col in go.GetComponentsInChildren<Collider>(true))Object.DestroyImmediate(col);foreach(var rb in go.GetComponentsInChildren<Rigidbody>(true))Object.DestroyImmediate(rb);foreach(var script in go.GetComponentsInChildren<MonoBehaviour>(true))if(script!=null)Object.DestroyImmediate(script);
   var renderers=go.GetComponentsInChildren<MeshRenderer>(true);Require(renderers.Length>0,"No renderers "+path);foreach(var r in renderers){r.enabled=true;r.gameObject.SetActive(true);}
   long triangles=go.GetComponentsInChildren<MeshFilter>(true).Sum(f=>Scene18AssetAudit.Triangles(f.sharedMesh));Require(triangles<=1000,"Per prop mesh budget exceeded: "+path+" "+triangles);
   Bounds bounds=renderers[0].bounds;foreach(var r in renderers)bounds.Encapsulate(r.bounds);go.transform.localScale*=height/Mathf.Max(.01f,bounds.size.y);bounds=renderers[0].bounds;foreach(var r in renderers)bounds.Encapsulate(r.bounds);float y=TerrainScaleBounds.BackdropHeight(surface,x,z);go.transform.position+=new Vector3(x,y,z)-new Vector3(bounds.center.x,bounds.min.y,bounds.center.z);
   bounds=renderers[0].bounds;foreach(var r in renderers){bounds.Encapsulate(r.bounds);r.sharedMaterials=r.sharedMaterials.Select(MaterialCopy).ToArray();r.shadowCastingMode=height>6&&!far?ShadowCastingMode.On:ShadowCastingMode.Off;r.receiveShadows=true;r.lightProbeUsage=LightProbeUsage.Off;r.reflectionProbeUsage=ReflectionProbeUsage.Off;GameObjectUtility.SetStaticEditorFlags(r.gameObject,StaticEditorFlags.BatchingStatic);}
   Require(!(bounds.min.x<242&&bounds.max.x> -242&&bounds.min.z<220&&bounds.max.z> -220),"Decoration intersects playable area: "+path);
   var cull=go.AddComponent<LODGroup>();cull.SetLODs(new[]{new LOD(height<3?.012f:.006f,renderers)});cull.RecalculateBounds();var u=used.FirstOrDefault(v=>v.prefab==path&&v.trianglesPerInstance==triangles);if(u==null){u=new Used{prefab=path,trianglesPerInstance=triangles};used.Add(u);}u.instances++;return go;
  }
  static string SC(string tail)=>"Assets/ThirdParty/Supercyan Free Forest Sample/Prefabs/Mobile/"+tail+".prefab";
  static string PT(string tail)=>"Assets/ThirdParty/Polytope Studio/Lowpoly_Environments/Prefabs/"+tail+".prefab";
  static string PP(string tail)=>"Assets/ThirdParty/Pure Poly/Free Low Poly Nature Pack/Prefabs/"+tail+".prefab";
  public static void Prepare(){
   Require(!Directory.Exists(Root),"Refuse overwrite 18");Require(!EditorApplication.isPlaying,"Play mode");Directory.CreateDirectory(Root+"/Textures");Directory.CreateDirectory(Root+"/Materials");AssetDatabase.Refresh();mats.Clear();textures.Clear();used.Clear();rng=new System.Random(1804);Require(AssetDatabase.CopyAsset(Source+"/ForestHills.unity",Battle),"Copy battle");var previous=SceneManager.GetActiveScene();Scene scene=default;
   try{scene=EditorSceneManager.OpenScene(Battle,OpenSceneMode.Additive);SceneManager.SetActiveScene(scene);var manager=Find<MassEngineManager>(scene);var deployment=Find<WarSandboxRuntimeDeployment>(scene);Require(manager.TryGetTerrainContext(out surface,out _,out var error),error);Require(surface.Size==new Vector2(512,512),"Map size changed");
    var catalog=Clone(deployment.battlefieldCatalog,"Catalog");deployment.battlefieldCatalog=catalog;foreach(var e in catalog.entries){e.id="forest-scenery18";e.scenePath=Battle;e.displayName="林间旷野 · 轻量景观";e.description="疏林 / 岩群 / 林缘小景 · 512地图\n默认2048人，保留紧密阵型试验。";e.briefing="低面数树木与分组岩石，保留开阔主战场；装饰仅在外围禁行带和视觉背景。\n贴图采用独立512副本，原资源不改；并非高密度森林，也未扩大地图。\n十万人仍是高负载试验，不保证流畅。";}catalog.defaultEntryId="forest-scenery18";EditorUtility.SetDirty(catalog);
    foreach(var g in scene.GetRootGameObjects())foreach(var t in g.GetComponentsInChildren<Transform>(true).ToArray())if(t!=null&&(t.name=="Kenney CC0 - Scenery inside authored exclusion zones"||t.name=="Visual Only Distant Treeline"))Object.DestroyImmediate(t.gameObject);
    var scenery=new GameObject("18 Lightweight Store Scenery - outside navigation");SceneManager.MoveGameObjectToScene(scenery,scene);var near=new GameObject("Authored grove islands");near.transform.SetParent(scenery.transform);var distant=new GameObject("Sparse distant silhouettes");distant.transform.SetParent(scenery.transform);
    string fir=SC("Tree/Fir/Mobile_forestpack_tree_fir_tall"),leaf=SC("Tree/Leaf/Normal/Mobile_forestpack_tree_1_leaf_1"),pine=PT("Trees/PT_Pine_Tree_03_green"),shrub=PT("Shrubs/PT_Generic_Shrub_01_green"),rock=PP("PP_Rock_Moss_Grown_11"),stone=SC("Stone/Mobile_forestpack_stone_large_1"),grass=PT("Plants/PT_Grass_02"),flower=PT("Flowers/PT_Poppy_02");
    var centers=new List<Vector2>();foreach(float x in new[]{-205f,-112f,6f,126f,212f}){centers.Add(new Vector2(x,255));centers.Add(new Vector2(x+8,-257));}foreach(float z in new[]{-138f,35f,155f}){centers.Add(new Vector2(-278,z));centers.Add(new Vector2(280,z+10));}
    for(int c=0;c<centers.Count;c++){var center=centers[c];var group=new GameObject("Grove "+c);group.transform.SetParent(near.transform);int count=c%3==0?5:7;for(int k=0;k<count;k++){float angle=k*2.39996f+c*.3f,radius=5+3.8f*Mathf.Sqrt(k);float x=center.x+Mathf.Cos(angle)*radius,z=center.y+Mathf.Sin(angle)*radius;Place(k%3==0?pine:k%3==1?leaf:fir,x,z,Rand(12,19),Rand(0,360),group.transform);}
     for(int k=0;k<4;k++){float x=center.x+Rand(-15,15),z=center.y+Rand(-12,12);Place(k%2==0?rock:stone,x,z,Rand(1.8f,4.2f),Rand(0,360),group.transform);}
     for(int k=0;k<6;k++)Place(k%3==0?shrub:k%3==1?grass:flower,center.x+Rand(-17,17),center.y+Rand(-12,12),k%3==0?Rand(1.2f,2.2f):Rand(.7f,1.4f),Rand(0,360),group.transform);
    }
    for(int k=0;k<36;k++){float angle=(k+.4f)*Mathf.PI*2/36;float radius=Rand(355,455);Place(pine,Mathf.Cos(angle)*radius,Mathf.Sin(angle)*radius,Rand(18,27),Rand(0,360),distant.transform,true);}
    // Small trail-side landmarks outside the legal deployment rectangle, no fake walkable bridge.
    Place(SC("Sign/Mobile_forestpack_roadSign_westEast_1"),-251,8,3.8f,90,near.transform);Place(SC("Tree/Treestump/Mobile_forestpack_tree_stump_1"),252,-32,2.6f,35,near.transform);Place(PT("Trees/PT_Fruit_Tree_01_logs"),253,-38,2.2f,80,near.transform);
    EditorUtility.SetDirty(deployment);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();var rs=scenery.GetComponentsInChildren<MeshRenderer>(true);var report=new Receipt{passed=true,props=used.Sum(u=>u.instances),renderers=rs.Length,materials=mats.Count,textures=textures.Count,triangles=used.Sum(u=>u.instances*u.trianglesPerInstance),sources=used.ToArray(),textureInfo=textures.Values.Select(t=>new TextureInfo{path=AssetDatabase.GetAssetPath(t),width=t.width,height=t.height,format=t.format.ToString()}).ToArray()};Require(report.triangles<180000,"Scenery triangle budget");File.WriteAllText(Logs+"/prepare.json",JsonUtility.ToJson(report,true));
   }finally{if(scene.IsValid()&&scene.isLoaded)EditorSceneManager.CloseScene(scene,true);if(previous.IsValid()&&previous.isLoaded)SceneManager.SetActiveScene(previous);}
   Require(AssetDatabase.CopyAsset(Source+"/LaunchMenu.unity",Menu),"Copy menu");var menu=EditorSceneManager.OpenScene(Menu,OpenSceneMode.Additive);try{Find<WarSandboxSceneSession>(menu).catalog=AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Root+"/Catalog.asset");EditorSceneManager.SaveScene(menu);}finally{EditorSceneManager.CloseScene(menu,true);}AssetDatabase.SaveAssets();Debug.Log("SCENE18_PREPARED");
  }
  [Serializable]class BuildResultRow{public bool passed;public string buildGuid;public int errors,warnings;}
  public static void Build(){string output="Builds/Scenery-20261004-18";Require(!Directory.Exists(output),"Refuse overwrite build18");Require(File.Exists(Logs+"/Prepare-complete.json"),"Prepare not complete");Directory.CreateDirectory(output);var r=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{Menu,Battle},locationPathName=output+"/WarSandbox.exe",target=BuildTarget.StandaloneWindows64,options=BuildOptions.Development});File.WriteAllText(Logs+"/build.json",JsonUtility.ToJson(new BuildResultRow{passed=r.summary.result==BuildResult.Succeeded,buildGuid=r.summary.guid.ToString(),errors=(int)r.summary.totalErrors,warnings=(int)r.summary.totalWarnings},true));Require(r.summary.result==BuildResult.Succeeded,"Build failed");File.WriteAllText(output+"/Start-Terrain.cmd","@echo off\r\ncd /d \"%~dp0\"\r\nstart \"\" \"WarSandbox.exe\" -screen-fullscreen 1 -window-mode exclusive -screen-width 1920 -screen-height 1080\r\n");}
 }
}
