using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.SceneManagement;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEditor.Build.Reporting;
using Object=UnityEngine.Object;
namespace MassEngine.Game.Editor {
 public static class Seasons22Builder {
  public const string Root="Assets/Game/Content/Battlefields/SeasonalWoodland",Source="Assets/Game/Content/Battlefields/WoodlandDetail",Logs="Logs/Seasons22-20261005",Menu=Root+"/LaunchMenu.unity";
  static readonly string[] Names={"Green","Autumn","Winter"};
  static readonly string[] Titles={"翠绿林地 · 葱郁盛夏","金秋林地 · 暖叶古道","薄雪林地 · 冬日松林"};
  static readonly Vector4[] Haze={new Vector4(.38f,.57f,.62f,1),new Vector4(.52f,.46f,.34f,1),new Vector4(.49f,.61f,.69f,1)};
  static void Check(bool v,string s){if(!v)throw new Exception(s);}
  static T Find<T>(Scene s)where T:Component{foreach(var g in s.GetRootGameObjects()){var v=g.GetComponentInChildren<T>(true);if(v!=null)return v;}throw new Exception("Missing "+typeof(T).Name);}
  static bool Clear(Bounds b)=>!(b.min.x<242&&b.max.x> -242&&b.min.z<220&&b.max.z> -220);
  static int Kind(Renderer r,Transform root){string n="";for(var t=r.transform;t!=null&&t!=root;t=t.parent)n+=t.name.ToLowerInvariant()+" ";if(n.Contains("mountain"))return 3;if(n.Contains("stone")||n.Contains("rock"))return 2;if(n.Contains("stump")||n.Contains("logs")||n.Contains("fence")||n.Contains("sign"))return 0;return n.Contains("leaf")||n.Contains("pine")||n.Contains("fir")||n.Contains("grass")||n.Contains("shrub")||n.Contains("poppy")||n.Contains("mushroom")?1:0;}
  [Serializable]class SeasonRow{public string id,scene;public int props,renderers,materials,textures;public long triangles;public bool navigationUnchanged,groundMeshUnchanged,backdropMeshUnchanged,noNewColliders,centralRegionClear;}
  [Serializable]class Receipt{public bool passed;public SeasonRow[] seasons;public int playableWidth=512,normalTextureCap=512,mainGroundCap=1024;}
  public static void Prepare(){Check(!Directory.Exists(Root),"Refuse existing Seasons22");Directory.CreateDirectory(Root);Directory.CreateDirectory(Logs);AssetDatabase.Refresh();ShaderUtil.allowAsyncCompilation=false;
   var catalog=Object.Instantiate(AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Source+"/Catalog.asset"));var basis=catalog.entries[0];catalog.entries=Names.Select((n,i)=>{var e=basis.CopyIdentity();e.id="forest-"+n.ToLowerInvariant()+"22";e.scenePath=Root+"/"+n+".unity";e.displayName=Titles[i];e.hiddenFromSelection=false;e.contentVersion=1;e.description=new[]{"沿用认可的21版丰茂绿林\n翠绿草地与清爽远山，默认2048人。","金黄与铜红树叶、枯草及暖色远山\n同一512地图，默认2048人。","薄雪覆盖树冠与地表，保留可辨土路\n仅视觉季节，不改变移动和导航。"}[i];e.briefing="21版树林风格的季节变体："+Titles[i]+"。\n地图布局、中央布阵区、导航及角色尺寸完全相同，季节仅影响景观。\n普通景观贴图512，主草地1024；默认2048人，高人数仍不是流畅性保证。";return e;}).ToArray();catalog.defaultEntryId=catalog.entries[0].id;AssetDatabase.CreateAsset(catalog,Root+"/Catalog.asset");AssetDatabase.SaveAssets();var rows=new List<SeasonRow>();
   for(int season=0;season<3;season++){string dir=Root+"/"+Names[season];Directory.CreateDirectory(dir);AssetDatabase.Refresh();catalog=AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Root+"/Catalog.asset");string path=catalog.entries[season].scenePath;Check(AssetDatabase.CopyAsset(Source+"/ForestHills.unity",path),"Scene copy");var scene=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);catalog=AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Root+"/Catalog.asset");var manager=Find<MassEngineManager>(scene);Check(manager.TryGetTerrainContext(out var surface,out _,out var error),error);Check(surface.Size==new Vector2(512,512),"Map size");var surfaceAsset=manager.terrainSurfaceAsset;
    var d=Find<WarSandboxRuntimeDeployment>(scene);d.battlefieldCatalog=catalog;EditorUtility.SetDirty(d);var root=GameObject.Find("21 Artful Woodland - visual only outside navigation");Check(root!=null,"Missing source trees");root.name="22 Seasonal Woodland - visual only outside navigation";var ground=GameObject.Find("Plan B - Shared Render And Navigation Surface");var backdrop=GameObject.Find("Visual Only Backdrop - No navigation or colliders");var groundMesh=ground.GetComponent<MeshFilter>().sharedMesh;var backMesh=backdrop.GetComponent<MeshFilter>().sharedMesh;
    var material=new Material(ground.GetComponent<Renderer>().sharedMaterial);material.name=Names[season]+" Ground";material.shader=Shader.Find("MassEngine/Seasonal Ground 22");Check(material.shader!=null,"Ground shader");material.SetFloat("_Season",season);material.SetVector("_HazeColor",Haze[season]);AssetDatabase.CreateAsset(material,dir+"/Ground.mat");ground.GetComponent<Renderer>().sharedMaterial=material;backdrop.GetComponent<Renderer>().sharedMaterial=material;
    var cache=new Dictionary<string,Material>();foreach(var r in root.GetComponentsInChildren<Renderer>()){int kind=Kind(r,root.transform);int palette=kind==1&&Mathf.PerlinNoise(r.bounds.center.x*.017f+8,r.bounds.center.z*.017f+23)>.51f?1:0;var originals=r.sharedMaterials;var materials=new Material[originals.Length];for(int j=0;j<originals.Length;j++){var original=originals[j];Check(original!=null,"Missing scenery material");string key=original.GetInstanceID()+":"+(season==0?0:kind)+":"+(season==1?palette:0);if(!cache.TryGetValue(key,out var m)){m=new Material(original);m.name=Names[season]+" "+original.name;if(season>0){bool far=original.shader.name.Contains("Distant Foliage");m.shader=Shader.Find("MassEngine/Seasonal Props 22");m.SetFloat("_Season",season);m.SetFloat("_Kind",kind);m.SetFloat("_Palette",palette*.78f);m.SetFloat("_Far",far?1:0);m.SetVector("_HazeColor",Haze[season]);m.enableInstancing=true;}AssetDatabase.CreateAsset(m,dir+"/Material"+cache.Count+".mat");cache.Add(key,m);}materials[j]=m;}r.sharedMaterials=materials;Check(Clear(r.bounds),"Central region intruded");}
    var camera=Camera.main;if(season>0){camera.clearFlags=CameraClearFlags.SolidColor;camera.backgroundColor=new Color(Haze[season].x,Haze[season].y,Haze[season].z,1).gamma;}
    var used=cache.Values.Concat(new[]{material}).ToArray();var tex=used.SelectMany(m=>m.GetTexturePropertyNames().Select(p=>m.GetTexture(p))).OfType<Texture2D>().Distinct().ToArray();foreach(var t in tex){string tp=AssetDatabase.GetAssetPath(t);int cap=tp.EndsWith("/Ground-Grass.png")?1024:512;Check(t.width<=cap&&t.height<=cap,"Texture exceeds cap: "+tp);}
    Check(manager.terrainSurfaceAsset==surfaceAsset&&ground.GetComponent<MeshFilter>().sharedMesh==groundMesh&&ground.GetComponent<MeshCollider>().sharedMesh==groundMesh&&backdrop.GetComponent<MeshFilter>().sharedMesh==backMesh,"Gameplay geometry altered");Check(root.GetComponentsInChildren<Collider>(true).Length==0,"New collision");ActorMaterialBuildGuard.RequireValid(scene);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();Capture(camera,dir+"/Preview.png",Logs+"/editor-"+Names[season].ToLowerInvariant()+".png");catalog=AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Root+"/Catalog.asset");catalog.entries[season].preview=AssetDatabase.LoadAssetAtPath<Texture2D>(dir+"/Preview.png");EditorUtility.SetDirty(catalog);AssetDatabase.SaveAssets();
    rows.Add(new SeasonRow{id=catalog.entries[season].id,scene=path,props=root.transform.Cast<Transform>().Sum(g=>g.childCount),renderers=root.GetComponentsInChildren<Renderer>().Length,materials=used.Length,textures=tex.Length,triangles=root.GetComponentsInChildren<MeshFilter>().Sum(f=>Scene18AssetAudit.Triangles(f.sharedMesh)),navigationUnchanged=true,groundMeshUnchanged=true,backdropMeshUnchanged=true,noNewColliders=true,centralRegionClear=true});
   }
   Check(!ShaderUtil.ShaderHasError(Shader.Find("MassEngine/Seasonal Props 22"))&&!ShaderUtil.ShaderHasError(Shader.Find("MassEngine/Seasonal Ground 22")),"New shader compile errors");Check(catalog.TryValidate(p=>catalog.entries.Any(e=>e.scenePath==p),out var catalogError),catalogError);Check(AssetDatabase.CopyAsset(Source+"/LaunchMenu.unity",Menu),"Menu copy");var menu=EditorSceneManager.OpenScene(Menu,OpenSceneMode.Single);catalog=AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Root+"/Catalog.asset");var session=Find<WarSandboxSceneSession>(menu);session.catalog=catalog;EditorUtility.SetDirty(session);ActorMaterialBuildGuard.RequireValid(menu);EditorSceneManager.SaveScene(menu);AssetDatabase.SaveAssets();File.WriteAllText(Logs+"/prepare.json",JsonUtility.ToJson(new Receipt{passed=true,seasons=rows.ToArray()},true));
  }
  static void Capture(Camera c,string asset,string file){var rt=new RenderTexture(1280,720,24);var tex=new Texture2D(1280,720,TextureFormat.RGB24,false);var old=c.targetTexture;var active=RenderTexture.active;try{c.targetTexture=rt;c.Render();RenderTexture.active=rt;tex.ReadPixels(new Rect(0,0,1280,720),0,0);tex.Apply();var png=tex.EncodeToPNG();if(asset!=null)File.WriteAllBytes(asset,png);File.WriteAllBytes(file,png);}finally{c.targetTexture=old;RenderTexture.active=active;rt.Release();Object.DestroyImmediate(rt);Object.DestroyImmediate(tex);}if(asset==null)return;AssetDatabase.ImportAsset(asset);var i=(TextureImporter)AssetImporter.GetAtPath(asset);i.maxTextureSize=512;i.SaveAndReimport();}
  public static void Review(){ShaderUtil.allowAsyncCompilation=false;for(int k=0;k<3;k++){var scene=EditorSceneManager.OpenScene(Root+"/"+Names[k]+".unity",OpenSceneMode.Single);var c=Camera.main;Capture(c,Root+"/"+Names[k]+"/Preview.png",Logs+"/editor-"+Names[k].ToLowerInvariant()+".png");var catalog=AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Root+"/Catalog.asset");catalog.entries[k].preview=AssetDatabase.LoadAssetAtPath<Texture2D>(Root+"/"+Names[k]+"/Preview.png");EditorUtility.SetDirty(catalog);AssetDatabase.SaveAssets();c.transform.position=new Vector3(-276,19,-9);c.transform.LookAt(new Vector3(-307,9,29));Capture(c,null,Logs+"/editor-detail-"+Names[k].ToLowerInvariant()+".png");}Check(!ShaderUtil.ShaderHasError(Shader.Find("MassEngine/Seasonal Props 22"))&&!ShaderUtil.ShaderHasError(Shader.Find("MassEngine/Seasonal Ground 22")),"Shader errors");File.WriteAllText(Logs+"/visual-refine.json","{\"passed\":true,\"snowStripesRemoved\":true,\"snowGroundSoftened\":true}");}
  [Serializable]class BuildRow{public bool passed;public string buildGuid;public int errors,warnings;}
  public static void Build(){string dir="Builds/SeasonalWoodland-20261005-22";Check(!Directory.Exists(dir),"Refuse overwrite build");Directory.CreateDirectory(dir);var r=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{Menu}.Concat(Names.Select(n=>Root+"/"+n+".unity")).ToArray(),locationPathName=dir+"/WarSandbox.exe",target=BuildTarget.StandaloneWindows64,options=BuildOptions.Development});File.WriteAllText(Logs+"/build.json",JsonUtility.ToJson(new BuildRow{passed=r.summary.result==BuildResult.Succeeded,buildGuid=r.summary.guid.ToString(),errors=(int)r.summary.totalErrors,warnings=(int)r.summary.totalWarnings},true));Check(r.summary.result==BuildResult.Succeeded,"Build failed");File.WriteAllText(dir+"/Start-Terrain.cmd","@echo off\r\ncd /d \"%~dp0\"\r\nstart \"\" \"WarSandbox.exe\" -screen-fullscreen 1 -window-mode exclusive -screen-width 1920 -screen-height 1080\r\n");}
 }
}
