using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.SceneManagement;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEditor.Build.Reporting;
using Object=UnityEngine.Object;
namespace MassEngine.Game.Editor {
 public static class Season22Builder {
  const string Root="Assets/Game/Experiments/SeasonPrototype",Source="Assets/Game/Content/Battlefields/WoodlandDetail",Logs="Logs/Season22-20261005";
  static readonly string[] Names={"Summer","Autumn","Winter"},Titles={"夏日绿林","金色秋林","薄雪冬林"};
  static readonly Color[] Haze={new Color(.38f,.57f,.62f,1),new Color(.56f,.52f,.42f,1),new Color(.49f,.60f,.68f,1)};
  static Dictionary<string,Material> materials=new Dictionary<string,Material>();
  static Dictionary<string,Texture2D> textures=new Dictionary<string,Texture2D>();
  static void Require(bool b,string e){if(!b)throw new Exception(e);}
  static T Find<T>(Scene s)where T:Component{foreach(var g in s.GetRootGameObjects()){var t=g.GetComponentInChildren<T>(true);if(t!=null)return t;}throw new Exception("Missing "+typeof(T).Name);}
  static string Battle(int season)=>Root+"/"+Names[season]+".unity";
  static int Kind(Renderer r){string s=r.transform.name;var p=r.transform.parent;while(p!=null){s+=" "+p.name;p=p.parent;}s=s.ToLowerInvariant();if(s.Contains("mountain"))return 3;if(s.Contains("rock")||s.Contains("stone"))return 3;if(s.Contains("asymmetric forest"))return 1;if(s.Contains("grass")||s.Contains("shrub")||s.Contains("poppy")||s.Contains("mushroom"))return 2;return 0;}
  static Texture2D ColorTexture(Texture2D src,int season,int kind){
   if(season==0||kind==0||(season==1&&kind==3))return src;string key=AssetDatabase.GetAssetPath(src)+":"+season+":"+kind;if(textures.TryGetValue(key,out var known))return known;
   Require(src.width<=512&&src.height<=512,"Scenery color texture above 512: "+src.name);
   var rt=RenderTexture.GetTemporary(src.width,src.height,0,RenderTextureFormat.ARGB32,RenderTextureReadWrite.sRGB);var previous=RenderTexture.active;var image=new Texture2D(src.width,src.height,TextureFormat.RGBA32,false,true);
   try{Graphics.Blit(src,rt);RenderTexture.active=rt;image.ReadPixels(new Rect(0,0,src.width,src.height),0,0);image.Apply();var pixels=image.GetPixels();for(int i=0;i<pixels.Length;i++){var c=pixels[i];Color.RGBToHSV(c,out float h,out float sat,out float value);float green=Mathf.SmoothStep(0,1,Mathf.InverseLerp(.16f,.24f,h))*(1-Mathf.SmoothStep(0,1,Mathf.InverseLerp(.50f,.61f,h)))*Mathf.SmoothStep(0,1,Mathf.InverseLerp(.10f,.35f,sat));Color target=c;
    if(season==1&&kind!=3){float hue=Mathf.Lerp(.115f,.045f,Mathf.InverseLerp(.22f,.53f,h));target=Color.Lerp(c,Color.HSVToRGB(hue,Mathf.Lerp(.58f,.86f,sat),Mathf.Clamp01(value*.96f+.07f)),green*.96f);}
    if(season==2){if(kind==1)target=Color.Lerp(c,Color.Lerp(new Color(.25f,.35f,.34f),new Color(.77f,.83f,.82f),Mathf.Clamp01(value*.75f+.12f)),green*.94f);else if(kind==2)target=Color.Lerp(c,Color.HSVToRGB(.13f,.26f,Mathf.Clamp01(value*.72f+.19f)),green*.90f);else if(kind==3){target=Color.Lerp(c,new Color(.75f,.81f,.83f),.17f+green*.47f);}}target.a=c.a;pixels[i]=target;}
    image.SetPixels(pixels);image.Apply();string path=Root+"/"+Names[season]+"/Textures/Color"+textures.Count+".png";File.WriteAllBytes(path,image.EncodeToPNG());AssetDatabase.ImportAsset(path);var imp=(TextureImporter)AssetImporter.GetAtPath(path);imp.maxTextureSize=512;imp.mipmapEnabled=true;imp.sRGBTexture=true;imp.textureCompression=TextureImporterCompression.Compressed;imp.alphaSource=TextureImporterAlphaSource.FromInput;imp.wrapMode=TextureWrapMode.Repeat;imp.SaveAndReimport();known=AssetDatabase.LoadAssetAtPath<Texture2D>(path);textures[key]=known;return known;
   }finally{RenderTexture.active=previous;RenderTexture.ReleaseTemporary(rt);Object.DestroyImmediate(image);}
  }
  static Material MaterialCopy(Material source,int season,int kind){Require(source!=null,"Missing source material");string key=source.GetInstanceID()+":"+season+":"+kind;if(materials.TryGetValue(key,out var m))return m;m=new Material(source);m.name=Names[season]+" "+source.name;
   if(m.shader.name=="MassEngine/Art21 Distant Foliage"){m.shader=Shader.Find("MassEngine/Season22 Distant Foliage");m.SetFloat("_Season",season);m.SetVector("_HazeColor",Haze[season]);}
   if(m.HasProperty("_BaseMap")&&m.GetTexture("_BaseMap") is Texture2D tex)m.SetTexture("_BaseMap",ColorTexture(tex,season,kind));
   m.enableInstancing=true;AssetDatabase.CreateAsset(m,Root+"/"+Names[season]+"/Materials/M"+materials.Count+".mat");materials[key]=m;return m;
  }
  [Serializable]class Variant {public string id,scene;public bool navigationUnchanged,groundMeshUnchanged,backdropUnchanged,noNewColliders,noCentralIntrusion;public int renderers,activeRenderers,disabledWinterFlowers,materials,textures;public long decorationTriangles;}
  [Serializable]class Receipt {public bool passed;public int variants;public Variant[] scenes;}
  static void Capture(Camera c,string path){ShaderUtil.allowAsyncCompilation=false;var rt=new RenderTexture(1280,720,24);var image=new Texture2D(1280,720,TextureFormat.RGB24,false);var old=c.targetTexture;var active=RenderTexture.active;try{c.targetTexture=rt;c.Render();RenderTexture.active=rt;image.ReadPixels(new Rect(0,0,1280,720),0,0);image.Apply();File.WriteAllBytes(path,image.EncodeToPNG());}finally{c.targetTexture=old;RenderTexture.active=active;rt.Release();Object.DestroyImmediate(rt);Object.DestroyImmediate(image);}}
  public static void RecoverDraft(){Require(!File.Exists(Logs+"/prepare.json")&&!Directory.Exists("Builds/WoodlandSeasons-20261005-22"),"Cannot recover completed candidate");Require(!Directory.Exists(Logs+"/failed-prepare01-assets"),"Recovery already attempted");EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);Directory.Move(Root,Logs+"/failed-prepare01-assets");if(File.Exists(Root+".meta"))File.Move(Root+".meta",Logs+"/failed-prepare01-assets.meta");File.Copy(Logs+"/Prepare.log",Logs+"/failed-prepare01.log",false);AssetDatabase.Refresh();Prepare();}
  public static void Prepare(){
   Require(!Directory.Exists(Root),"Refuse overwrite Season22");Directory.CreateDirectory(Root);Directory.CreateDirectory(Logs);for(int k=0;k<3;k++){Directory.CreateDirectory(Root+"/"+Names[k]+"/Materials");Directory.CreateDirectory(Root+"/"+Names[k]+"/Textures");}AssetDatabase.Refresh();
   var sourceCatalog=AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Source+"/Catalog.asset");Require(sourceCatalog!=null,"Source catalog missing");var catalog=Object.Instantiate(sourceCatalog);catalog.name="22 Woodland Seasons";var original=sourceCatalog.entries.First(e=>e.id=="forest-art21");catalog.entries=new WarSandboxBattlefieldEntry[3];
   for(int k=0;k<3;k++){var e=original.CopyIdentity();e.id="woodland-"+Names[k].ToLowerInvariant()+"22";e.displayName=Titles[k];e.scenePath=Battle(k);e.hiddenFromSelection=false;e.description=new[]{"清绿树冠 · 草甸与林下小景","金黄与铜橙树冠 · 暖色林地","霜色树林 · 薄雪与显露土路"}[k]+"\n沿用21版布局，默认2048人。";e.briefing="21版树林基调的季节变体："+Titles[k]+"。\n保持512地图、中央布阵空间、导航与角色尺寸；季节仅改变景观外观，无气候伤害或移动惩罚。\n普通景观贴图512，主草地1024；高人数仍仅为压力试验。";catalog.entries[k]=e;}catalog.defaultEntryId=catalog.entries[0].id;AssetDatabase.CreateAsset(catalog,Root+"/Catalog.asset");
   var reports=new List<Variant>();
   for(int k=0;k<3;k++){
    Require(AssetDatabase.CopyAsset(Source+"/ForestHills.unity",Battle(k)),"Copy scene");var scene=EditorSceneManager.OpenScene(Battle(k),OpenSceneMode.Single);catalog=AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Root+"/Catalog.asset");var manager=Find<MassEngineManager>(scene);Require(manager.TryGetTerrainContext(out var surface,out _,out var error),error);Require(surface.Size==new Vector2(512,512),"Map size changed");var oldSurface=manager.terrainSurfaceAsset;var ground=GameObject.Find("Plan B - Shared Render And Navigation Surface");var backdrop=GameObject.Find("Visual Only Backdrop - No navigation or colliders");var mesh=ground.GetComponent<MeshFilter>().sharedMesh;var back=backdrop.GetComponent<MeshFilter>().sharedMesh;var root=GameObject.Find("21 Artful Woodland - visual only outside navigation");Require(root!=null,"Source art missing");root.name="22 Seasonal Woodland - visual only outside navigation";
    var rs=root.GetComponentsInChildren<Renderer>(true);foreach(var r in rs){int kind=Kind(r);r.sharedMaterials=r.sharedMaterials.Select(m=>MaterialCopy(m,k,kind)).ToArray();}
    int disabled=0;if(k==2)foreach(Transform group in root.transform)foreach(Transform t in group){string n=t.name.ToLowerInvariant();if(n.Contains("poppy")||n.Contains("mushroom")){t.gameObject.SetActive(false);disabled++;}}
    var mat=new Material(ground.GetComponent<Renderer>().sharedMaterial);mat.shader=Shader.Find("MassEngine/Season22 Ground");mat.SetFloat("_Season",k);mat.SetVector("_HazeColor",Haze[k]);AssetDatabase.CreateAsset(mat,Root+"/"+Names[k]+"/Ground.mat");ground.GetComponent<Renderer>().sharedMaterial=mat;backdrop.GetComponent<Renderer>().sharedMaterial=mat;
    Find<WarSandboxRuntimeDeployment>(scene).battlefieldCatalog=catalog;
    if(k==1)Camera.main.backgroundColor=new Color(.76f,.73f,.64f);if(k==2)Camera.main.backgroundColor=new Color(.71f,.79f,.85f);
    Require(manager.terrainSurfaceAsset==oldSurface&&ground.GetComponent<MeshFilter>().sharedMesh==mesh&&backdrop.GetComponent<MeshFilter>().sharedMesh==back,"Geometry altered");Require(root.GetComponentsInChildren<Collider>(true).Length==0,"Unexpected colliders");foreach(var r in rs){var b=r.bounds;Require(!(b.min.x<242&&b.max.x> -242&&b.min.z<220&&b.max.z> -220),"Decoration in protected region");Require(r.sharedMaterials.All(m=>m.shader!=null&&m.shader.isSupported),"Unsupported scenery material");}
    ActorMaterialBuildGuard.RequireValid(scene);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();Capture(Camera.main,Logs+"/"+Names[k]+"-overview.png");File.Copy(Logs+"/"+Names[k]+"-overview.png",Root+"/"+Names[k]+"/Preview.png");AssetDatabase.ImportAsset(Root+"/"+Names[k]+"/Preview.png");var imp=(TextureImporter)AssetImporter.GetAtPath(Root+"/"+Names[k]+"/Preview.png");imp.maxTextureSize=512;imp.textureCompression=TextureImporterCompression.Compressed;imp.SaveAndReimport();catalog=AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Root+"/Catalog.asset");catalog.entries[k].preview=AssetDatabase.LoadAssetAtPath<Texture2D>(Root+"/"+Names[k]+"/Preview.png");EditorUtility.SetDirty(catalog);AssetDatabase.SaveAssets();
    Camera.main.transform.position=new Vector3(-276,19,-9);Camera.main.transform.LookAt(new Vector3(-307,9,29));Capture(Camera.main,Logs+"/"+Names[k]+"-detail.png");
    var allMaterials=rs.SelectMany(r=>r.sharedMaterials).Concat(new[]{mat}).Distinct().ToArray();var allTextures=allMaterials.SelectMany(m=>m.GetTexturePropertyNames().Select(p=>m.GetTexture(p))).OfType<Texture2D>().Distinct().ToArray();Require(allTextures.All(t=>Mathf.Max(t.width,t.height)<=(AssetDatabase.GetAssetPath(t).EndsWith("/Ground-Grass.png")?1024:512)),"Texture budget exceeded");
    reports.Add(new Variant{id=catalog.entries[k].id,scene=Battle(k),navigationUnchanged=true,groundMeshUnchanged=true,backdropUnchanged=true,noNewColliders=true,noCentralIntrusion=true,renderers=rs.Length,activeRenderers=rs.Count(r=>r.gameObject.activeInHierarchy&&r.enabled),disabledWinterFlowers=disabled,materials=allMaterials.Length,textures=allTextures.Length,decorationTriangles=root.GetComponentsInChildren<MeshFilter>(true).Sum(f=>Scene18AssetAudit.Triangles(f.sharedMesh))});
   }
   Require(AssetDatabase.CopyAsset(Source+"/LaunchMenu.unity",Root+"/LaunchMenu.unity"),"Copy menu");var menu=EditorSceneManager.OpenScene(Root+"/LaunchMenu.unity",OpenSceneMode.Single);catalog=AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Root+"/Catalog.asset");Find<WarSandboxSceneSession>(menu).catalog=catalog;Require(catalog.TryValidate(p=>p==Root+"/LaunchMenu.unity"||Names.Any(n=>p==Root+"/"+n+".unity"),out var ce),ce);ActorMaterialBuildGuard.RequireValid(menu);EditorSceneManager.SaveScene(menu);AssetDatabase.SaveAssets();File.WriteAllText(Logs+"/prepare.json",JsonUtility.ToJson(new Receipt{passed=true,variants=3,scenes=reports.ToArray()},true));
  }
  [Serializable]class BuildReceipt{public bool passed;public string buildGuid;public int errors,warnings;}
  public static void Build(){const string dir="Builds/WoodlandSeasons-20261005-22";Require(!Directory.Exists(dir),"Refuse overwrite 22 build");Directory.CreateDirectory(dir);var result=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{Root+"/LaunchMenu.unity",Battle(0),Battle(1),Battle(2)},locationPathName=dir+"/WarSandbox.exe",target=BuildTarget.StandaloneWindows64,options=BuildOptions.Development});File.WriteAllText(Logs+"/build.json",JsonUtility.ToJson(new BuildReceipt{passed=result.summary.result==BuildResult.Succeeded,buildGuid=result.summary.guid.ToString(),errors=(int)result.summary.totalErrors,warnings=(int)result.summary.totalWarnings},true));Require(result.summary.result==BuildResult.Succeeded,"Build failed");File.WriteAllText(dir+"/Start-Terrain.cmd","@echo off\r\ncd /d \"%~dp0\"\r\nstart \"\" \"WarSandbox.exe\" -screen-fullscreen 1 -window-mode exclusive -screen-width 1920 -screen-height 1080\r\n");}
 }
}
