using System;using System.Linq;using System.IO;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;using Object=UnityEngine.Object;using UnityEditor.Build.Reporting;using UnityEngine;
namespace MassEngine.Game.Editor { public static class Seasons22BBuilder {

const string Root="Assets/Game/Content/Battlefields/WinterContrast",Source="Assets/Game/Content/Battlefields/SeasonalWoodland",Logs="Logs/Seasons22B-20261005";
static T Find<T>(Scene s)where T:Component{foreach(var g in s.GetRootGameObjects()){var v=g.GetComponentInChildren<T>(true);if(v!=null)return v;}throw new Exception("Missing "+typeof(T).Name);}
public static void Prepare(){if(Directory.Exists(Root))throw new Exception("Refuse overwrite22B assets");Directory.CreateDirectory(Root);AssetDatabase.Refresh();ShaderUtil.allowAsyncCompilation=false;var c=Object.Instantiate(AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Source+"/Catalog.asset"));string[] names={"Green","Autumn","Winter"};for(int i=0;i<3;i++)c.entries[i].scenePath=Root+"/"+names[i]+".unity";AssetDatabase.CreateAsset(c,Root+"/Catalog.asset");AssetDatabase.SaveAssets();for(int k=0;k<3;k++){string path=Root+"/"+names[k]+".unity";if(!AssetDatabase.CopyAsset(Source+"/"+names[k]+".unity",path))throw new Exception("Scene copy failed");var scene=EditorSceneManager.OpenScene(path,OpenSceneMode.Single);c=AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Root+"/Catalog.asset");var d=Find<WarSandboxRuntimeDeployment>(scene);d.battlefieldCatalog=c;EditorUtility.SetDirty(d);if(k==2){var ground=GameObject.Find("Plan B - Shared Render And Navigation Surface");var mat=new Material(ground.GetComponent<Renderer>().sharedMaterial);mat.shader=Shader.Find("MassEngine/Seasonal Ground 22B");AssetDatabase.CreateAsset(mat,Root+"/WinterGround.mat");ground.GetComponent<Renderer>().sharedMaterial=mat;GameObject.Find("Visual Only Backdrop - No navigation or colliders").GetComponent<Renderer>().sharedMaterial=mat;}
ActorMaterialBuildGuard.RequireValid(scene);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();var camera=Camera.main;Capture(camera,Root+"/"+names[k]+"Preview.png",Logs+"/editor-"+names[k].ToLowerInvariant()+".png");c=AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Root+"/Catalog.asset");c.entries[k].preview=AssetDatabase.LoadAssetAtPath<Texture2D>(Root+"/"+names[k]+"Preview.png");EditorUtility.SetDirty(c);AssetDatabase.SaveAssets();camera.transform.position=new Vector3(-276,19,-9);camera.transform.LookAt(new Vector3(-307,9,29));Capture(camera,null,Logs+"/editor-detail-"+names[k].ToLowerInvariant()+".png");}
if(!AssetDatabase.CopyAsset(Source+"/LaunchMenu.unity",Root+"/LaunchMenu.unity"))throw new Exception("Menu copy failed");var menu=EditorSceneManager.OpenScene(Root+"/LaunchMenu.unity",OpenSceneMode.Single);var session=Find<WarSandboxSceneSession>(menu);session.catalog=AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Root+"/Catalog.asset");EditorUtility.SetDirty(session);ActorMaterialBuildGuard.RequireValid(menu);EditorSceneManager.SaveScene(menu);AssetDatabase.SaveAssets();if(ShaderUtil.ShaderHasError(Shader.Find("MassEngine/Seasonal Ground 22B")))throw new Exception("Winter shader failed");File.WriteAllText(Logs+"/prepare.json","{\"passed\":true,\"clonedScenes\":4,\"sourcePreserved\":true,\"winterPatchContrastReduced\":true,\"sceneRoot\":\"Assets/Game/Content/Battlefields/WinterContrast\"}");}
static void Capture(Camera c,string asset,string path){var rt=new RenderTexture(1280,720,24);var tex=new Texture2D(1280,720,TextureFormat.RGB24,false);var old=c.targetTexture;var active=RenderTexture.active;try{c.targetTexture=rt;c.Render();RenderTexture.active=rt;tex.ReadPixels(new Rect(0,0,1280,720),0,0);tex.Apply();var png=tex.EncodeToPNG();if(asset!=null)File.WriteAllBytes(asset,png);File.WriteAllBytes(path,png);}finally{c.targetTexture=old;RenderTexture.active=active;rt.Release();Object.DestroyImmediate(rt);Object.DestroyImmediate(tex);}if(asset!=null){AssetDatabase.ImportAsset(asset);var imp=(TextureImporter)AssetImporter.GetAtPath(asset);imp.maxTextureSize=512;imp.SaveAndReimport();}}


[Serializable]class SceneAudit{public string scene;public int renderers,materials,textures;public long decorationTriangles;public bool passed;}
[Serializable]class Audits{public bool passed;public SceneAudit[] scenes;}
static void Audit(){string[] names={"Green","Autumn","Winter"};var rows=new System.Collections.Generic.List<SceneAudit>();foreach(var name in names){var scene=EditorSceneManager.OpenScene(Root+"/"+name+".unity",OpenSceneMode.Single);var manager=Find<MassEngineManager>(scene);if(!manager.TryGetTerrainContext(out var surface,out _,out var error)||surface.Size!=new Vector2(512,512))throw new Exception("Terrain: "+error);var g=GameObject.Find("Plan B - Shared Render And Navigation Surface");if(AssetDatabase.GetAssetPath(manager.terrainSurfaceAsset)!="Assets/Game/Content/Battlefields/ForestTerrain/Surface.asset"||AssetDatabase.GetAssetPath(g.GetComponent<MeshFilter>().sharedMesh)!="Assets/Game/Content/Battlefields/ForestTerrain/GroundMesh.asset"||g.GetComponent<MeshCollider>().sharedMesh!=g.GetComponent<MeshFilter>().sharedMesh)throw new Exception("Gameplay geometry changed");if(AssetDatabase.GetAssetPath(GameObject.Find("Visual Only Backdrop - No navigation or colliders").GetComponent<MeshFilter>().sharedMesh)!="Assets/Game/Content/Battlefields/ForestTerrain/Backdrop.asset")throw new Exception("Backdrop changed");var root=GameObject.Find("22 Seasonal Woodland - visual only outside navigation");if(root.GetComponentsInChildren<Collider>(true).Length!=0)throw new Exception("Added scenery collision");var rr=root.GetComponentsInChildren<Renderer>();foreach(var r in rr){var b=r.bounds;if(b.min.x<242&&b.max.x> -242&&b.min.z<220&&b.max.z> -220)throw new Exception("Intruding scenery");}var mats=rr.SelectMany(r=>r.sharedMaterials).Concat(new[]{g.GetComponent<Renderer>().sharedMaterial}).Distinct().ToArray();var textures=mats.SelectMany(m=>m.GetTexturePropertyNames().Select(n=>m.GetTexture(n))).OfType<Texture2D>().Distinct().ToArray();foreach(var t in textures){int cap=AssetDatabase.GetAssetPath(t).EndsWith("/Ground-Grass.png")?1024:512;if(t.width>cap||t.height>cap)throw new Exception("Texture cap exceeded");}long tris=root.GetComponentsInChildren<MeshFilter>().Sum(f=>Scene18AssetAudit.Triangles(f.sharedMesh));if(tris!=331633||rr.Length!=2045)throw new Exception("Unexpected layout change");ActorMaterialBuildGuard.RequireValid(scene);rows.Add(new SceneAudit{scene=scene.path,renderers=rr.Length,materials=mats.Length,textures=textures.Length,decorationTriangles=tris,passed=true});}File.WriteAllText(Logs+"/scene-audit.json",JsonUtility.ToJson(new Audits{passed=true,scenes=rows.ToArray()},true));}

[Serializable]class Receipt {public bool passed;public string buildGuid;public int errors,warnings;}
public static void Build(){Audit();const string dir="Builds/SeasonalWoodland-20261005-22B";if(Directory.Exists(dir))throw new Exception("Refuse overwrite build22B");Directory.CreateDirectory(dir);var r=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{"Assets/Game/Content/Battlefields/WinterContrast/LaunchMenu.unity","Assets/Game/Content/Battlefields/WinterContrast/Green.unity","Assets/Game/Content/Battlefields/WinterContrast/Autumn.unity","Assets/Game/Content/Battlefields/WinterContrast/Winter.unity"},locationPathName=dir+"/WarSandbox.exe",target=BuildTarget.StandaloneWindows64,options=BuildOptions.Development});File.WriteAllText("Logs/Seasons22B-20261005/build.json",JsonUtility.ToJson(new Receipt{passed=r.summary.result==BuildResult.Succeeded,buildGuid=r.summary.guid.ToString(),errors=(int)r.summary.totalErrors,warnings=(int)r.summary.totalWarnings},true));if(r.summary.result!=BuildResult.Succeeded)throw new Exception("Build22B failed");File.WriteAllText(dir+"/Start-Terrain.cmd","@echo off\r\ncd /d \"%~dp0\"\r\nstart \"\" \"WarSandbox.exe\" -screen-fullscreen 1 -window-mode exclusive -screen-width 1920 -screen-height 1080\r\n");}
}}
