using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEditor.Build.Reporting;
using Object=UnityEngine.Object;
namespace MassEngine.Game.Editor {
 public static class TerrainScaleBuilder {
  public const string Root="Assets/Game/Content/Battlefields/ForestTerrain",Battle=Root+"/ForestHills.unity",Menu=Root+"/LaunchMenu.unity",Logs="Logs/TerrainScale-20261004";
  const string Source="Assets/Game/Experiments/TerrainAtmosphere";
  static void Assert(bool b,string e){if(!b)throw new Exception(e);}
  static T Copy<T>(T a,string name) where T:Object {var c=Object.Instantiate(a);c.name=name;AssetDatabase.CreateAsset(c,Root+"/"+name+".asset");return c;}
  static bool Block(float x,float z)=>Mathf.Abs(x)>242||Mathf.Abs(z)>220;
  static Color GroundColor(float x,float z){float px=x*.5f,pz=z*.5f;var c=Color.Lerp(new Color(.34f,.49f,.20f),new Color(.53f,.63f,.29f),Mathf.PerlinNoise(px*.04f+70,pz*.04f+50));float path=Mathf.Abs(pz-8*Mathf.Sin(px/27));float side=Mathf.Abs(pz-(45+4*Mathf.Sin(px/20)));float road=1-Mathf.SmoothStep(0,1,Mathf.InverseLerp(4,8,Mathf.Min(path,side+2)));return Color.Lerp(c,new Color(.67f,.57f,.37f),road);}
  public static void Prepare(){
   Assert(!Directory.Exists(Root),"Refuse overwrite 15");Directory.CreateDirectory(Root);Directory.CreateDirectory(Logs);AssetDatabase.Refresh();
   Assert(AssetDatabase.CopyAsset(Source+"/ForestHills.unity",Battle),"Copy battle");var scene=EditorSceneManager.OpenScene(Battle,OpenSceneMode.Single);
   var m=Object.FindFirstObjectByType<MassEngineManager>();var d=Object.FindFirstObjectByType<WarSandboxRuntimeDeployment>();
   Assert(m.TryGetTerrainContext(out var old,out _,out var error),error);
   const int n=257;var heights=new float[n*n];var blocked=new bool[256*256];
   for(int z=0;z<n;z++)for(int x=0;x<n;x++){float wx=-256+x*2,wz=-256+z*2;old.TrySample(new Vector2(wx*.5f,wz*.5f),out var q);heights[z*n+x]=q.Position.y;if(x<256&&z<256)blocked[z*256+x]=Block(wx+1,wz+1);}
   var a=ScriptableObject.CreateInstance<TerrainSurfaceAsset>();a.Initialize("forest-hills-scale15",1,n,n,new Vector2(-256,-256),new Vector2(512,512),38,heights,blocked);AssetDatabase.CreateAsset(a,Root+"/Surface.asset");Assert(a.TryCreateSurface(out var s,out error),error);
   var ground=GameObject.Find("Plan B - Shared Render And Navigation Surface");var mesh=TerrainPrototype.CreateMesh(s);mesh.colors32=mesh.vertices.Select(v=>(Color32)GroundColor(v.x,v.z)).ToArray();AssetDatabase.CreateAsset(mesh,Root+"/GroundMesh.asset");ground.GetComponent<MeshFilter>().sharedMesh=mesh;ground.GetComponent<MeshCollider>().sharedMesh=mesh;
   var material=Object.Instantiate(ground.GetComponent<Renderer>().sharedMaterial);material.SetFloat("_HazeStart",380);material.SetFloat("_HazeEnd",1080);AssetDatabase.CreateAsset(material,Root+"/Ground.mat");ground.GetComponent<Renderer>().sharedMaterial=material;
   var system=Copy(m.systemConfig,"System");system.simulationConfig=Copy(system.simulationConfig,"Simulation");system.simulationConfig.simulationWorldSize=new Vector2(512,512);system.runtimeFlowConfig=Copy(system.runtimeFlowConfig,"Flow");system.runtimeFlowConfig.flowFieldOrigin=new Vector2(-256,-256);system.runtimeFlowConfig.flowFieldResolution=256;system.runtimeFlowConfig.flowFieldCellSize=2;m.systemConfig=system;m.terrainSurfaceAsset=a;
   var scenario=Copy(m.scenarioConfig,"Scenario");var policy=Copy(d.rosterPolicy,"RosterPolicy");var catalog=Copy(d.battlefieldCatalog,"Catalog");
   scenario.unitTypes=(UnitTypeConfig[])scenario.unitTypes.Clone();policy.templates=(UnitTypeConfig[])policy.templates.Clone();
   for(int i=0;i<scenario.unitTypes.Length;i++){var prior=scenario.unitTypes[i];var u=Copy(prior,"Formation"+i);u.spawnConfig=Copy(prior.spawnConfig,"Spawn"+i);u.spawnConfig.unitCount=1024;u.spawnConfig.spawnCenter=new Vector3(i==0?-128:128,0,0);u.spawnConfig.spawnSize=Vector3.zero;u.spawnConfig.formationDensity=.4f;u.spawnConfig.formationAspect=2.2f;scenario.unitTypes[i]=u;policy.templates=policy.templates.Select(t=>t==prior?u:t).ToArray();foreach(var t in catalog.templates)if(t.config==prior)t.config=u;EditorUtility.SetDirty(u);EditorUtility.SetDirty(u.spawnConfig);}
   policy.maximumUnits=50000;policy.explanation="512×512扩图试装：默认2048人，试验上限合计5万人；保留正常角色体型和原阵列平均密度。此地图尚不能正常布阵双方各十万，人数上限不是性能保证。";
   m.scenarioConfig=scenario;d.rosterPolicy=policy;d.battlefieldCatalog=catalog;
   // Relocate scenery to the authored exclusion strips, never scale tree or rock models.
   foreach(Transform t in GameObject.Find("Kenney CC0 - Scenery inside authored exclusion zones").transform){var rs=t.GetComponentsInChildren<Renderer>();if(rs.Length==0)continue;var b=rs[0].bounds;foreach(var r in rs)b.Encapsulate(r.bounds);var p=t.position;float x=p.x*2;float sign=p.z>=0?1:-1;float z=sign*(234+Mathf.Repeat(Mathf.Abs(p.z)*.63f,12));s.TrySample(new Vector2(Mathf.Clamp(x,-250,250),z),out var q);t.position+=new Vector3(x,q.Position.y,z)-new Vector3(b.center.x,b.min.y,b.center.z);}
   var coords=new List<float>();for(int x=-1408;x<-256;x+=32)coords.Add(x);for(int x=-256;x<=256;x+=2)coords.Add(x);for(int x=288;x<=1408;x+=32)coords.Add(x);int size=coords.Count;
   var vs=new Vector3[size*size];var cs=new Color32[vs.Length];var tris=new List<int>();
   for(int z=0;z<size;z++)for(int x=0;x<size;x++){int i=z*size+x;float wx=coords[x],wz=coords[z];vs[i]=new Vector3(wx,TerrainScaleBounds.BackdropHeight(s,wx,wz),wz);float outside=Mathf.Max(Mathf.Abs(wx),Mathf.Abs(wz))-256;var edge=GroundColor(Mathf.Clamp(wx,-256,256),Mathf.Clamp(wz,-256,256));var far=Color.Lerp(new Color(.27f,.34f,.31f),new Color(.40f,.45f,.37f),Mathf.PerlinNoise(wx*.01f+40,wz*.01f+70));cs[i]=Color.Lerp(edge,far,Mathf.SmoothStep(0,1,Mathf.Clamp01(outside/280)));if(x==size-1||z==size-1)continue;float mx=(wx+coords[x+1])*.5f,mz=(wz+coords[z+1])*.5f;if(Mathf.Abs(mx)<256&&Mathf.Abs(mz)<256)continue;tris.AddRange(new[]{i,i+size+1,i+1,i,i+size,i+size+1});}
   var back=new Mesh{name="512 terrain seamless visual apron",indexFormat=IndexFormat.UInt32};back.vertices=vs;back.colors32=cs;back.triangles=tris.ToArray();back.RecalculateNormals();var normals=back.normals;var gn=mesh.normals;for(int i=0;i<vs.Length;i++)if(Mathf.Abs(vs[i].x)<=256&&Mathf.Abs(vs[i].z)<=256)normals[i]=gn[Mathf.RoundToInt((vs[i].z+256)/2)*257+Mathf.RoundToInt((vs[i].x+256)/2)];back.normals=normals;back.RecalculateBounds();AssetDatabase.CreateAsset(back,Root+"/Backdrop.asset");var backdrop=GameObject.Find("Visual Only Backdrop - No navigation or colliders");backdrop.GetComponent<MeshFilter>().sharedMesh=back;backdrop.GetComponent<Renderer>().sharedMaterial=material;
   var mats=new Dictionary<Material,Material>();foreach(Transform t in GameObject.Find("Visual Only Distant Treeline").transform){var rs=t.GetComponentsInChildren<Renderer>();var b=rs[0].bounds;foreach(var r in rs)b.Encapsulate(r.bounds);float x=b.center.x*2,z=b.center.z*2;t.position+=new Vector3(x,TerrainScaleBounds.BackdropHeight(s,x,z),z)-new Vector3(b.center.x,b.min.y,b.center.z);foreach(var r in rs){var mm=r.sharedMaterials;for(int i=0;i<mm.Length;i++){if(!mats.TryGetValue(mm[i],out var mat)){mat=Object.Instantiate(mm[i]);mat.SetFloat("_HazeStart",380);mat.SetFloat("_HazeEnd",1080);AssetDatabase.CreateAsset(mat,Root+"/DistantTree"+mats.Count+".mat");mats[mm[i]]=mat;}mm[i]=mat;}r.sharedMaterials=mm;}}
   var camera=Camera.main;Object.DestroyImmediate(camera.GetComponent<BattlefieldAtmosphereBounds>());var envelope=camera.gameObject.AddComponent<TerrainScaleBounds>();envelope.manager=m;envelope.cameraController=Object.FindFirstObjectByType<MyCameraManager>();envelope.cameraController.MaxZoomDistance=720;envelope.cameraController.FlyMoveSpeed=65;camera.farClipPlane=3600;camera.transform.position=new Vector3(250,280,-384);camera.transform.LookAt(new Vector3(0,8,0));
   foreach(var e in catalog.entries){e.id="forest-hills-scale15";e.scenePath=Battle;e.terrainId=a.Id;e.terrainVersion=a.Version;e.terrainSurface=a;e.displayName="林地丘陵 · 512扩图";e.description="512×512真实可玩地形 · 开阔布阵区\n默认2048人，试验上限5万人；不是二十万人验收。";e.briefing="两侧开阔布阵，中央保留推进空间；树林和岩群移至外围禁行带。\n角色与树木体型不变，导航精度保持2米。双方各十万在正常密度下仍放不下，需更大地图。";}
   catalog.defaultEntryId="forest-hills-scale15";
   foreach(var obj in new Object[]{m,d,system,system.simulationConfig,system.runtimeFlowConfig,scenario,policy,catalog,envelope,envelope.cameraController})EditorUtility.SetDirty(obj);EditorSceneManager.SaveScene(scene);AssetDatabase.SaveAssets();
   Capture(camera,Logs+"/01-default.png");File.Copy(Logs+"/01-default.png",Root+"/Preview.png");AssetDatabase.ImportAsset(Root+"/Preview.png");catalog.entries[0].preview=AssetDatabase.LoadAssetAtPath<Texture2D>(Root+"/Preview.png");EditorUtility.SetDirty(catalog);AssetDatabase.SaveAssets();
   Assert(AssetDatabase.CopyAsset(Source+"/LaunchMenu.unity",Menu),"Copy menu");var menu=EditorSceneManager.OpenScene(Menu,OpenSceneMode.Single);Object.FindFirstObjectByType<WarSandboxSceneSession>().catalog=AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Root+"/Catalog.asset");EditorSceneManager.SaveScene(menu);
   Audit();
  }
  [Serializable]class Capacity {public string unit;public float radius,priorResolvedDensity;public int targetPerSide=100000,capacityPerSideAtPriorDensity,capacityPerSideAtSquarePacking;public float targetAreaAtPriorDensity;}
  [Serializable]class AuditReceipt {public bool passed;public int playableWidth=512,surfaceVertices=257,flowResolution=256,seamVertices,cameraCases;public float navigationStep=2,deployDepth=212,deployFront=424,centralGap=48;public bool targetFitsWithoutCompaction=false;public Capacity[] capacities;}
  public static void RefineRoads(){
   EditorSceneManager.OpenScene(Battle,OpenSceneMode.Single);
   var ground=AssetDatabase.LoadAssetAtPath<Mesh>(Root+"/GroundMesh.asset");ground.colors32=ground.vertices.Select(v=>(Color32)GroundColor(v.x,v.z)).ToArray();EditorUtility.SetDirty(ground);
   var back=AssetDatabase.LoadAssetAtPath<Mesh>(Root+"/Backdrop.asset");back.colors32=back.vertices.Select(v=>{float outside=Mathf.Max(Mathf.Abs(v.x),Mathf.Abs(v.z))-256;var edge=GroundColor(Mathf.Clamp(v.x,-256,256),Mathf.Clamp(v.z,-256,256));var far=Color.Lerp(new Color(.27f,.34f,.31f),new Color(.40f,.45f,.37f),Mathf.PerlinNoise(v.x*.01f+40,v.z*.01f+70));return (Color32)Color.Lerp(edge,far,Mathf.SmoothStep(0,1,Mathf.Clamp01(outside/280)));}).ToArray();EditorUtility.SetDirty(back);
   Assert(GroundColor(0,0).r>GroundColor(0,0).g,"Road color missing");AssetDatabase.SaveAssets();Capture(Camera.main,Logs+"/01-default.png");File.Copy(Logs+"/01-default.png",Root+"/Preview.png",true);AssetDatabase.ImportAsset(Root+"/Preview.png");Audit();
  }
  public static void Audit(){
   EditorSceneManager.OpenScene(Battle,OpenSceneMode.Single);var m=Object.FindFirstObjectByType<MassEngineManager>();Assert(m.TryGetTerrainContext(out var s,out var nav,out var err),err);Assert(s.Size==new Vector2(512,512),"Wrong terrain size");Assert(m.systemConfig.runtimeFlowConfig.flowFieldResolution==256,"Wrong nav size");Assert(nav.AreConnected(new Vector2(-128,0),new Vector2(128,0)),"Disconnected");
   Assert(nav.IsFootprintWalkable(new Vector2(-130,0),new Vector2(212,424))&&nav.IsFootprintWalkable(new Vector2(130,0),new Vector2(212,424)),"Large deployment clearings blocked");
   var r=new AuditReceipt();var mesh=AssetDatabase.LoadAssetAtPath<Mesh>(Root+"/GroundMesh.asset");var back=AssetDatabase.LoadAssetAtPath<Mesh>(Root+"/Backdrop.asset");var vs=back.vertices;var ns=back.normals;var cs=back.colors32;var gv=mesh.vertices;var gn=mesh.normals;var gc=mesh.colors32;
   for(int i=0;i<vs.Length;i++){var v=vs[i];if(Mathf.Abs(v.x)>256||Mathf.Abs(v.z)>256||(Mathf.Abs(v.x)!=256&&Mathf.Abs(v.z)!=256))continue;int j=Mathf.RoundToInt((v.z+256)/2)*257+Mathf.RoundToInt((v.x+256)/2);Assert(Vector3.Distance(v,gv[j])<.0001f&&Vector3.Distance(ns[i],gn[j])<.0001f&&cs[i].Equals(gc[j]),"Seam mismatch");r.seamVertices++;}Assert(r.seamVertices==1024,"Missing seam");
   var env=Camera.main.GetComponent<TerrainScaleBounds>();for(int i=0;i<24;i++)foreach(float h in new[]{-200f,1800f}){var p=env.Constrain(new Vector3(Mathf.Cos(i*Mathf.PI/12)*2000,h,Mathf.Sin(i*Mathf.PI/12)*2000));Assert((p-env.center).magnitude<=720.01f&&new Vector2(p.x,p.z).magnitude<=480.01f&&p.y<=600.01f,"Camera escape");r.cameraCases++;}
   var prior=AssetDatabase.LoadAssetAtPath<ScenarioConfig>("Assets/Game/Experiments/ForestPrototype/Scenario.asset");r.capacities=prior.unitTypes.Select(u=>new Capacity{unit=u.unitTypeName,radius=u.flockingConfig.agentRadius,priorResolvedDensity=u.spawnConfig.ResolveDensity(),capacityPerSideAtPriorDensity=Mathf.FloorToInt(212*424*u.spawnConfig.ResolveDensity()),capacityPerSideAtSquarePacking=Mathf.FloorToInt(212/(2*u.flockingConfig.agentRadius))*Mathf.FloorToInt(424/(2*u.flockingConfig.agentRadius)),targetAreaAtPriorDensity=100000/u.spawnConfig.ResolveDensity()}).ToArray();
   Assert(r.capacities.All(c=>c.capacityPerSideAtPriorDensity<100000),"Unexpected target capacity; reevaluate");r.passed=true;File.WriteAllText(Logs+"/capacity-and-audit.json",JsonUtility.ToJson(r,true));
  }
  static void Capture(Camera c,string p){ShaderUtil.allowAsyncCompilation=false;var rt=new RenderTexture(1280,720,24);var tex=new Texture2D(1280,720,TextureFormat.RGB24,false);var old=RenderTexture.active;c.targetTexture=rt;c.Render();RenderTexture.active=rt;tex.ReadPixels(new Rect(0,0,1280,720),0,0);tex.Apply();File.WriteAllBytes(p,tex.EncodeToPNG());c.targetTexture=null;RenderTexture.active=old;rt.Release();Object.DestroyImmediate(rt);Object.DestroyImmediate(tex);}
  [Serializable]class BuildReceipt {public bool passed;public string buildGuid;public int errors,warnings;}
  public static void Build(){const string path="Builds/TerrainScale-20261004-16";Assert(!Directory.Exists(path),"Refuse overwrite build 16");Directory.CreateDirectory(path);var r=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{Menu,Battle},locationPathName=path+"/WarSandbox.exe",target=BuildTarget.StandaloneWindows64,options=BuildOptions.Development});File.WriteAllText(Logs+"/build.json",JsonUtility.ToJson(new BuildReceipt{passed=r.summary.result==BuildResult.Succeeded,buildGuid=r.summary.guid.ToString(),errors=(int)r.summary.totalErrors,warnings=(int)r.summary.totalWarnings},true));Assert(r.summary.result==BuildResult.Succeeded,"Build failed");File.WriteAllText(path+"/Start-Terrain.cmd","@echo off\r\ncd /d \"%~dp0\"\r\nstart \"\" \"WarSandbox.exe\" -screen-fullscreen 1 -window-mode exclusive -screen-width 1920 -screen-height 1080\r\n");}
 }
}
