using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Security.Cryptography;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using Object=UnityEngine.Object;
namespace MassEngine.Game.Editor {
 public static class WhiteActorFix19 {
  public const string Logs="Logs/WhiteActorFix-20261004",Source="Assets/Game/Experiments/ForestScenery",Root="Assets/Game/Experiments/MaterialFix",Battle=Root+"/ForestHills.unity",Menu=Root+"/LaunchMenu.unity";
  const string RuntimeAtlas="Assets/Game/RuntimeDependencies/TinyHero/Albedo.png";
  const string Atlas="Assets/ThirdParty/RPG Tiny Hero Duo/Texture/Albedo.png",AtlasGuid="a63884258dc521b4085d9bc96fe60c86";
  static void Require(bool yes,string text){if(!yes)throw new Exception(text);}
  [Serializable]class Row{public string unit,config,render,material,shader,texture;public int lod,width,height;}
  [Serializable]class Inspection{public bool passed,expectedBrokenReference,buildGateRejected;public string[] errors;public Row[] defaultActors;public int catalogUnits;}
  static Row[] ActorRows(Scene scene){var manager=Object.FindFirstObjectByType<MassEngineManager>();var list=new List<Row>();foreach(var u in manager.scenarioConfig.unitTypes){var resolved=ResolvedUnitTypeRuntime.Resolve(u,1.5f);for(int lod=0;lod<3;lod++){var m=resolved.GetMaterial(lod);var t=m!=null&&m.HasProperty("_BaseMap")?m.GetTexture("_BaseMap"):null;list.Add(new Row{unit=u.unitTypeName,config=AssetDatabase.GetAssetPath(u),render=AssetDatabase.GetAssetPath(u.renderConfig),lod=lod,material=AssetDatabase.GetAssetPath(m),shader=m==null?"null":m.shader.name,texture=t==null?"<missing>":AssetDatabase.GetAssetPath(t),width=t==null?0:t.width,height=t==null?0:t.height});}}return list.ToArray();}
  public static void Before(){Directory.CreateDirectory(Logs);Require(!File.Exists(Atlas)&&!File.Exists(Atlas+".meta"),"Expected original missing texture pair for negative control");var scene=EditorSceneManager.OpenScene(Source+"/ForestHills.unity",OpenSceneMode.Single);var errors=ActorMaterialBuildGuard.Inspect(scene);bool caught=false;try{ActorMaterialBuildGuard.RequireValid(scene);}catch(BuildFailedException){caught=true;}var report=new Inspection{passed=errors.Any(e=>e.Contains(AtlasGuid))&&caught,expectedBrokenReference=errors.Any(e=>e.Contains(AtlasGuid)),buildGateRejected=caught,errors=errors.ToArray(),defaultActors=ActorRows(scene),catalogUnits=ActorMaterialBuildGuard.Units(scene).Count};File.WriteAllText(Logs+"/before.json",JsonUtility.ToJson(report,true));Require(report.passed,"The real missing atlas must fail the new build gate");}
  [Serializable]class Tests{public bool passed,missingAssignedTextureRejected,missingNearRejected,missingMidRejected,missingFarRejected,intentionalSolidColorAccepted,actualSceneAccepted;}
  public static void After(){Directory.CreateDirectory(Logs);Require(AssetDatabase.LoadAssetAtPath<Texture2D>(File.Exists(RuntimeAtlas)?RuntimeAtlas:Atlas)!=null,"Required atlas missing");var scene=EditorSceneManager.OpenScene(Source+"/ForestHills.unity",OpenSceneMode.Single);var errors=ActorMaterialBuildGuard.Inspect(scene);var inspection=new Inspection{passed=errors.Count==0,errors=errors.ToArray(),defaultActors=ActorRows(scene),catalogUnits=ActorMaterialBuildGuard.Units(scene).Count};File.WriteAllText(Logs+"/after.json",JsonUtility.ToJson(inspection,true));Require(inspection.passed,string.Join("\n",errors));
   var manager=Object.FindFirstObjectByType<MassEngineManager>();var unit=Object.Instantiate(manager.scenarioConfig.unitTypes[0]);var render=Object.Instantiate(unit.renderConfig);unit.renderConfig=render;var tests=new Tests{actualSceneAccepted=true};string temp="Assets/Game/WhiteActorGuardTestTemp";Require(!Directory.Exists(temp),"Refuse overwrite test temp");Directory.CreateDirectory(temp);AssetDatabase.Refresh();
   try{
    Material near=render.nearMaterial,mid=render.midMaterial,far=render.farMaterial;
    render.nearMaterial=null;var e=new List<string>();ActorMaterialBuildGuard.InspectUnit(unit,e);tests.missingNearRejected=e.Any(x=>x.Contains("LOD0: missing material"));render.nearMaterial=near;
    render.midMaterial=null;e.Clear();ActorMaterialBuildGuard.InspectUnit(unit,e);tests.missingMidRejected=e.Any(x=>x.Contains("LOD1: missing material"));render.midMaterial=mid;
    render.farMaterial=null;e.Clear();ActorMaterialBuildGuard.InspectUnit(unit,e);tests.missingFarRejected=e.Any(x=>x.Contains("LOD2: missing material"));render.farMaterial=far;
    var bad=Object.Instantiate(near);string file=temp+"/MissingAtlas.mat";AssetDatabase.CreateAsset(bad,file);AssetDatabase.SaveAssets();string yaml=File.ReadAllText(file);string textureGuid=AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(near.GetTexture("_BaseMap")));Require(yaml.Contains(textureGuid),"Fixture must start with real albedo reference");string fake="bad1bad1bad1bad1bad1bad1bad1bad1";Require(string.IsNullOrEmpty(AssetDatabase.GUIDToAssetPath(fake)),"Fixture GUID collision");File.WriteAllText(file,yaml.Replace(textureGuid,fake));AssetDatabase.ImportAsset(file,ImportAssetOptions.ForceUpdate|ImportAssetOptions.ForceSynchronousImport);e.Clear();ActorMaterialBuildGuard.InspectMaterial(AssetDatabase.LoadAssetAtPath<Material>(file),"injected missing atlas",e);tests.missingAssignedTextureRejected=e.Any(x=>x.Contains(fake));
    var solid=new Material(Shader.Find("Universal Render Pipeline/Lit"));solid.SetColor("_BaseColor",new Color(.3f,.5f,.2f));AssetDatabase.CreateAsset(solid,temp+"/Solid.mat");AssetDatabase.SaveAssets();e.Clear();ActorMaterialBuildGuard.InspectMaterial(solid,"legitimate color-only material",e);tests.intentionalSolidColorAccepted=e.Count==0;
   }finally{Object.DestroyImmediate(unit);Object.DestroyImmediate(render);AssetDatabase.DeleteAsset(temp);}
   tests.passed=tests.actualSceneAccepted&&tests.missingAssignedTextureRejected&&tests.missingNearRejected&&tests.missingMidRejected&&tests.missingFarRejected&&tests.intentionalSolidColorAccepted;File.WriteAllText(Logs+"/guard-regression.json",JsonUtility.ToJson(tests,true));Require(tests.passed,"Guard regression failed");WriteDependencies(scene);Debug.Log("WHITE_ACTOR_GUARD_TESTS_PASSED");
  }
  [Serializable]class Dependency{public string path,sha256;}
  [Serializable]class Manifest{public Dependency[] files;}
  static void WriteDependencies(Scene scene){var files=new HashSet<string>();foreach(string path in AssetDatabase.GetDependencies(ActorMaterialBuildGuard.Units(scene).Select(AssetDatabase.GetAssetPath).ToArray(),true)){if(!path.StartsWith("Assets/")||!File.Exists(path))continue;files.Add(path);if(File.Exists(path+".meta"))files.Add(path+".meta");}var list=new List<Dependency>();foreach(var p in files.OrderBy(x=>x)){using(var f=File.OpenRead(p))using(var h=SHA256.Create())list.Add(new Dependency{path=p,sha256=BitConverter.ToString(h.ComputeHash(f)).Replace("-","").ToLowerInvariant()});}File.WriteAllText(Logs+"/actor-dependency-manifest.json",JsonUtility.ToJson(new Manifest{files=list.ToArray()},true));}
  [Serializable]class HardenRow{public bool passed,byteIdenticalCopy,independentOfSourceFolder;public string runtimeAtlas;public string[] reboundMaterials;}
  public static void Harden(){Require(File.Exists(Atlas),"Recover original before hardening");Require(!File.Exists(RuntimeAtlas),"Refuse overwrite runtime dependency");string[] paths={"Assets/MassEngine/VatRender/Materials/LitInstancedAgent.mat","Assets/MassEngine/VatRender/Materials/FarInstancedAgent.mat","Assets/MassEngine/VatRender/Materials/LitInstancedAgent_Defender.mat","Assets/MassEngine/VatRender/Materials/FarInstancedAgent_Defender.mat"};var original=AssetDatabase.LoadAssetAtPath<Texture2D>(Atlas);var materials=paths.Select(AssetDatabase.LoadAssetAtPath<Material>).ToArray();Require(materials.All(m=>m!=null&&m.GetTexture("_BaseMap")==original),"Unexpected existing material binding; do not overwrite user edits");Directory.CreateDirectory(Logs+"/material-backups");foreach(var path in paths)File.Copy(path,Logs+"/material-backups/"+Path.GetFileName(path),false);if(File.Exists(Logs+"/after.json"))File.Copy(Logs+"/after.json",Logs+"/after-original-restore.json",false);
   Directory.CreateDirectory(Path.GetDirectoryName(RuntimeAtlas));AssetDatabase.Refresh();Require(AssetDatabase.CopyAsset(Atlas,RuntimeAtlas),"Copy runtime atlas");var texture=AssetDatabase.LoadAssetAtPath<Texture2D>(RuntimeAtlas);Require(texture!=null,"Missing runtime copy");foreach(var m in materials){m.SetTexture("_BaseMap",texture);EditorUtility.SetDirty(m);}AssetDatabase.SaveAssets();bool identical=File.ReadAllBytes(Atlas).SequenceEqual(File.ReadAllBytes(RuntimeAtlas));Require(identical,"Pixel source changed");var scene=EditorSceneManager.OpenScene(Source+"/ForestHills.unity",OpenSceneMode.Single);ActorMaterialBuildGuard.RequireValid(scene);var deps=AssetDatabase.GetDependencies(ActorMaterialBuildGuard.Units(scene).Select(AssetDatabase.GetAssetPath).ToArray(),true);bool independent=deps.Contains(RuntimeAtlas)&&!deps.Contains(Atlas);Require(independent,"Actors still depend on disposable source atlas");File.WriteAllText(Logs+"/harden.json",JsonUtility.ToJson(new HardenRow{passed=true,byteIdenticalCopy=identical,independentOfSourceFolder=independent,runtimeAtlas=RuntimeAtlas,reboundMaterials=paths},true));After();
  }
  public static void Prepare(){Require(!Directory.Exists(Root),"Refuse overwrite19");Directory.CreateDirectory(Root);AssetDatabase.Refresh();Require(AssetDatabase.CopyAsset(Source+"/Catalog.asset",Root+"/Catalog.asset"),"Copy catalog");Require(AssetDatabase.CopyAsset(Source+"/ForestHills.unity",Battle),"Copy scene");var catalog=AssetDatabase.LoadAssetAtPath<WarSandboxBattlefieldCatalog>(Root+"/Catalog.asset");foreach(var entry in catalog.entries){entry.id="forest-scenery19";entry.scenePath=Battle;entry.displayName="林间旷野 · 轻量景观";}catalog.defaultEntryId="forest-scenery19";EditorUtility.SetDirty(catalog);
   var scene=EditorSceneManager.OpenScene(Battle,OpenSceneMode.Single);Object.FindFirstObjectByType<WarSandboxRuntimeDeployment>().battlefieldCatalog=catalog;ActorMaterialBuildGuard.RequireValid(scene);EditorSceneManager.SaveScene(scene);CapturePreview(Camera.main,catalog);AssetDatabase.SaveAssets();Require(AssetDatabase.CopyAsset(Source+"/LaunchMenu.unity",Menu),"Copy menu");var menu=EditorSceneManager.OpenScene(Menu,OpenSceneMode.Single);Object.FindFirstObjectByType<WarSandboxSceneSession>().catalog=catalog;ActorMaterialBuildGuard.RequireValid(menu);EditorSceneManager.SaveScene(menu);AssetDatabase.SaveAssets();File.WriteAllText(Logs+"/prepare.json","{\"passed\":true,\"restoredOriginalAtlas\":true,\"newSceneRoot\":\"Assets/Game/Experiments/MaterialFix\"}");}
  static void CapturePreview(Camera camera,WarSandboxBattlefieldCatalog catalog){var rt=new RenderTexture(1280,720,24);var image=new Texture2D(1280,720,TextureFormat.RGB24,false);var oldTarget=camera.targetTexture;var old=RenderTexture.active;try{camera.targetTexture=rt;camera.Render();RenderTexture.active=rt;image.ReadPixels(new Rect(0,0,1280,720),0,0);image.Apply();File.WriteAllBytes(Root+"/Preview.png",image.EncodeToPNG());}finally{camera.targetTexture=oldTarget;RenderTexture.active=old;rt.Release();Object.DestroyImmediate(rt);Object.DestroyImmediate(image);}AssetDatabase.ImportAsset(Root+"/Preview.png");var importer=(TextureImporter)AssetImporter.GetAtPath(Root+"/Preview.png");importer.maxTextureSize=512;importer.SaveAndReimport();foreach(var e in catalog.entries)e.preview=AssetDatabase.LoadAssetAtPath<Texture2D>(Root+"/Preview.png");EditorUtility.SetDirty(catalog);}
  [Serializable]class BuildRow{public bool passed;public string buildGuid;public int errors,warnings;}
  public static void Build(){const string dir="Builds/Scenery-20261004-19";Require(!Directory.Exists(dir),"Refuse overwrite19 build");Directory.CreateDirectory(dir);File.WriteAllText(Logs+"/guard-build-start.txt",DateTime.UtcNow.ToString("o"));var r=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{Menu,Battle},locationPathName=dir+"/WarSandbox.exe",target=BuildTarget.StandaloneWindows64,options=BuildOptions.Development});File.WriteAllText(Logs+"/build.json",JsonUtility.ToJson(new BuildRow{passed=r.summary.result==BuildResult.Succeeded,buildGuid=r.summary.guid.ToString(),errors=(int)r.summary.totalErrors,warnings=(int)r.summary.totalWarnings},true));Require(r.summary.result==BuildResult.Succeeded,"Build19 failed");File.WriteAllText(dir+"/Start-Terrain.cmd","@echo off\r\ncd /d \"%~dp0\"\r\nstart \"\" \"WarSandbox.exe\" -screen-fullscreen 1 -window-mode exclusive -screen-width 1920 -screen-height 1080\r\n");}
 }
}
