#pragma kernel ClassifyVisibleAgentsByTeam

#include "AgentDataCommon_Stage6.hlsl"

[numthreads(64, 1, 1)]
void ClassifyVisibleAgentsByTeam(uint3 id : SV_DispatchThreadID)
{
    if (!IsValidAgentIndex(id.x))
        return;

    AgentData agent = agentBuffer[id.x];
    if (hpReadBuffer[id.x] <= 0)
        AppendVisibleAgent(id.x, agent, deathClipDuration, false, false);
    else
        AppendVisibleAgent(id.x, agent, animationDuration, true, true);

    agentBuffer[id.x] = agent;
}
