#if UNITY_EDITOR
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.TestTools;
using Unity.Profiling;
namespace MassEngine.Game.Tests {
 public sealed class P9CapacityTests {
  const BindingFlags Private=BindingFlags.Instance|BindingFlags.NonPublic;
  LocalOrdersSceneTests owner;MassEngineManager m;WarSandboxBattleController c;string output;
  float scale;int vsync,fps;readonly List<UnityEngine.Object> clones=new List<UnityEngine.Object>();ScenarioConfig original;
  static string F(double v)=>v.ToString("R",CultureInfo.InvariantCulture);
  static string Arg(string p)=>Environment.GetCommandLineArgs().FirstOrDefault(x=>x.StartsWith(p))?.Substring(p.Length);
  IEnumerator Frames(int n){for(int i=0;i<n;i++)yield return null;}
  [UnitySetUp]public IEnumerator Setup(){output=Arg("--interaction-p8-output=");Assert.NotNull(output);owner=new LocalOrdersSceneTests();yield return owner.Setup();m=(MassEngineManager)typeof(LocalOrdersSceneTests).GetField("m",Private).GetValue(owner);c=(WarSandboxBattleController)typeof(LocalOrdersSceneTests).GetField("c",Private).GetValue(owner);scale=Time.timeScale;vsync=QualitySettings.vSyncCount;fps=Application.targetFrameRate;Time.captureDeltaTime=0;Time.timeScale=1;original=m.scenarioConfig;}
  [UnityTearDown]public IEnumerator Cleanup(){if(m!=null){m.PauseBattle();m.DisableLocalOrderPrototype();m.enabled=false;m.scenarioConfig=original;}if(owner!=null)yield return owner.Cleanup();foreach(var o in clones)if(o!=null)UnityEngine.Object.Destroy(o);Time.timeScale=scale;QualitySettings.vSyncCount=vsync;Application.targetFrameRate=fps;}
  T Clone<T>(T x)where T:UnityEngine.Object{var y=UnityEngine.Object.Instantiate(x);clones.Add(y);return y;}
  [Serializable]class Placement{public int agents;public bool fits;public string reason;public Vector2[] centers;public Vector3[] sizes;public float[] densities;}
  [Serializable]class Inventory{public string gpu,api,scope="Authored Green geometry; no asset edits; standing Hold diagnostic, not battle or Player FPS qualification";public int graphicsMB,agents,gridCells,maxPerCell,flowCells,types,teams,validTeam0;public float navClearance;public Vector2 origin;public int resolutionX,resolutionZ;public float cell;public long currentCoreBufferBytes;public List<Placement> placements=new List<Placement>();}
  Placement Plan(int total){var u=original.unitTypes;var p=new Placement{agents=total,centers=new Vector2[u.Length],sizes=new Vector3[u.Length],densities=new float[u.Length]};if(u.Length!=2||u[0].teamId!=0||u[1].teamId!=1){p.reason="Requires two original teams in stable unit order; do not silently substitute roster.";return p;}var nav=m.TerrainNavigation;var candidates=new List<Vector2>[2];
   for(int t=0;t<2;t++){var sp=u[t].spawnConfig;p.densities[t]=sp.ResolveDensity();p.sizes[t]=SpawnConfig.ResolveSpawnSize(total/2,p.densities[t],sp.ResolveSpawnSize().z/sp.ResolveSpawnSize().x,Vector3.zero);candidates[t]=new List<Vector2>();for(int z=0;z<nav.ResolutionZ;z+=4)for(int x=0;x<nav.ResolutionX;x+=4){var v=nav.CellCenter(z*nav.ResolutionX+x);if(t==0?v.x>=-8:v.x<=8)continue;if(nav.IsFootprintWalkable(v,new Vector2(p.sizes[t].x,p.sizes[t].z)))candidates[t].Add(v);} }
   foreach(var a in candidates[0].OrderBy(v=>Mathf.Abs(v.y)+Mathf.Abs(v.x)))foreach(var b in candidates[1].OrderBy(v=>Mathf.Abs(v.y)+Mathf.Abs(v.x))){if(b.x-a.x<(p.sizes[0].x+p.sizes[1].x)*.5f+16)continue;if(!nav.AreConnected(a,b))continue;p.centers[0]=a;p.centers[1]=b;p.fits=true;p.reason="Conservative full-footprint navigation checks; original effective density/aspect, two disjoint connected formations.";return p;}p.reason="No legal pair in the documented 4-cell-stride placement search. Not proof no other layout exists; no density increase or terrain removal permitted.";return p;
  }
  long Buffers(){var seen=new HashSet<ComputeBuffer>();Action<object> scan=o=>{foreach(var f in o.GetType().GetFields(BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic)){var v=f.GetValue(o);if(v is ComputeBuffer b)seen.Add(b);if(v is ComputeBuffer[] a)foreach(var q in a)if(q!=null)seen.Add(q);}};scan(m.Buffers);scan(m.Buffers.combatBuffers);return seen.Where(x=>x!=null).Sum(x=>(long)x.count*x.stride);}
  [UnityTest,Timeout(240000)]public IEnumerator CapacityGeometryPreflight(){m.PauseBattle();var nav=m.TerrainNavigation;var pos=new Vector2[m.Buffers.AgentCount];var team=new int[pos.Length];m.Buffers.agentPositionReadBuffer.GetData(pos);m.Buffers.combatBuffers.teamIdBuffer.GetData(team);var r=new Inventory{gpu=SystemInfo.graphicsDeviceName,api=SystemInfo.graphicsDeviceType.ToString(),graphicsMB=SystemInfo.graphicsMemorySize,agents=pos.Length,gridCells=m.Buffers.GridCellCount,maxPerCell=m.Buffers.MaxAgentsPerCell,flowCells=m.Buffers.FlowCellCount,types=m.Buffers.UnitTypeCount,teams=m.Buffers.TeamCount,origin=nav.Origin,resolutionX=nav.ResolutionX,resolutionZ=nav.ResolutionZ,cell=nav.CellSize,navClearance=nav.Clearance,currentCoreBufferBytes=Buffers(),validTeam0=Enumerable.Range(0,pos.Length).Count(i=>team[i]==0&&nav.IsWalkable(pos[i]))};foreach(int n in new[]{2048,50000}){r.placements.Add(Plan(n));yield return null;}File.WriteAllText(Path.Combine(output,"capacity-geometry.json"),JsonUtility.ToJson(r,true));Debug.Log("P9_STAGE capacity-geometry "+JsonUtility.ToJson(r));}
  IEnumerator Resolution(){var asm=typeof(EditorWindow).Assembly;var st=asm.GetType("UnityEditor.GameViewSizes");var sizes=typeof(ScriptableSingleton<>).MakeGenericType(st).GetProperty("instance",BindingFlags.Public|BindingFlags.Static).GetValue(null);var gt=asm.GetType("UnityEditor.GameViewSizeGroupType");var group=st.GetMethod("GetGroup").Invoke(sizes,new[]{Enum.Parse(gt,"Standalone")});var t=group.GetType();int index=(int)t.GetMethod("GetBuiltinCount").Invoke(group,null)+(int)t.GetMethod("GetCustomCount").Invoke(group,null);var size=Activator.CreateInstance(asm.GetType("UnityEditor.GameViewSize"),BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic,null,new object[]{Enum.Parse(asm.GetType("UnityEditor.GameViewSizeType"),"FixedResolution"),1280,720,"P9 capacity owned"},CultureInfo.InvariantCulture);t.GetMethod("AddCustomSize").Invoke(group,new[]{size});var view=EditorWindow.GetWindow(asm.GetType("UnityEditor.GameView"));view.Show();view.Focus();view.GetType().GetProperty("selectedSizeIndex",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).SetValue(view,index);yield return Frames(30);Assert.AreEqual(1280,Screen.width);Assert.AreEqual(720,Screen.height);}
  struct Sample{public int frame,groups;public double wall,gpu;public long main,memory;public bool fresh;}
  sealed class Counter:IDispatchListener{public readonly Dictionary<string,int> counts=new Dictionary<string,int>();public void OnDispatch(string label){counts.TryGetValue(label,out var n);counts[label]=n+1;}public int Get(string label)=>counts.TryGetValue(label,out var n)?n:0;}
  IEnumerator Measure(int total){Assert.False(Application.isBatchMode);yield return Resolution();QualitySettings.vSyncCount=0;Application.targetFrameRate=-1;
   if(total!=2048){var p=Plan(total);File.WriteAllText(Path.Combine(output,"placement.json"),JsonUtility.ToJson(p,true));Assert.True(p.fits,p.reason);var sc=Clone(original);sc.unitTypes=new UnitTypeConfig[2];for(int i=0;i<2;i++){var u=Clone(original.unitTypes[i]);u.spawnConfig=Clone(u.spawnConfig);u.spawnConfig.unitCount=total/2;u.spawnConfig.spawnCenter=new Vector3(p.centers[i].x,0,p.centers[i].y);u.spawnConfig.spawnSize=p.sizes[i];sc.unitTypes[i]=u;}m.scenarioConfig=sc;}
   var cam=m.cullingCamera;Assert.NotNull(cam);Vector3 cp=new Vector3(0,400,-260);Quaternion cq=Quaternion.LookRotation(-cp);int rendered=0,last=-1;Action<Camera> observe=v=>{if(v==cam&&v.targetTexture==null&&last!=Time.frameCount){last=Time.frameCount;rendered++;}};Camera.CameraCallback post=v=>observe(v);Action<ScriptableRenderContext,Camera> srp=(ctx,v)=>observe(v);Camera.onPostRender+=post;RenderPipelineManager.endCameraRendering+=srp;
   var main=ProfilerRecorder.StartNew(ProfilerCategory.Internal,"Main Thread",1);var ft=new FrameTiming[1];ulong stamp=0;
   var commands=new List<string>{"window,mode,cache,selected,observed_ms,readback_ms,plan_ms,upload_ms,executing,blocked"};var summaries=new List<string>{"window,mode,agents,samples,camera_frames,alive,groups,local_bytes,core_buffer_bytes,global_dispatches,local_dispatches,overflow_end,sentinel,width,height,gpu_valid_samples,visible_instances_end"};int window=0;
   try{foreach(string mode in new[]{"off","empty","selected4","selected1000","selected1000","selected4","empty","off"}){window++;m.PauseBattle();m.ResetScenario();c.RebuildArmyStates();Assert.AreEqual(total,m.Buffers.AgentCount);Assert.True(c.IssueOrder(ArmyOrder.Hold(0)));Assert.True(c.IssueOrder(ArmyOrder.Hold(1)));m.PauseBattle();cam.transform.SetPositionAndRotation(cp,cq);yield return Frames(5);if(mode!="off")Assert.True(m.TryEnableLocalOrderPrototype(out var err),err);
    var pipeline=(ComputePipelineOrchestrator)typeof(MassEngineManager).GetField("pipelineOrchestrator",Private).GetValue(m);var field=typeof(ComputePipelineOrchestrator).GetField("dispatchListener",Private);var old=field.GetValue(pipeline);var counter=new Counter();field.SetValue(pipeline,counter);
    try{m.StartBattle();if(mode.StartsWith("selected")){int k=mode=="selected4"?4:1000;var positions=new Vector2[total];var teams=new int[total];m.Buffers.agentPositionReadBuffer.GetData(positions);m.Buffers.combatBuffers.teamIdBuffer.GetData(teams);var ids=Enumerable.Range(0,total).Where(i=>teams[i]==0&&m.TerrainNavigation.IsWalkable(positions[i])).Take(k).ToArray();Assert.AreEqual(k,ids.Length,"Not enough physically valid members; do not lower selected count");var sw=System.Diagnostics.Stopwatch.StartNew();var receipt=m.LocalOrders.Submit(m.LocalOrders.Epoch,0,window,ids,LocalOrderKind.Hold,Vector2.zero);double deadline=Time.realtimeSinceStartupAsDouble+120;while((receipt.Status==LocalOrderStatus.AwaitingSnapshot||receipt.GpuExecutingMembers==0)&&Time.realtimeSinceStartupAsDouble<deadline){if(receipt.Status==LocalOrderStatus.Rejected)Assert.Fail(receipt.Error);yield return null;}Assert.Greater(receipt.GpuExecutingMembers,0,receipt.Error);Assert.AreEqual(k,receipt.SubmittedMembers);commands.Add(string.Join(",",window,mode,"existing-cache-first-use-not-cold-ABA",k,F(sw.Elapsed.TotalMilliseconds),F(receipt.ReadbackMilliseconds),F(receipt.PlanMilliseconds),F(receipt.UploadMilliseconds),receipt.GpuExecutingMembers,receipt.GpuBlockedMembers));File.WriteAllLines(Path.Combine(output,"commands.csv"),commands);}
     m.StartBattle();double warm=Time.realtimeSinceStartupAsDouble+3;while(Time.realtimeSinceStartupAsDouble<warm){cam.transform.SetPositionAndRotation(cp,cq);yield return null;}counter.counts.Clear();int before=rendered,validGpu=0;var raw=new List<Sample>(4096);double start=Time.realtimeSinceStartupAsDouble,prev=start;
     while(Time.realtimeSinceStartupAsDouble-start<5){cam.transform.SetPositionAndRotation(cp,cq);FrameTimingManager.CaptureFrameTimings();yield return null;double now=Time.realtimeSinceStartupAsDouble;bool fresh=FrameTimingManager.GetLatestTimings(1,ft)>0&&ft[0].frameStartTimestamp>stamp&&ft[0].gpuFrameTime>0;if(fresh){stamp=ft[0].frameStartTimestamp;validGpu++;}raw.Add(new Sample{frame=Time.frameCount,wall=(now-prev)*1000,main=main.Valid?main.LastValue:-1,gpu=fresh?ft[0].gpuFrameTime:0,fresh=fresh,memory=UnityEngine.Profiling.Profiler.GetTotalAllocatedMemoryLong(),groups=m.LocalOrders?.ActiveGroups??0});prev=now;}
     m.PauseBattle();int[] hp=new int[total],stats=new int[4];m.Buffers.combatBuffers.hpReadBuffer.GetData(hp);m.Buffers.spatialHashStatsBuffer.GetData(stats);Assert.AreEqual(MassGpuBufferManager.DeviceResetSentinel,stats[3]);Assert.AreEqual(total,hp.Count(x=>x>0),"Standing comparison must not silently become a casualty comparison");Assert.GreaterOrEqual(rendered-before,(raw.Count)/2);Assert.AreEqual(counter.Get("ClearPendingDamage"),counter.Get("SimulateCombatAndAccumulateDamage"));int locals=counter.counts.Where(x=>x.Key.StartsWith("SimulateLocal")).Sum(x=>x.Value);if(mode.StartsWith("selected"))Assert.Greater(locals,0);else Assert.AreEqual(0,locals);
     uint visible=0;foreach(var args in (ComputeBuffer[])typeof(MassGpuBufferManager).GetField("drawArgsBuffers",Private).GetValue(m.Buffers)){if(args==null)continue;var values=new uint[5];args.GetData(values);visible+=values[1];}Assert.Greater(visible,0,"Camera callbacks alone do not prove visible units");
     File.WriteAllLines(Path.Combine(output,"window-"+window.ToString("00")+"-"+mode+".csv"),new[]{"frame,wall_ms,main_ns,gpu_ms,gpu_new_timestamp,allocated_bytes,local_groups"}.Concat(raw.Select(x=>string.Join(",",x.frame,F(x.wall),x.main,x.fresh?F(x.gpu):"",x.fresh?1:0,x.memory,x.groups))));summaries.Add(string.Join(",",window,mode,total,raw.Count,rendered-before,hp.Count(x=>x>0),m.LocalOrders?.ActiveGroups??0,m.LocalOrders?.GpuBytes??0,Buffers(),counter.Get("SimulateCombatAndAccumulateDamage"),locals,stats[0],stats[3],Screen.width,Screen.height,validGpu,visible));File.WriteAllLines(Path.Combine(output,"windows.csv"),summaries);Debug.Log("P9_STAGE capacity-window "+summaries.Last());
    }finally{field.SetValue(pipeline,old);}}
   }finally{Camera.onPostRender-=post;RenderPipelineManager.endCameraRendering-=srp;main.Dispose();}
  }
  [UnityTest,Timeout(900000)]public IEnumerator Capacity2048Standing(){yield return Measure(2048);}
  [UnityTest,Timeout(900000)]public IEnumerator Capacity50000Standing(){yield return Measure(50000);}
 }
}
#endif
