#if UNITY_EDITOR
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using NUnit.Framework;
using UnityEditor;
using UnityEditorInternal;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.TestTools;
using Unity.Profiling;
using Unity.Profiling.LowLevel.Unsafe;
namespace MassEngine.Game.Tests {
 public sealed class P9CapacityBreakdownTests {
  const BindingFlags P=BindingFlags.Instance|BindingFlags.NonPublic;
  P9CapacityTests owner;MassEngineManager m;WarSandboxBattleController c;string output;ScenarioConfig original;readonly List<UnityEngine.Object> clones=new List<UnityEngine.Object>();int oldVsync,oldFps;bool oldProfiler,oldProfileEditor;
  static string F(double x)=>x.ToString("R",CultureInfo.InvariantCulture);
  static object Field(object o,string name)=>o.GetType().GetField(name,P).GetValue(o);
  T Clone<T>(T o)where T:UnityEngine.Object{var r=UnityEngine.Object.Instantiate(o);clones.Add(r);return r;}
  IEnumerator Frames(int n){for(int i=0;i<n;i++)yield return null;}
  [UnitySetUp]public IEnumerator Setup(){oldProfiler=UnityEngine.Profiling.Profiler.enabled;oldProfileEditor=ProfilerDriver.profileEditor;oldVsync=QualitySettings.vSyncCount;oldFps=Application.targetFrameRate;owner=new P9CapacityTests();yield return owner.Setup();m=(MassEngineManager)Field(owner,"m");c=(WarSandboxBattleController)Field(owner,"c");output=(string)Field(owner,"output");original=m.scenarioConfig;yield return (IEnumerator)typeof(P9CapacityTests).GetMethod("Resolution",P).Invoke(owner,null);QualitySettings.vSyncCount=0;Application.targetFrameRate=-1;}
  [UnityTearDown]public IEnumerator Cleanup(){UnityEngine.Profiling.Profiler.enabled=oldProfiler;ProfilerDriver.profileEditor=oldProfileEditor;if(m!=null){m.enabled=false;m.scenarioConfig=original;}if(owner!=null)yield return owner.Cleanup();foreach(var x in clones)if(x!=null)UnityEngine.Object.Destroy(x);QualitySettings.vSyncCount=oldVsync;Application.targetFrameRate=oldFps;}
  IEnumerator Install(int total){m.enabled=true;m.enableGpuDispatch=true;m.PauseBattle();m.scenarioConfig=original;if(total!=2048){var p=typeof(P9CapacityTests).GetMethod("Plan",P).Invoke(owner,new object[]{total});var type=p.GetType();Assert.True((bool)type.GetField("fits").GetValue(p));var centers=(Vector2[])type.GetField("centers").GetValue(p);var sizes=(Vector3[])type.GetField("sizes").GetValue(p);var sc=Clone(original);sc.unitTypes=new UnitTypeConfig[2];for(int i=0;i<2;i++){var u=Clone(original.unitTypes[i]);u.spawnConfig=Clone(u.spawnConfig);u.spawnConfig.unitCount=total/2;u.spawnConfig.spawnCenter=new Vector3(centers[i].x,0,centers[i].y);u.spawnConfig.spawnSize=sizes[i];sc.unitTypes[i]=u;}m.scenarioConfig=sc;}m.ResetScenario();c.RebuildArmyStates();Assert.True(c.IssueOrder(ArmyOrder.Hold(0)));Assert.True(c.IssueOrder(ArmyOrder.Hold(1)));m.StartBattle();Assert.AreEqual(total,m.Buffers.AgentCount);Assert.IsNull(m.LocalOrders);CameraPose();yield return Frames(8);}
  void CameraPose(){var p=new Vector3(0,400,-260);m.cullingCamera.transform.SetPositionAndRotation(p,Quaternion.LookRotation(-p));}
  [Serializable]class LodRow{public int type,lod;public string unit,mesh,material,shader,shadowCasting;public int vertices;public uint indices,instances;public bool receiveShadows;}
  List<LodRow> Census(){var r=new List<LodRow>();var registry=(UnitTypeRegistry)Field(m,"unitTypeRegistry");foreach(var t in registry.RegisteredTypes)for(int l=0;l<3;l++){var a=new uint[5];m.Buffers.GetDrawArgsBuffer(t.UnitTypeIndex,l).GetData(a);var mesh=t.RenderRuntime.GetMesh(l);var mat=t.RenderRuntime.GetMaterial(l);r.Add(new LodRow{type=t.UnitTypeIndex,lod=l,unit=t.Config.name,mesh=mesh!=null?mesh.name:"",material=mat!=null?mat.name:"",shader=mat!=null?mat.shader.name:"",vertices=mesh!=null?mesh.vertexCount:0,indices=a[0],instances=a[1],shadowCasting=t.RenderRuntime.GetShadowCasting(l).ToString(),receiveShadows=t.RenderRuntime.GetReceiveShadows(l)});}return r;}
  [Serializable]class Window{public int window,frames,cameraFrames,alive,overflow;public string phase;public List<LodRow> lods;public List<string> dispatches;}
  [Serializable]class Report{public string method="Diagnostic ablations only, NOT optimized gameplay. full: unchanged manager. no-unit-draw: only runtime unit materials detached; simulation/LOD continue. draw-only: manager GPU-dispatch gate disabled, original indirect unit draws submitted with frozen buffers. neither: manager GPU-dispatch gate disabled and unit draws absent. Other scene systems stay active. Warm 3s + measure 8s, forward/reverse. These non-additive contrasts cannot be summed into independent costs. Raw FrameTiming and recorder values may be delayed; inclusive marker durations must not be summed.";public List<string> markers=new List<string>();public List<string> markerUnits=new List<string>();public List<Window> windows=new List<Window>();}
  sealed class Counter:IDispatchListener{public readonly Dictionary<string,int> counts=new Dictionary<string,int>();public void OnDispatch(string label){counts.TryGetValue(label,out var n);counts[label]=n+1;}}
  struct Row{public int frame;public double wall,gpu,cpu,main,render,present;public long[] markers;public bool fresh;}
  IEnumerator Breakdown(){yield return Install(50000);var report=new Report();var recorderList=new List<ProfilerRecorder>();var handles=new List<ProfilerRecorderHandle>();ProfilerRecorderHandle.GetAvailable(handles);
   foreach(var h in handles){var d=ProfilerRecorderHandle.GetDescription(h);string name=d.Name;if(new[]{"Main Thread","Render Thread","WaitFor","Present","BehaviourUpdate","Camera.Render","RenderLoop","ComputeBuffer.","DrawMeshInstancedIndirect","Draw Calls Count","Triangles Count","Vertices Count","Batches Count","GC.Alloc"}.Any(x=>name.IndexOf(x,StringComparison.OrdinalIgnoreCase)>=0)){if(report.markers.Contains(name))continue;report.markers.Add(name);report.markerUnits.Add(d.UnitType.ToString());recorderList.Add(ProfilerRecorder.StartNew(d.Category,name,1));}}
   var cam=m.cullingCamera;int rendered=0,last=-1;Action<Camera> obs=x=>{if(x==cam&&x.targetTexture==null&&last!=Time.frameCount){last=Time.frameCount;rendered++;}};Camera.CameraCallback post=x=>obs(x);Action<ScriptableRenderContext,Camera> srp=(ctx,x)=>obs(x);Camera.onPostRender+=post;RenderPipelineManager.endCameraRendering+=srp;
   try{int window=0;foreach(string phase in new[]{"full","no-unit-draw","draw-only","neither","neither","draw-only","no-unit-draw","full"}){window++;yield return Install(50000);var registry=(UnitTypeRegistry)Field(m,"unitTypeRegistry");var dispatcher=(MassGpuRenderDispatcher)Field(m,"renderDispatcher");var pipeline=(ComputePipelineOrchestrator)Field(m,"pipelineOrchestrator");var listenerField=typeof(ComputePipelineOrchestrator).GetField("dispatchListener",P);var previous=listenerField.GetValue(pipeline);var counter=new Counter();listenerField.SetValue(pipeline,counter);var materials=registry.RegisteredTypes.Select(t=>new[]{t.RenderRuntime.nearMaterial,t.RenderRuntime.midMaterial,t.RenderRuntime.farMaterial}).ToArray();bool noDraw=phase=="no-unit-draw",frozen=phase=="draw-only"||phase=="neither";var bounds=(Bounds)typeof(MassEngineManager).GetMethod("ResolveRenderBounds",P).Invoke(m,null);var lod=(LodConfig)typeof(MassEngineManager).GetProperty("Lod",P).GetValue(m);var sink=new Vector4(Mathf.Max(0,lod.corpseLingerSeconds),Mathf.Max(0,lod.corpseSinkSeconds),Mathf.Max(0,lod.corpseSinkDepth),0);
    Action step=()=>{CameraPose();if(phase=="draw-only")dispatcher.Draw(registry,m.Buffers,bounds,sink);};
    try{if(noDraw){var skips=(HashSet<int>)Field(dispatcher,"reportedSkippedBatches");foreach(var t in registry.RegisteredTypes){for(int i=0;i<3;i++)skips.Add(t.UnitTypeIndex*3+i);t.RenderRuntime.nearMaterial=t.RenderRuntime.midMaterial=t.RenderRuntime.farMaterial=null;}}if(frozen)m.enableGpuDispatch=false;
     double warm=Time.realtimeSinceStartupAsDouble+3;while(Time.realtimeSinceStartupAsDouble<warm){step();yield return null;}counter.counts.Clear();int before=rendered;var raw=new List<Row>(2048);var timings=new FrameTiming[1];ulong stamp=0;double start=Time.realtimeSinceStartupAsDouble,prev=start;
     while(Time.realtimeSinceStartupAsDouble-start<8){step();FrameTimingManager.CaptureFrameTimings();yield return null;double now=Time.realtimeSinceStartupAsDouble;bool fresh=FrameTimingManager.GetLatestTimings(1,timings)>0&&timings[0].frameStartTimestamp>stamp;var ft=timings[0];if(fresh)stamp=ft.frameStartTimestamp;var values=new long[recorderList.Count];for(int i=0;i<values.Length;i++)values[i]=recorderList[i].Valid?recorderList[i].LastValue:-1;raw.Add(new Row{frame=Time.frameCount,wall=(now-prev)*1000,fresh=fresh,gpu=ft.gpuFrameTime,cpu=ft.cpuFrameTime,main=ft.cpuMainThreadFrameTime,render=ft.cpuRenderThreadFrameTime,present=ft.cpuMainThreadPresentWaitTime,markers=values});prev=now;}
     m.PauseBattle();var hp=new int[50000];m.Buffers.combatBuffers.hpReadBuffer.GetData(hp);var stats=new int[4];m.Buffers.spatialHashStatsBuffer.GetData(stats);Assert.AreEqual(50000,hp.Count(x=>x>0));Assert.AreEqual(MassGpuBufferManager.DeviceResetSentinel,stats[3]);Assert.Greater(rendered-before,raw.Count/2);Assert.AreEqual(frozen, counter.counts.Count==0);report.windows.Add(new Window{window=window,phase=phase,frames=raw.Count,cameraFrames=rendered-before,alive=50000,overflow=stats[0],lods=Census(),dispatches=counter.counts.Select(x=>x.Key+"="+x.Value).ToList()});
     var header="frame,wall_ms,fresh,gpu_ms,ft_cpu_ms,ft_main_ms,ft_render_ms,ft_present_wait_ms,"+string.Join(",",report.markers.Select(x=>"\""+x.Replace("\"","\"\"")+"\""));File.WriteAllLines(Path.Combine(output,"breakdown-"+window.ToString("00")+"-"+phase+".csv"),new[]{header}.Concat(raw.Select(x=>string.Join(",",x.frame,F(x.wall),x.fresh?1:0,x.fresh?F(x.gpu):"",x.fresh?F(x.cpu):"",x.fresh?F(x.main):"",x.fresh?F(x.render):"",x.fresh?F(x.present):"")+","+string.Join(",",x.markers))));File.WriteAllText(Path.Combine(output,"breakdown.json"),JsonUtility.ToJson(report,true));Debug.Log("P9_STAGE breakdown "+window+" "+phase+" frames="+raw.Count);
    }finally{for(int i=0;i<registry.RegisteredTypes.Count;i++){var r=registry.RegisteredTypes[i].RenderRuntime;r.nearMaterial=materials[i][0];r.midMaterial=materials[i][1];r.farMaterial=materials[i][2];}m.enableGpuDispatch=true;listenerField.SetValue(pipeline,previous);}}
   }finally{Camera.onPostRender-=post;RenderPipelineManager.endCameraRendering-=srp;foreach(var r in recorderList)r.Dispose();}
   yield return ProfileCpu();
  }
  IEnumerator ProfileCpu(){yield return Install(50000);double warm=Time.realtimeSinceStartupAsDouble+3;while(Time.realtimeSinceStartupAsDouble<warm){CameraPose();yield return null;}UnityEngine.Profiling.Profiler.enabled=true;ProfilerDriver.profileEditor=false;int before=ProfilerDriver.lastFrameIndex;double stop=Time.realtimeSinceStartupAsDouble+5;while(Time.realtimeSinceStartupAsDouble<stop){CameraPose();yield return null;}UnityEngine.Profiling.Profiler.enabled=false;int end=ProfilerDriver.lastFrameIndex;var csv=new List<string>{"frame,thread,name,inclusive_ms,calls"};for(int f=Math.Max(before+2,ProfilerDriver.firstFrameIndex);f<=end-2;f++)for(int t=0;t<16;t++){using(var view=ProfilerDriver.GetRawFrameDataView(f,t)){if(!view.valid)break;var sums=new Dictionary<string,(double ms,int n)>();for(int s=0;s<view.sampleCount;s++){string name=view.GetSampleName(s);double ms=view.GetSampleTimeMs(s);if(ms<=0)continue;sums.TryGetValue(name,out var old);sums[name]=(old.ms+ms,old.n+1);}foreach(var v in sums.Where(x=>x.Value.ms>=.1).OrderByDescending(x=>x.Value.ms).Take(60))csv.Add(string.Join(",",f,"\""+view.threadName.Replace("\"","\"\"")+"\"","\""+v.Key.Replace("\"","\"\"")+"\"",F(v.Value.ms),v.Value.n));}}File.WriteAllLines(Path.Combine(output,"cpu-profile-inclusive.csv"),csv);Assert.Greater(csv.Count,1,"No CPU profile samples captured; do not claim a breakdown");UnityEngine.Profiling.Profiler.enabled=oldProfiler;ProfilerDriver.profileEditor=oldProfileEditor;}
  [UnityTest,Timeout(900000)]public IEnumerator Capacity50000Breakdown(){yield return Breakdown();}
  [UnityTest,Timeout(900000)]public IEnumerator CapacityWarmCommands(){var rows=new List<string>{"agents,selected,repetition,phase,observed_ms,readback_ms,plan_ms,upload_ms,executing,blocked,nav_contexts"};foreach(int total in new[]{2048,50000}){yield return Install(total);foreach(int k in new[]{4,1000}){m.DisableLocalOrderPrototype();Assert.True(m.TryEnableLocalOrderPrototype(out var error),error);var p=new Vector2[total];var teams=new int[total];m.Buffers.agentPositionReadBuffer.GetData(p);m.Buffers.combatBuffers.teamIdBuffer.GetData(teams);var ids=Enumerable.Range(0,total).Where(i=>teams[i]==0&&m.TerrainNavigation.IsWalkable(p[i])).Take(k).ToArray();Assert.AreEqual(k,ids.Length);for(int rep=0;rep<3;rep++){CameraPose();var sw=System.Diagnostics.Stopwatch.StartNew();var r=m.LocalOrders.Submit(m.LocalOrders.Epoch,0,rep+1,ids,LocalOrderKind.Hold,Vector2.zero);double deadline=Time.realtimeSinceStartupAsDouble+30;while(r.GpuExecutingMembers!=k&&Time.realtimeSinceStartupAsDouble<deadline){Assert.AreNotEqual(LocalOrderStatus.Rejected,r.Status,r.Error);CameraPose();yield return null;}Assert.AreEqual(k,r.GpuExecutingMembers,r.Error);Assert.AreEqual(0,r.GpuBlockedMembers);rows.Add(string.Join(",",total,k,rep,rep==0?"first-on-new-channel-existing-shader-cache":"same-channel-repeat",F(sw.Elapsed.TotalMilliseconds),F(r.ReadbackMilliseconds),F(r.PlanMilliseconds),F(r.UploadMilliseconds),r.GpuExecutingMembers,r.GpuBlockedMembers,m.LocalOrders.NavigationContexts));File.WriteAllLines(Path.Combine(output,"warm-commands.csv"),rows);yield return Frames(10);}}}}
 }
}
#endif
