#if UNITY_EDITOR
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.SceneManagement;
using UnityEngine.TestTools;
using UnityEngine.UI;
using Object=UnityEngine.Object;
namespace MassEngine.Game.Tests {
 public sealed class P9CombinedAcceptanceTests {
  const BindingFlags Private=BindingFlags.Instance|BindingFlags.NonPublic;
  string output;WarSandboxSceneSession session;WarSandboxFrontEnd front;MassEngineManager m;WarSandboxBattleController c;WarSandboxRuntimeDeployment d;WarSandboxDeploymentHUD dh;WarSandboxCommandHUD hud;Camera selectionCamera;
  static readonly FieldInfo RuntimeField=typeof(MassEngineManager).GetField("terrainRuntime",Private);
  TerrainNavigationRuntime Runtime=>m!=null?(TerrainNavigationRuntime)RuntimeField.GetValue(m):null;
  int[] members;float oldCapture,oldScale;Vector2? oldScreen;bool owned;List<string> ledger=new List<string>();
  static object Call(object o,string n,params object[] a)=>o.GetType().GetMethod(n,Private).Invoke(o,a);
  static void Set(object o,string n,object v)=>o.GetType().GetField(n,Private).SetValue(o,v);
  static string F(double x)=>x.ToString("R",CultureInfo.InvariantCulture);
  void Mark(string stage,string detail="") {string row=Time.frameCount+","+F(Time.realtimeSinceStartupAsDouble)+","+stage+","+detail;ledger.Add(row);File.WriteAllLines(Path.Combine(output,"stages-"+TestContext.CurrentContext.Test.MethodName+".csv"),ledger);Debug.Log("P9_STAGE "+stage+" "+detail);}
  IEnumerator Frames(int n=12){double until=Time.realtimeSinceStartupAsDouble+n/60.0;for(int i=0;i<n||Time.realtimeSinceStartupAsDouble<until;i++)yield return null;}
  static T[] Active<T>() where T:Component=>Object.FindObjectsByType<T>(FindObjectsSortMode.None).Where(x=>x.gameObject.activeInHierarchy).ToArray();
  Button Button(string name){var b=Active<Button>().SingleOrDefault(x=>x.name==name);Assert.NotNull(b,"UI button "+name);Assert.True(b.interactable,"UI enabled "+name);return b;}
  IEnumerator Click(string name){Button(name).onClick.Invoke();yield return Frames();}
  void Input(string name,string value){var f=Active<InputField>().SingleOrDefault(x=>x.name==name);Assert.NotNull(f,"UI input "+name+"; active="+string.Join(";",Active<InputField>().Select(x=>x.name)));f.text=value;f.onEndEdit.Invoke(value);}
  [UnitySetUp]public IEnumerator Setup(){var arg=Environment.GetCommandLineArgs().FirstOrDefault(x=>x.StartsWith("--interaction-p8-output="));Assert.NotNull(arg,"Owned isolated P9 runner required");output=arg.Split(new[]{'='},2)[1];owned=true;oldCapture=Time.captureDeltaTime;oldScale=Time.timeScale;oldScreen=WarSandboxUGUI.ScreenSizeOverride;Time.captureDeltaTime=0;Time.timeScale=1;WarSandboxUGUI.ScreenSizeOverride=new Vector2(1280,720);Assert.IsNull(WarSandboxSceneSession.Instance);yield return SceneManager.LoadSceneAsync("Assets/Game/Scenes/MainMenu.unity",LoadSceneMode.Single);yield return Frames();session=WarSandboxSceneSession.Instance;Assert.NotNull(session);front=session.GetComponent<WarSandboxFrontEnd>();Assert.NotNull(front);Assert.AreEqual(WarSandboxEntryState.Menu,session.State);Mark("menu-ready","single-process production scene session; synthetic uGUI callbacks, not OS input");}
  IEnumerator Loaded(){double until=Time.realtimeSinceStartupAsDouble+120;while(session.IsLoading&&Time.realtimeSinceStartupAsDouble<until)yield return null;Assert.False(session.IsLoading,"Scene transition timeout");Assert.AreNotEqual(WarSandboxEntryState.Failed,session.State,session.Error);yield return Frames();}
  void Bind(){c=session.Controller;Assert.NotNull(c);m=c.manager;d=m.GetComponent<WarSandboxRuntimeDeployment>();dh=m.GetComponent<WarSandboxDeploymentHUD>();hud=m.GetComponent<WarSandboxCommandHUD>();Assert.NotNull(d);d.PlanStore=new WarSandboxLocalPlanStore(Path.Combine(output,"plans"));Assert.AreEqual(2048,m.Buffers.AgentCount);}
  IEnumerator Enter(string id="forest-green22"){Assert.True(session.TryEnterBattlefield(id,false,out var error),error);yield return Loaded();Bind();Mark("entered",id+";allocated=2048");}
  int WorkspaceCount(){var t=typeof(TerrainNavigationRuntime).Assembly.GetType("MassEngine.TerrainNavigationBurstWorkspace");return (int)t.GetProperty("ActiveWorkspaces",BindingFlags.Public|BindingFlags.Static).GetValue(null);}
  IEnumerator Menu(){var buffers=m?.Buffers;var nav=Runtime;var local=m?.LocalOrders;var selection=hud?.SelectionPreview;Assert.True(session.TryReturnToMenu(true,out var error),error);yield return Loaded();Assert.AreEqual(WarSandboxEntryState.Menu,session.State);if(buffers!=null)Assert.False(buffers.IsAllocated,"GPU buffers retained after unload");if(nav!=null)Assert.AreEqual("Disposed",nav.PreparationState);if(local!=null){Assert.True(local.IsDisposed);Assert.AreEqual(0,local.GpuBytes);}if(selection!=null){Assert.False(selection.IsCurrent);Assert.AreEqual(0,selection.LogicalGpuBytes);}Assert.AreEqual(0,WorkspaceCount());m=null;c=null;d=null;dh=null;hud=null;selectionCamera=null;yield return Resources.UnloadUnusedAssets();GC.Collect();yield return Frames();Mark("menu-resources-released","old buffers/local/selection/Burst workspace released");}
  [UnityTearDown]public IEnumerator Cleanup(){if(!owned)yield break;if(session!=null&&session.State==WarSandboxEntryState.Battle&&!session.IsLoading){yield return Menu();}if(session!=null)Object.Destroy(session.gameObject);yield return Frames(2);Time.captureDeltaTime=oldCapture;Time.timeScale=oldScale;WarSandboxUGUI.ScreenSizeOverride=oldScreen;}
  WarSandboxDeploymentMapPointer Pointer()=>Active<WarSandboxDeploymentMapPointer>().Single();
  Vector2 MapPoint(Vector3 v){var p=Pointer();var world=d.WorldSize;return RectTransformUtility.WorldToScreenPoint(null,p.Rect.TransformPoint(new Vector3((v.x/world.x+.5f)*p.Rect.rect.width,-(.5f-v.z/world.y)*p.Rect.rect.height,0)));}
  Vector3 LegalTranslation(){var original=d.Draft[0];foreach(var delta in new[]{new Vector3(0,0,24),new Vector3(0,0,-24),new Vector3(-24,0,0),new Vector3(24,0,0)}){var entries=d.Draft.Snapshot();entries[0].center+=delta;var candidate=new WarSandboxDeploymentDraft(entries,d.Draft.Rules,d.Draft.Stats);object[] args={candidate,null};if((bool)Call(d,"ValidateDraft",args))return entries[0].center;}Assert.Fail("No valid translation fixture");return original.center;}
  IEnumerator Drag(Vector3 from,Vector3 to,bool resize){var pointer=Pointer();var draft=d.Draft;var old=draft[0];int rev=draft.Revision;var buffer=m.Buffers.agentBuffer;var e=new PointerEventData(EventSystem.current){button=PointerEventData.InputButton.Left,pointerId=-1,position=MapPoint(from)};ExecuteEvents.Execute(pointer.gameObject,e,ExecuteEvents.pointerDownHandler);e.position=MapPoint(to);for(int i=0;i<16;i++)ExecuteEvents.Execute(pointer.gameObject,e,ExecuteEvents.dragHandler);Assert.AreEqual(rev,draft.Revision);Assert.AreEqual(old,draft[0]);Assert.AreSame(buffer,m.Buffers.agentBuffer);ExecuteEvents.Execute(pointer.gameObject,e,ExecuteEvents.pointerUpHandler);Assert.AreEqual(rev+1,draft.Revision);Assert.AreEqual(old.count,draft[0].count);var changed=draft[0];Assert.True(draft.Undo());Assert.AreEqual(old,draft[0]);Assert.True(draft.Redo());Assert.AreEqual(changed,draft[0]);Call(dh,"ReadFields");Set(dh,"nextUiRefresh",0f);yield return Frames();Mark(resize?"resize-undo-redo":"translation-undo-redo","actual EventSystem drag; preview does not change GPU buffer; one commit");}
  IEnumerator Select(){if(selectionCamera==null){var go=new GameObject("P9 projection fixture camera (not rendered)");selectionCamera=go.AddComponent<Camera>();selectionCamera.enabled=false;selectionCamera.orthographic=true;selectionCamera.orthographicSize=35;selectionCamera.nearClipPlane=.1f;selectionCamera.farClipPlane=500;selectionCamera.pixelRect=new Rect(0,0,Mathf.Max(256,Screen.width),Mathf.Max(256,Screen.height));selectionCamera.transform.rotation=Quaternion.LookRotation(Vector3.down,Vector3.forward);}hud.commandCamera=selectionCamera;c.SelectArmy(0);var agents=new AgentData[m.Buffers.AgentCount];m.Buffers.agentBuffer.GetData(agents);var anchor=agents[0].position;selectionCamera.transform.position=anchor+Vector3.up*100;var lo=(Vector2)selectionCamera.WorldToScreenPoint(anchor+new Vector3(-3.5f,0,-3.5f));var hi=(Vector2)selectionCamera.WorldToScreenPoint(anchor+new Vector3(3.5f,0,3.5f));hud.TestSelectionPointerP7(lo,true,false,false);hud.TestSelectionPointerP7(hi,false,true,false);hud.TestSelectionPointerP7(hi,false,false,true);double until=Time.realtimeSinceStartupAsDouble+20;while((hud.SelectionPreview==null||hud.SelectionPreview.Busy||hud.SelectionPreview.State.Scope==MemberSelectionScope.Pending)&&Time.realtimeSinceStartupAsDouble<until)yield return null;Assert.NotNull(hud.SelectionPreview);Assert.True(hud.SelectionPreview.TrySnapshot(out members,out _));Assert.Greater(members.Length,0);Assert.Less(members.Length,128);}
  Vector3 Goal(){var pos=new Vector2[m.Buffers.AgentCount];m.Buffers.agentPositionReadBuffer.GetData(pos);var p=pos[members[0]];foreach(var delta in new[]{new Vector2(24,0),new Vector2(-24,0),new Vector2(0,24),new Vector2(0,-24),new Vector2(40,40)}){var t=p+delta;if(m.TerrainNavigation.IsFootprintWalkable(t,new Vector2(20,20))&&m.TerrainNavigation.AreConnected(p,t))return new Vector3(t.x,0,t.y);}Assert.Fail("No reachable selected-member goal");return Vector3.zero;}
  IEnumerator Order(string button,LocalOrderKind kind,string label){var old=hud.LastPlayerReceipt;double start=Time.realtimeSinceStartupAsDouble,until=start+20;int frame=Time.frameCount;do{Button(button).onClick.Invoke();if(kind==LocalOrderKind.Move)hud.TestGroundMoveP8(Goal());if(hud.LastPlayerReceipt!=old)break;yield return null;}while(Time.realtimeSinceStartupAsDouble<until);var receipt=hud.LastPlayerReceipt;Assert.AreNotSame(old,receipt,"A new scoped command must be submitted");Assert.AreEqual(kind,receipt.Kind);while(receipt.Status==LocalOrderStatus.AwaitingSnapshot&&Time.realtimeSinceStartupAsDouble<until)yield return null;Assert.True(receipt.Status==LocalOrderStatus.Committed||receipt.Status==LocalOrderStatus.GpuExecuting,receipt.Error);CollectionAssert.AreEquivalent(members,receipt.MemberSnapshot);double accepted=Time.realtimeSinceStartupAsDouble;yield return Frames(4);var orders=new LocalAgentOrder[m.Buffers.AgentCount];((ComputeBuffer)typeof(LocalOrderChannel).GetField("orderBuffer",Private).GetValue(m.LocalOrders)).GetData(orders);var selected=new HashSet<int>(members);for(int i=0;i<orders.Length;i++)if(selected.Contains(i))Assert.AreEqual(receipt.Sequence,orders[i].sequence);else Assert.AreEqual(0,orders[i].slotPlusOne,"Unselected override "+i);Assert.AreEqual(ArmyOrderType.Hold,c.GetArmy(0).currentOrder.type);File.AppendAllText(Path.Combine(output,"command-latency.csv"),label+","+kind+","+members.Length+","+F((accepted-start)*1000)+","+(Time.frameCount-frame)+","+receipt.Status+"\n");Mark("scoped-"+kind,label+";selected="+members.Length+";accepted_ms="+F((accepted-start)*1000));}
  IEnumerator Four(string label){yield return Select();yield return Order("attack",LocalOrderKind.Attack,label);yield return Order("hold",LocalOrderKind.Hold,label);yield return Order("retreat",LocalOrderKind.Retreat,label);yield return Order("move",LocalOrderKind.Move,label);}
  [UnityTest,Timeout(900000)]public IEnumerator P9SingleSessionRadiusDeploymentPlansOrdersNaturalResultAndSceneSwitch(){
   front.OpenLibrary();yield return Frames();var entry=WarSandboxRosterChoices.Library(session.catalog)[0];var source=EditorJsonUtility.ToJson(entry.config.flockingConfig);string global=front.LibraryStore.FilePath;StringAssert.StartsWith(Path.GetFullPath(output)+Path.DirectorySeparatorChar,Path.GetFullPath(global));Assert.False(File.Exists(global),"Fresh owned stat file required");Input("lib-r-agentRadius-field","0.6");yield return Frames();Assert.AreEqual(.6f,Active<UnitModelPreviewWidget>().Single().Renderer.ContactRadius);Assert.False(File.Exists(global));yield return Click("lib-discard");Assert.False(File.Exists(global));Mark("radius-cancel","unsaved edit did not create file");Input("lib-r-agentRadius-field","0.6");yield return Frames();Assert.True((bool)Call(front,"SaveLibraryPending",entry));byte[] saved=File.ReadAllBytes(global);Input("lib-r-agentRadius-field","0.7");yield return Frames();yield return Click("lib-discard");CollectionAssert.AreEqual(saved,File.ReadAllBytes(global));Call(front,"CloseLibrary");front.OpenLibrary();yield return Frames();Assert.AreEqual(.6f,Active<UnitModelPreviewWidget>().Single().Renderer.ContactRadius);Call(front,"CloseLibrary");yield return Frames();Mark("radius-save-reenter","same saved UI bytes preserved; preview=.6");
   yield return Enter();var settings=new UnitTypeGpuSettings[m.Buffers.UnitTypeCount];m.Buffers.unitTypeSettingsBuffer.GetData(settings);Assert.AreEqual(.6f,settings[0].agentRadius,"Exact UI saved radius consumed on scene entry");Assert.AreEqual(source,EditorJsonUtility.ToJson(entry.config.flockingConfig));yield return Click("edit");Assert.True(d.IsEditing);var draft=d.Draft;var before=draft[0];var target=LegalTranslation();yield return Drag(before.center+new Vector3(2,0,2),target+new Vector3(2,0,2),false);Set(dh,"spatialSelection",true);Set(dh,"nextUiRefresh",0f);yield return Frames();var r=draft[0];var corner=new Vector3(r.Bounds.xMax,r.center.y,r.Bounds.yMax);yield return Drag(corner,corner+new Vector3(14,0,18),true);var expected=draft.Snapshot();
   yield return Click("deployment-plans");Input("plans-slot","P9");Input("plans-name","P9 联合验收方案");yield return Click("plans-save");Assert.True(d.PlanStore.Exists("P9"));string planPath=Path.Combine(output,"plans/P9.json");byte[] plan=File.ReadAllBytes(planPath);yield return Click("plans-save");yield return Click("plans-confirm-no");CollectionAssert.AreEqual(plan,File.ReadAllBytes(planPath));yield return Click("plans-back");yield return Click("deployment-cancel");Assert.False(d.IsEditing);yield return Click("edit");yield return Click("deployment-plans");yield return Click("plan-item-0");yield return Click("plans-load");yield return Click("plans-confirm-yes");CollectionAssert.AreEqual(expected,d.Draft.Snapshot());Mark("plan-save-cancel-overwrite-reload","same disk file loaded via uGUI; draft and unit counts identical");
   // Corrupt only a separate owned copy; exercise actual load UI and preserve the valid draft/file.
   File.WriteAllText(Path.Combine(output,"plans/Broken.json"),"not-json");yield return Click("deployment-plans");yield return Click("plans-refresh");Assert.True(d.PlanStore.TryListSlots(out var slots,out var error),error);int broken=Array.IndexOf(slots,"Broken");Assert.GreaterOrEqual(broken,0);yield return Click("plan-item-"+broken);yield return Click("plans-load");yield return Click("plans-confirm-yes");CollectionAssert.AreEqual(expected,d.Draft.Snapshot());CollectionAssert.AreEqual(plan,File.ReadAllBytes(planPath));Mark("corrupt-plan-ui-recovery","bad owned copy rejected; draft and good plan preserved");yield return Click("plans-back");yield return Click("deployment-apply");Assert.False(d.IsEditing);Assert.AreEqual(2048,m.Buffers.AgentCount);var agents=new AgentData[2048];m.Buffers.agentBuffer.GetData(agents);for(int i=0;i<expected[0].count;i++){Assert.That(agents[i].position.x,Is.InRange(expected[0].Bounds.xMin-.01f,expected[0].Bounds.xMax+.01f));Assert.That(agents[i].position.z,Is.InRange(expected[0].Bounds.yMin-.01f,expected[0].Bounds.yMax+.01f));}Mark("plan-applied-gpu","2048 real GPU positions inside saved moved/resized footprint");
   Assert.True(c.IssueOrder(ArmyOrder.Hold(0)));Assert.True(c.IssueOrder(ArmyOrder.Hold(1)));yield return Frames(20);yield return Four("joint-session");hud.CloseSelectionPreview();Assert.True(c.StartDefaultBattle());Mark("natural-battle-start","authored rules; normal time; no forced winner or EndBattle");double until=Time.realtimeSinceStartupAsDouble+420,nextLog=0;while(!c.BattleResult.valid&&Time.realtimeSinceStartupAsDouble<until){if(Time.realtimeSinceStartupAsDouble>nextLog){Mark("natural-battle-progress","seconds="+F(c.TelemetrySnapshot.battleSeconds));nextLog=Time.realtimeSinceStartupAsDouble+30;}yield return null;}Assert.True(c.BattleResult.valid,"Natural settlement deadline 420 real seconds; do not force result");Assert.Greater(c.BattleResult.battleSeconds,0);Assert.False(m.IsBattleRunning);if(TerrainNavigationRuntime.BurstReserveRequested){Assert.AreEqual("Ready",Runtime.PreparationState);Assert.Greater(Runtime.BurstSolveCount,0,"Opt-in joint session must execute actual Burst solves");}else Assert.AreEqual(0,Runtime.BurstSolveCount);Mark("joint-backend-proof","burst="+Runtime.BurstSolveCount+";managed="+Runtime.ManagedSolveCount);string result=JsonUtility.ToJson(c.BattleResult);File.WriteAllText(Path.Combine(output,"natural-result.json"),result);yield return Frames(30);Assert.AreEqual(result,JsonUtility.ToJson(c.BattleResult));Assert.IsNull(m.LocalOrders);Assert.IsNull(hud.SelectionPreview);Mark("natural-result-frozen",c.Phase.ToString());Assert.True(c.RestartWithDefaultOrders());Assert.False(c.BattleResult.valid);Assert.AreEqual(2048,m.Buffers.AgentCount);Assert.IsNull(m.LocalOrders);Assert.IsNull(hud.SelectionPreview);yield return Frames(30);Mark("restarted","2048; no old selection or local overrides");CollectionAssert.AreEqual(plan,File.ReadAllBytes(planPath));yield return Menu();yield return Enter("forest-autumn22");Assert.AreEqual("forest-autumn22",session.CurrentEntryId);Assert.IsNull(m.LocalOrders);Assert.IsNull(hud.SelectionPreview);yield return Menu();Assert.AreEqual(source,EditorJsonUtility.ToJson(entry.config.flockingConfig));CollectionAssert.AreEqual(saved,File.ReadAllBytes(global));yield return FailedSceneRecovery();Mark("joint-session-complete","manual and Player/AOT acceptance remain pending");
  }
  IEnumerator FailedSceneRecovery(){var original=session.catalog;var clone=Object.Instantiate(original);var e=original.entries[0];var bad=new WarSandboxBattlefieldEntry{contentVersion=e.contentVersion,terrainId=e.terrainId,terrainVersion=e.terrainVersion,terrainSurface=e.terrainSurface,rules=e.rules};bad.id="p9-no-manager-fixture";bad.displayName="P9 owned failed scene";bad.scenePath="Assets/Game/Scenes/MainMenu.unity";clone.entries=original.entries.Concat(new[]{bad}).ToArray();session.catalog=clone;Assert.True(session.TryEnterBattlefield(bad.id,false,out var error),error);double until=Time.realtimeSinceStartupAsDouble+120;while(session.IsLoading&&Time.realtimeSinceStartupAsDouble<until)yield return null;Assert.False(session.IsLoading);Assert.AreEqual(WarSandboxEntryState.Failed,session.State);Assert.IsNotEmpty(session.Error);Assert.IsNull(session.Controller);yield return Frames();yield return Click("failure-return");yield return Loaded();Assert.AreEqual(WarSandboxEntryState.Menu,session.State);session.catalog=original;Object.Destroy(clone);yield return Enter("forest-green22");yield return Menu();Mark("scene-failure-ui-recovered","in-memory catalog points to no-manager scene; actual Failed screen return callback; successful official reload; no asset edits");}
  IEnumerator FixedGameView(){var asm=typeof(EditorWindow).Assembly;var sizesType=asm.GetType("UnityEditor.GameViewSizes");var singleton=typeof(ScriptableSingleton<>).MakeGenericType(sizesType);var sizes=singleton.GetProperty("instance",BindingFlags.Public|BindingFlags.Static).GetValue(null);var groupType=asm.GetType("UnityEditor.GameViewSizeGroupType");var group=sizesType.GetMethod("GetGroup").Invoke(sizes,new[]{Enum.Parse(groupType,"Standalone")});var gt=group.GetType();int index=(int)gt.GetMethod("GetBuiltinCount").Invoke(group,null)+(int)gt.GetMethod("GetCustomCount").Invoke(group,null);var sizeType=asm.GetType("UnityEditor.GameViewSize");var modeType=asm.GetType("UnityEditor.GameViewSizeType");var size=Activator.CreateInstance(sizeType,BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic,null,new object[]{Enum.Parse(modeType,"FixedResolution"),1280,720,"P9 owned 1280x720"},CultureInfo.InvariantCulture);gt.GetMethod("AddCustomSize").Invoke(group,new[]{size});var view=EditorWindow.GetWindow(asm.GetType("UnityEditor.GameView"));view.Show();view.Focus();view.GetType().GetProperty("selectedSizeIndex",BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).SetValue(view,index);yield return Frames(30);Assert.AreEqual(1280,Screen.width);Assert.AreEqual(720,Screen.height);Mark("fixed-render-size","1280x720; owned Editor preferences journaled by runner");}
  IEnumerator BackendReady(){double until=Time.realtimeSinceStartupAsDouble+75;while(TerrainNavigationRuntime.BurstReserveRequested&&Runtime.PreparationState=="Waiting"&&Time.realtimeSinceStartupAsDouble<until)yield return null;if(TerrainNavigationRuntime.BurstReserveRequested)Assert.AreEqual("Ready",Runtime.PreparationState,Runtime.PreparationBlockReason);else{Assert.AreEqual(0,Runtime.BurstSolveCount);Assert.AreEqual(0,WorkspaceCount());}}
  IEnumerator Sample(int repeat){var cam=m.cullingCamera;Assert.NotNull(cam);cam.transform.position=new Vector3(0,180,-120);cam.transform.LookAt(Vector3.zero);Vector3 p=cam.transform.position;Quaternion rotation=cam.transform.rotation;yield return Frames(90);yield return BackendReady();var rows=new List<string>{"frame,wall_ms,unity_allocated_bytes,unity_reserved_bytes,selection_bytes,local_bytes,readback_pairs,snapshot_requests,ack_requests,burst_solves,managed_solves"};double previous=Time.realtimeSinceStartupAsDouble;for(int i=0;i<300;i++){cam.transform.SetPositionAndRotation(p,rotation);yield return null;double now=Time.realtimeSinceStartupAsDouble;rows.Add(string.Join(",",i,F((now-previous)*1000),UnityEngine.Profiling.Profiler.GetTotalAllocatedMemoryLong(),UnityEngine.Profiling.Profiler.GetTotalReservedMemoryLong(),hud.SelectionPreview?.LogicalGpuBytes??0,m.LocalOrders?.GpuBytes??0,hud.SelectionPreview?.ReadbackPairs??0,m.LocalOrders?.SnapshotRequests??0,m.LocalOrders?.AckRequests??0,Runtime.BurstSolveCount,Runtime.ManagedSolveCount));previous=now;}File.WriteAllLines(Path.Combine(output,"repeat-"+repeat+"-frames.csv"),rows);Assert.AreEqual(2048,m.Buffers.AgentCount);if(TerrainNavigationRuntime.BurstReserveRequested)Assert.Greater(Runtime.BurstSolveCount,0,"Opt-in must actually execute native solves");else Assert.AreEqual(0,Runtime.BurstSolveCount);Mark("repeat-sampled",repeat+";300 wall-frame samples;fixed camera/settings;Editor not Player FPS qualification");}
  [UnityTest,Timeout(900000)]public IEnumerator P9Repeated2048ScopedFeedbackAndResourceRelease(){
   Assert.False(Application.isBatchMode,"Run performance in an owned rendered Editor, not batch/nographics");var gameView=EditorWindow.GetWindow(typeof(EditorWindow).Assembly.GetType("UnityEditor.GameView"));gameView.Show();gameView.Focus();yield return FixedGameView();var resources=new List<string>{"repeat,unity_allocated_after_unload,unity_reserved_after_unload,textures,rendertextures,materials,gameobjects,active_native_workspaces"};
   for(int run=1;run<=3;run++){yield return Enter();Assert.True(c.IssueOrder(ArmyOrder.Hold(0)));Assert.True(c.IssueOrder(ArmyOrder.Hold(1)));yield return Frames(90);yield return BackendReady();Assert.True(c.StartDefaultBattle());yield return Frames(60);Assert.True(c.IssueOrder(ArmyOrder.Hold(0)));Assert.True(c.IssueOrder(ArmyOrder.Hold(1)));yield return Frames();Mark("whole-navigation-warmup","repeat="+run+";burst="+Runtime.BurstSolveCount+";managed="+Runtime.ManagedSolveCount);yield return Four("repeat-"+run);yield return Sample(run);yield return Menu();resources.Add(string.Join(",",run,UnityEngine.Profiling.Profiler.GetTotalAllocatedMemoryLong(),UnityEngine.Profiling.Profiler.GetTotalReservedMemoryLong(),Resources.FindObjectsOfTypeAll<Texture>().Length,Resources.FindObjectsOfTypeAll<RenderTexture>().Length,Resources.FindObjectsOfTypeAll<Material>().Length,Resources.FindObjectsOfTypeAll<GameObject>().Length,WorkspaceCount()));File.WriteAllLines(Path.Combine(output,"repeat-resources.csv"),resources);}
   Mark("repeated-2048-complete","3 cycles;buffer/native ownership gates passed;frame/memory trends require report analysis, not automatic 30FPS claim");
  }
 }
}
#endif
