#if UNITY_EDITOR
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;
namespace MassEngine.Game.Tests {
 public sealed class P9FirstCommandTests {
  const BindingFlags P=BindingFlags.NonPublic|BindingFlags.Instance;
  LocalOrdersSceneTests owner;
  static string Output=>Environment.GetCommandLineArgs().FirstOrDefault(x=>x.StartsWith("--interaction-p8-output="))?.Substring("--interaction-p8-output=".Length);
  [UnitySetUp]public IEnumerator Setup(){if(Output==null)Assert.Ignore("Owned first-command diagnostics only");yield return null;}
  [UnityTearDown]public IEnumerator Cleanup(){if(owner!=null)yield return owner.Cleanup();}
  [UnityTest,Timeout(120000)]public IEnumerator IndependentSolversPreserveTopologyAndParallelResults(){int comparisons=0;for(int seed=0;seed<12;seed++){var rng=new System.Random(seed);int n=24;var h=new float[(n+1)*(n+1)];for(int i=0;i<h.Length;i++)h[i]=(float)rng.NextDouble()*.03f;var blocked=new bool[n*n];for(int i=0;i<blocked.Length;i++)blocked[i]=rng.NextDouble()<.08;var origin=seed%2==0?Vector2.zero:new Vector2(100000,-100000);var surface=new TerrainSurface("fork-test",1,n+1,n+1,origin,new Vector2(n,n),80,h,blocked);var obstacles=new[]{new StaticObstacleRect(origin+new Vector2(12,8),new Vector2(.2f,6))};float radius=seed%3*.05f;Func<TerrainNavigationGrid> make=()=>new TerrainNavigationGrid(surface,origin,1,n,n,radius,.1f,obstacles,.05f);var source=make();var a=source.CreateIndependentSolver();var b=source.CreateIndependentSolver();foreach(string name in new[]{"walkable","components","neighbours","edgeCosts","uniformOutputDirections"})Assert.AreSame(typeof(TerrainNavigationGrid).GetField(name,P).GetValue(source),typeof(TerrainNavigationGrid).GetField(name,P).GetValue(a),name);foreach(string name in new[]{"distances","nextCells","heap","heapPositions"}){Assert.AreNotSame(typeof(TerrainNavigationGrid).GetField(name,P).GetValue(source),typeof(TerrainNavigationGrid).GetField(name,P).GetValue(a));Assert.AreNotSame(typeof(TerrainNavigationGrid).GetField(name,P).GetValue(a),typeof(TerrainNavigationGrid).GetField(name,P).GetValue(b));}var points=Enumerable.Range(0,source.CellCount).Select(source.CellCenter).Where(source.IsWalkable).ToArray();Assert.Greater(points.Length,3);var goalsA=new[]{points[0],points[points.Length/2]};var goalsB=new[]{points.Last()};var expectedA=make().CreateFlowField(goalsA,.25f);var expectedB=make().CreateFlowField(goalsB,1.5f);var jobs=new[]{Task.Run(()=>source.CreateFlowField(goalsA,.25f)),Task.Run(()=>a.CreateFlowField(goalsB,1.5f)),Task.Run(()=>b.CreateFlowField(goalsA,.25f))};while(jobs.Any(x=>!x.IsCompleted))yield return null;CollectionAssert.AreEqual(expectedA,jobs[0].Result);CollectionAssert.AreEqual(expectedB,jobs[1].Result);CollectionAssert.AreEqual(expectedA,jobs[2].Result);CollectionAssert.AreEqual(source.CopyWalkable(),a.CopyWalkable());for(int i=0;i<source.CellCount;i++){var p=source.CellCenter(i);Assert.AreEqual(source.ComponentAt(p),a.ComponentAt(p));}comparisons+=3;}File.WriteAllText(Path.Combine(Output,"solver-sharing-tests.txt"),"12 terrain/obstacle/clearance/origin cases; 36 concurrent field comparisons; exact Vector2 equality; topology shared, scratch private.");}
  [UnityTest,Timeout(300000)]public IEnumerator SceneLifecycleAndExactRadiusSharing(){owner=new LocalOrdersSceneTests();yield return owner.Setup();yield return owner.P6GreenBridgeWholeArmyResetAndResourceBudget();var m=(MassEngineManager)typeof(LocalOrdersSceneTests).GetField("m",P).GetValue(owner);Assert.True(m.TryEnableLocalOrderPrototype(out var error),error);var r=m.LocalOrders.Submit(m.LocalOrders.Epoch,0,501,new[]{0,1,2,3},LocalOrderKind.Hold,Vector2.zero);double until=Time.realtimeSinceStartupAsDouble+20;while(r.GpuExecutingMembers==0&&Time.realtimeSinceStartupAsDouble<until)yield return null;Assert.AreEqual(4,r.GpuExecutingMembers,r.Error);var cache=(Dictionary<float,TerrainNavigationGrid>)typeof(LocalOrderChannel).GetField("cache",P).GetValue(m.LocalOrders);Assert.Greater(cache.Count,0);foreach(var row in cache){var field=typeof(TerrainNavigationGrid).GetField("walkable",P);if(row.Key==m.TerrainNavigation.Clearance)Assert.AreSame(field.GetValue(m.TerrainNavigation),field.GetValue(row.Value));else Assert.AreNotSame(field.GetValue(m.TerrainNavigation),field.GetValue(row.Value),"Different radius must not borrow a wider/narrower mask");Assert.AreNotSame(typeof(TerrainNavigationGrid).GetField("heap",P).GetValue(m.TerrainNavigation),typeof(TerrainNavigationGrid).GetField("heap",P).GetValue(row.Value));}File.WriteAllText(Path.Combine(Output,"scene-sharing.txt"),"plan_ms="+r.PlanMilliseconds+";base_clearance="+m.TerrainNavigation.Clearance+";local_radii="+string.Join(",",cache.Keys));}
  [UnityTest,Timeout(300000)]public IEnumerator ObstacleChangeStillInvalidates(){owner=new LocalOrdersSceneTests();yield return owner.Setup();yield return owner.P6FourGroupsGreen2048AndRealObstacleChange();}
 }
}
#endif
