using UnityEngine;
#if UNITY_EDITOR || DEVELOPMENT_BUILD
using System;using System.Collections;using System.Collections.Generic;using System.IO;using System.Linq;using UnityEngine.UI;
#endif
namespace MassEngine.Game {
 public sealed class Camera24PlayerSmoke:MonoBehaviour {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
  [Serializable]class Receipt {public bool passed,osInputTest=false,actorBindingsChecked;public string buildGuid,error,stage;public int units,framesTested;public float maximumStep,minimumClearance=99999,frameRateZoomDifference;public string[] checks;}
  Receipt r=new Receipt();List<string> checks=new List<string>();string output;MyCameraManager owner;BattlefieldCameraComfort24 control;Camera cam;Vector3 start;Quaternion rotation;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Install(){var args=Environment.GetCommandLineArgs();if(!args.Contains("--camera24-smoke"))return;var p=args.FirstOrDefault(a=>a.StartsWith("--terrain-output="));if(p==null){Application.Quit(2);return;}var go=new GameObject("Camera24 deterministic input smoke");DontDestroyOnLoad(go);go.AddComponent<Camera24PlayerSmoke>().output=p.Substring("--terrain-output=".Length);}
  static void Check(bool b,string s){if(!b)throw new Exception(s);}
  static Button B(string n)=>FindObjectsByType<Button>(FindObjectsSortMode.None).Single(b=>b.name==n&&b.gameObject.activeInHierarchy);
  IEnumerator Start(){Directory.CreateDirectory(output);r.buildGuid=Application.buildGUID;var e=Run();while(true){object n;try{if(!e.MoveNext())break;n=e.Current;}catch(Exception ex){r.error=ex.ToString();Finish(1);yield break;}yield return n;}r.passed=true;Finish(0);}
  void Finish(int code){r.checks=checks.ToArray();File.WriteAllText(Path.Combine(output,"receipt.json"),JsonUtility.ToJson(r,true));Debug.Log("CAMERA24_RESULT "+JsonUtility.ToJson(r));Application.Quit(code);}
  void Shot(string n){ScreenCapture.CaptureScreenshot(Path.Combine(output,n+".png"));}
  BattlefieldCameraComfort24.Frame Frame()=>new BattlefieldCameraComfort24.Frame{allowed=true,focused=true,dt=1f/60,screenHeight=Screen.height,mouse=new Vector2(Screen.width*.5f,Screen.height*.5f)};
  void Step(BattlefieldCameraComfort24.Frame f){var p=cam.transform.position;control.Step(f);float step=Vector3.Distance(p,cam.transform.position);r.framesTested++;r.maximumStep=Mathf.Max(r.maximumStep,step);float c=cam.transform.position.y-control.Floor(cam.transform.position);r.minimumClearance=Mathf.Min(r.minimumClearance,c);Check(CameraMotionSafety.IsFinite(cam.transform.position),"Nonfinite camera");Check(c>=control.RequiredClearance-.01f,"Camera below actual visual terrain at "+r.stage);Check(step<=control.LastMoveBudget+.02f,"Unbounded step "+step+" budget "+control.LastMoveBudget+" "+r.stage);Check(new Vector2(cam.transform.position.x,cam.transform.position.z).magnitude<=480.02f,"Outside horizontal envelope");Check(Vector3.Distance(cam.transform.position,control.envelope.center)<=720.05f,"Outside total envelope");}
  void Pose(Vector3 p,Quaternion q){control.CancelMotion();owner.ConstrainWorldPosition(p);cam.transform.rotation=q;control.Enforce();}
  void Done(string s){checks.Add(s);}
  IEnumerator Run(){r.stage="menu";yield return new WaitForSecondsRealtime(3);var session=WarSandboxSceneSession.Instance;B("home-play").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);B("card-0").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("card-0-enter").onClick.Invoke();float until=Time.realtimeSinceStartup+120;while(session.IsLoading&&Time.realtimeSinceStartup<until)yield return null;Check(session.State==WarSandboxEntryState.Battle,"Load failed");yield return new WaitForSecondsRealtime(1);var c=session.Controller;var d=c.GetComponent<WarSandboxRuntimeDeployment>();Check(d.IsEditing&&d.Draft[0].count+d.Draft[1].count==2048,"Default deployment changed");B("deployment-start").onClick.Invoke();yield return new WaitForSecondsRealtime(1);Check(c.Phase==WarSandboxBattlePhase.Running,"Battle not running");r.units=c.manager.scenarioConfig.unitTypes.Sum(u=>u.spawnConfig.unitCount);Check(r.units==2048,"Unexpected count");foreach(var u in c.manager.scenarioConfig.unitTypes){var rr=ResolvedUnitTypeRuntime.Resolve(u,1.5f);for(int k=0;k<3;k++){var m=rr.GetMaterial(k);Check(m!=null&&m.GetTexture("_BaseMap")!=null&&m.shader.isSupported,"Actor albedo missing");}}r.actorBindingsChecked=true;B("start").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);
   owner=FindFirstObjectByType<MyCameraManager>();control=owner.GetComponent<BattlefieldCameraComfort24>();Check(control!=null&&control.ground!=null,"Missing camera policy");cam=owner.ControlledCamera;control.SyntheticInput=true;start=cam.transform.position;rotation=cam.transform.rotation;Shot("01-overview");yield return new WaitForSecondsRealtime(.3f);
   r.stage="middle-start";var f=Frame();f.middle=f.middleDown=true;var before=cam.transform.position;Step(f);Check(Vector3.Distance(before,cam.transform.position)<.001f,"Press jumps");f.middleDown=false;f.mouse+=new Vector2(10,10);Step(f);Check(Vector3.Distance(before,cam.transform.position)>0&&Mathf.Abs(cam.transform.position.y-before.y)<.01f,"Pan should move horizontally");Done("Middle press zero step; pan horizontal and bounded");
   r.stage="pointer-warp";before=cam.transform.position;f.mouse+=new Vector2(9000,-9000);Step(f);Check(Vector3.Distance(before,cam.transform.position)<.001f&&control.RejectedPointerSpikes>0,"Warp accepted");Done("Pointer warp discarded and rebased");
   r.stage="blocked-reentry";f.allowed=false;Step(f);f.allowed=true;f.mouse=Frame().mouse;before=cam.transform.position;Step(f);Check(control.CurrentMode==BattlefieldCameraComfort24.DragMode.None&&Vector3.Distance(before,cam.transform.position)<.001f,"Held drag resurrected after UI");f=Frame();f.wheel=2;Step(f);f.focused=false;Step(f);Check(control.PendingZoom==0&&control.CurrentMode==BattlefieldCameraComfort24.DragMode.None,"Focus loss retained inertia");Done("UI/outside/focus cancellation; no stale held drag");
   r.stage="wheel-spike-in";Pose(start,rotation);f=Frame();for(int i=0;i<260;i++){f.wheel=1000;f.dt=i==10?3:1f/60;Step(f);yield return null;}Done("260 huge wheel-in events/stall remain above ground and bounded");Shot("02-near-ground-stop");yield return new WaitForSecondsRealtime(.3f);
   r.stage="wheel-spike-out";for(int i=0;i<320;i++){f.wheel=-1000;f.dt=1f/60;Step(f);yield return null;}Done("320 huge wheel-out events remain within world envelope");Shot("03-far-limit");yield return new WaitForSecondsRealtime(.3f);
   r.stage="frame-rate";var ends=new List<Vector3>();foreach(int hz in new[]{30,60,144}){Pose(start,rotation);f=Frame();f.dt=1f/hz;for(int i=0;i<hz*2;i++){f.wheel=i==0?1:0;Step(f);}ends.Add(cam.transform.position);}r.frameRateZoomDifference=ends.Max(p=>Vector3.Distance(p,ends[0]));Check(r.frameRateZoomDifference<.08f,"Frame rate dependent wheel");Done("30/60/144Hz one-notch endpoint agrees within 8cm");
   r.stage="low-slope-pan";Pose(new Vector3(-278,control.ground.Height(-278,-20)+6,-20),Quaternion.Euler(45,40,0));f=Frame();f.middle=f.middleDown=true;Step(f);f.middleDown=false;for(int i=0;i<180;i++){f.mouse+=new Vector2(2,1);Step(f);yield return null;}Done("Low-height pan across visual apron remains clear");
   r.stage="fly-descend";f=Frame();f.right=f.rightDown=true;Step(f);f.rightDown=false;f.keys=new Vector3(0,-1,1);f.shift=true;for(int i=0;i<160;i++){Step(f);yield return null;}Done("Fast diagonal fly/descend cannot cross terrain");Shot("04-low-flight");yield return new WaitForSecondsRealtime(.3f);
   r.stage="look-spike";f.keys=Vector3.zero;var oldRotation=cam.transform.rotation;f.mouse+=new Vector2(9000,9000);Step(f);Check(Quaternion.Angle(oldRotation,cam.transform.rotation)<.01f,"Look warp rotated camera");Done("Right-drag start and warp reset");
   r.stage="orbit";Pose(start,rotation);f=Frame();f.alt=f.left=f.leftDown=true;Step(f);Check(control.CurrentMode==BattlefieldCameraComfort24.DragMode.Orbit,"Orbit anchor not acquired");f.leftDown=false;for(int i=0;i<120;i++){f.mouse+=new Vector2(2,1);Step(f);yield return null;}Done("Alt orbit uses independent bounded pivot");
   r.stage="alt-dolly";f=Frame();f.alt=f.right=f.rightDown=true;Step(f);f.rightDown=false;for(int i=0;i<100;i++){f.mouse+=new Vector2(2,1);Step(f);yield return null;}Done("Alt-right dolly uses same bounded zoom");
   r.stage="invalid-input";f=Frame();f.mouse=new Vector2(float.NaN,float.PositiveInfinity);Step(f);f=Frame();f.wheel=float.PositiveInfinity;Step(f);Done("Nonfinite input ignored");
   r.stage="home";Pose(new Vector3(-120,80,-120),Quaternion.Euler(50,120,0));f=Frame();f.home=true;Step(f);f.home=false;for(int i=0;i<1000;i++){Step(f);if(Vector3.Distance(cam.transform.position,control.HomePosition)<.1f)break;yield return null;}Check(Vector3.Distance(cam.transform.position,control.HomePosition)<.1f,"Home did not return");Done("Home returns smoothly, manual input suppresses old follow");Shot("05-home-restored");yield return new WaitForSecondsRealtime(.5f);r.stage="complete";
  }
#endif
 }
}
