#if UNITY_EDITOR || DEVELOPMENT_BUILD
using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using System.Globalization;using System.Text;using UnityEngine;using UnityEngine.UI;
namespace MassEngine.Game {
public sealed class Contact34Probe:MonoBehaviour {
[Serializable]class PhaseRow {public string phase,order;public int gpuStance;public int alive,attacking,engaging,cohortAlive,contactCohortAlive;public float seconds,meanX,meanZ,meanSpeed,meanDisplacement,meanGoalProgress,contactGoalProgress;}
[Serializable]class Receipt {public bool passed,osInputTest=false;public string stage,error,buildGuid;public int units,positionChecks;public List<PhaseRow> phases=new List<PhaseRow>();}
Receipt r=new Receipt();string output,phase="load";WarSandboxBattleController c;AgentData[] agents;int[] teams;StreamWriter frames;Vector3[] start;bool[] cohort,contact;Vector3 goal;float phaseTime,nextSample;
[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Install(){var a=Environment.GetCommandLineArgs();if(!a.Contains("--contact34-probe"))return;var g=new GameObject("Contact34 isolated diagnostic");DontDestroyOnLoad(g);var p=g.AddComponent<Contact34Probe>();p.output=a.First(s=>s.StartsWith("--terrain-output=")).Substring(17);}
static void Check(bool b,string s){if(!b)throw new Exception(s);}static string F(float f)=>f.ToString("R",CultureInfo.InvariantCulture);static Button B(string n)=>FindObjectsByType<Button>(FindObjectsSortMode.None).Single(b=>b.name==n&&b.gameObject.activeInHierarchy);
IEnumerator Start(){r.buildGuid=Application.buildGUID;Directory.CreateDirectory(output);frames=new StreamWriter(Path.Combine(output,"frames.csv"));frames.WriteLine("phase,t,id,team,x,z,vx,vz,state");var stack=new Stack<IEnumerator>();stack.Push(Run());while(stack.Count>0){bool moved;object next;try{moved=stack.Peek().MoveNext();next=moved?stack.Peek().Current:null;}catch(Exception ex){r.error=ex.ToString();Finish(1);yield break;}if(!moved){stack.Pop();continue;}if(next is IEnumerator e)stack.Push(e);else yield return next;}r.passed=true;Finish(0);}
void Finish(int code){frames?.Dispose();File.WriteAllText(Path.Combine(output,"receipt.json"),JsonUtility.ToJson(r,true));Debug.Log("CONTACT34_RESULT "+JsonUtility.ToJson(r));Application.Quit(code);}
void Read(bool record=true){c.manager.Buffers.agentBuffer.GetData(agents);for(int i=0;i<agents.Length;i++){var a=agents[i];if(a.currentState!=4){Check(c.manager.TerrainNavigation.IsWalkable(new Vector2(a.position.x,a.position.z)),"Blocked cell id="+i+" position="+a.position);r.positionChecks++;}if(record)frames.WriteLine(phase+","+F(Time.realtimeSinceStartup-phaseTime)+","+i+","+teams[i]+","+F(a.position.x)+","+F(a.position.z)+","+F(a.velocity.x)+","+F(a.velocity.z)+","+a.currentState);}}
int ContactCount()=>Enumerable.Range(0,agents.Length).Count(i=>teams[i]==0&&agents[i].currentState==3);
void Begin(string name,Vector3 target){Read(false);phase=r.stage=name;goal=target;phaseTime=Time.realtimeSinceStartup;nextSample=0;start=agents.Select(a=>a.position).ToArray();cohort=Enumerable.Range(0,agents.Length).Select(i=>teams[i]==0&&agents[i].currentState!=4).ToArray();contact=Enumerable.Range(0,agents.Length).Select(i=>cohort[i]&&agents[i].currentState==3).ToArray();Read();}
void End(){Read();var row=new PhaseRow{phase=phase,order=c.GetArmy(0).currentOrder.type.ToString(),seconds=Time.realtimeSinceStartup-phaseTime};for(int i=0;i<agents.Length;i++)if(teams[i]==0&&agents[i].currentState!=4){var a=agents[i];row.alive++;row.meanX+=a.position.x;row.meanZ+=a.position.z;row.meanSpeed+=new Vector2(a.velocity.x,a.velocity.z).magnitude;if(a.currentState==3)row.attacking++;if(a.currentState==2)row.engaging++;if(cohort[i]){row.cohortAlive++;row.meanDisplacement+=Vector2.Distance(new Vector2(start[i].x,start[i].z),new Vector2(a.position.x,a.position.z));float progress=Vector2.Distance(new Vector2(start[i].x,start[i].z),new Vector2(goal.x,goal.z))-Vector2.Distance(new Vector2(a.position.x,a.position.z),new Vector2(goal.x,goal.z));row.meanGoalProgress+=progress;if(contact[i]){row.contactCohortAlive++;row.contactGoalProgress+=progress;}}}row.meanX/=Math.Max(1,row.alive);row.meanZ/=Math.Max(1,row.alive);row.meanSpeed/=Math.Max(1,row.alive);row.meanDisplacement/=Math.Max(1,row.cohortAlive);row.meanGoalProgress/=Math.Max(1,row.cohortAlive);row.contactGoalProgress/=Math.Max(1,row.contactCohortAlive);int[] stances=new int[c.manager.Buffers.teamStanceBuffer.count];c.manager.Buffers.teamStanceBuffer.GetData(stances);row.gpuStance=stances[0];r.phases.Add(row);frames.Flush();File.WriteAllText(Path.Combine(output,"progress.json"),JsonUtility.ToJson(r,true));}
IEnumerator Observe(float seconds){float first=Time.realtimeSinceStartup;int frame=Time.frameCount;while(Time.realtimeSinceStartup-first<seconds){Check(c.Phase==WarSandboxBattlePhase.Running,"Battle ended during "+phase+"; actual="+c.Phase+" result="+JsonUtility.ToJson(c.BattleResult));float t=Time.realtimeSinceStartup-first;if(t>10)Check((Time.frameCount-frame)/t>=10,"Under10fps stop");if(t>=nextSample){Read();nextSample=t+.5f;}yield return null;}End();}
IEnumerator AwaitContact(string name,float timeout){Begin(name,Vector3.zero);float limit=Time.realtimeSinceStartup+timeout;while(Time.realtimeSinceStartup<limit){yield return new WaitForSecondsRealtime(.5f);Read();Check(c.Phase==WarSandboxBattlePhase.Running,"Battle ended before contact");if(ContactCount()>=20){End();yield break;}}throw new Exception("No sustained attacking contact within "+timeout+"s");}
IEnumerator Run(){r.stage="load";yield return new WaitForSecondsRealtime(3);var session=WarSandboxSceneSession.Instance;B("home-play").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);B("card-0").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);B("card-0-enter").onClick.Invoke();float limit=Time.realtimeSinceStartup+120;while(session.IsLoading&&Time.realtimeSinceStartup<limit)yield return null;yield return new WaitForSecondsRealtime(.6f);Check(session.State==WarSandboxEntryState.Battle&&!session.HelpOpen,"Load failed");c=session.Controller;var d=c.GetComponent<WarSandboxRuntimeDeployment>();Check(d.IsEditing&&d.Draft.Snapshot().Sum(e=>e.count)==2048&&c.manager.systemConfig.runtimeFlowConfig.terrainLaneApproach33,"Default33 configuration changed");B("deployment-start").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(c.Phase==WarSandboxBattlePhase.Running&&!d.IsEditing&&c.manager.TerrainGpuAllocated,"Start failed");r.units=c.manager.Buffers.AgentCount;Check(r.units==2048,"Count changed");agents=new AgentData[r.units];teams=new int[r.units];c.manager.Buffers.combatBuffers.teamIdBuffer.GetData(teams);
yield return AwaitContact("approach",120);Begin("contact",Vector3.zero);yield return Observe(3);
string kind=Environment.GetCommandLineArgs().First(x=>x.StartsWith("--contact34-case=")).Substring("--contact34-case=".Length);
var target=kind=="retreat"?c.GetArmy(0).spawnCenter:new Vector3(-100,0,55);Begin(kind,target);
if(kind=="hold")Check(c.IssueOrder(ArmyOrder.Hold(0)),"Hold rejected");
else if(kind=="move")Check(c.IssueMoveOrder(0,target,false),"Move rejected");
else if(kind=="retreat")Check(c.IssueOrder(ArmyOrder.Retreat(0)),"Retreat rejected");else throw new Exception("Unknown case "+kind);
yield return Observe(8);
if(Environment.GetCommandLineArgs().Contains("--contact34-assert")){var row=r.phases.Last();if(kind=="hold"){Check(row.gpuStance==4,"Hold stance not uploaded");Check(row.meanDisplacement<2,"Hold excessive displacement");}else{Check(row.gpuStance==3,"MoveOnly stance not uploaded");Check(row.attacking==0&&row.engaging==0,"Explicit movement still fighting");Check(row.meanGoalProgress>6,"Army not approaching goal");Check(row.contactCohortAlive>=5&&row.contactGoalProgress>4,"Contact cohort did not disengage");}}
Check(c.IssueOrder(ArmyOrder.Attack(0)),"Final attack rejected");Begin("attack_again",Vector3.zero);yield return Observe(4);if(Environment.GetCommandLineArgs().Contains("--contact34-assert")){var row=r.phases.Last();Check(row.gpuStance==1&&row.attacking>0,"Attack did not resume real combat");}c.PauseBattle();r.stage="complete";
}
}}
#endif
