#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using System.Globalization;using System.Text;using UnityEngine;using UnityEngine.UI;using UnityEngine.Rendering;
namespace MassEngine.Game {
public sealed class Contact35Probe:MonoBehaviour {
[Serializable]class Receipt{public bool passed,osInputTest=false;public string stage,error,phaseAtEnd;public int units,frames,cohort,positionChecks,captureRequests;public float elapsed,averageFps;public Vector3 originalCameraPosition,originalCameraEuler,diagnosticCameraPosition;}
Receipt r=new Receipt();string output;WarSandboxBattleController c;AgentData[] agents;int[] teams,targets,hp,slots,selected;StreamWriter csv;float start;Camera camera;MyCameraManager controls;
[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Install(){var a=Environment.GetCommandLineArgs();if(!a.Contains("--contact35-probe"))return;var go=new GameObject("Contact35 read-only observation");DontDestroyOnLoad(go);var p=go.AddComponent<Contact35Probe>();p.output=a.First(x=>x.StartsWith("--terrain-output=")).Substring(17);}
static void Check(bool b,string s){if(!b)throw new Exception(s);}static string F(float x)=>x.ToString("R",CultureInfo.InvariantCulture);static Button B(string n)=>FindObjectsByType<Button>(FindObjectsSortMode.None).Single(b=>b.name==n&&b.gameObject.activeInHierarchy);
IEnumerator Start(){Directory.CreateDirectory(output);var stack=new Stack<IEnumerator>();stack.Push(Run());while(stack.Count>0){bool moved;object next;try{moved=stack.Peek().MoveNext();next=moved?stack.Peek().Current:null;}catch(Exception ex){r.error=ex.ToString();Finish(1);yield break;}if(!moved){stack.Pop();continue;}if(next is IEnumerator e)stack.Push(e);else yield return next;}r.passed=true;Finish(0);}
void Finish(int code){csv?.Dispose();if(camera!=null){camera.transform.position=r.originalCameraPosition;camera.transform.eulerAngles=r.originalCameraEuler;}if(controls!=null)controls.enabled=true;File.WriteAllText(Path.Combine(output,"receipt.json"),JsonUtility.ToJson(r,true));Debug.Log("CONTACT35_RESULT "+JsonUtility.ToJson(r));Application.Quit(code);}
void Read(){c.manager.Buffers.agentBuffer.GetData(agents);for(int i=0;i<agents.Length;i++)if(agents[i].currentState!=4){Check(c.manager.TerrainNavigation.IsWalkable(new Vector2(agents[i].position.x,agents[i].position.z)),"Blocked cell id="+i);r.positionChecks++;}}
void Snapshot(string name){var s=new StringBuilder("id,team,x,y,z,state,presentation,yaw,speed\n");for(int i=0;i<agents.Length;i++){var a=agents[i];s.Append(i).Append(',').Append(teams[i]).Append(',').Append(F(a.position.x)).Append(',').Append(F(a.position.y)).Append(',').Append(F(a.position.z)).Append(',').Append(a.currentState).Append(',').Append(a.presentationState).Append(',').Append(F(a.rotation.y)).Append(',').Append(F(a.locomotionSpeed)).Append('\n');}File.WriteAllText(Path.Combine(output,name+".csv"),s.ToString());}
void Record(){var cb=c.manager.Buffers.combatBuffers;cb.targetAgentIndexBuffer.GetData(targets);cb.hpReadBuffer.GetData(hp);cb.engagementSlotAssignmentBuffer.GetData(slots);float t=Time.realtimeSinceStartup-start;var s=new StringBuilder();foreach(int i in selected){var a=agents[i];int target=targets[i],b=r.units+i*12;float distance=target>=0&&target<agents.Length?Vector3.Distance(a.position,agents[target].position):-1;s.Append(r.frames).Append(',').Append(F(t)).Append(',').Append(i).Append(',').Append(teams[i]).Append(',').Append(F(a.position.x)).Append(',').Append(F(a.position.z)).Append(',').Append(F(a.velocity.x)).Append(',').Append(F(a.velocity.z)).Append(',').Append(F(a.rotation.y)).Append(',').Append(a.currentState).Append(',').Append(a.presentationState).Append(',').Append(F(a.locomotionSpeed)).Append(',').Append(target).Append(',').Append(F(distance)).Append(',').Append(hp[i]).Append(',').Append(slots[i]).Append(',').Append(F(BitConverter.Int32BitsToSingle(slots[b+5]))).Append(',').Append(F(BitConverter.Int32BitsToSingle(slots[b+7]))).Append('\n');}csv.Write(s.ToString());r.frames++;}
void CaptureView(string path){var rt=RenderTexture.GetTemporary(1280,720,24,RenderTextureFormat.ARGB32);var previous=RenderTexture.active;Texture2D image=null;try{var request=new RenderPipeline.StandardRequest{destination=rt};Check(RenderPipeline.SupportsRenderRequest(camera,request),"Standard render request unavailable");RenderPipeline.SubmitRenderRequest(camera,request);RenderTexture.active=rt;image=new Texture2D(1280,720,TextureFormat.RGB24,false);image.ReadPixels(new Rect(0,0,1280,720),0,0);image.Apply();File.WriteAllBytes(path,image.EncodeToPNG());}finally{RenderTexture.active=previous;if(image!=null)Destroy(image);RenderTexture.ReleaseTemporary(rt);}}
IEnumerator Run(){r.stage="load";yield return new WaitForSecondsRealtime(3);var session=WarSandboxSceneSession.Instance;B("home-play").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);B("card-0").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);B("card-0-enter").onClick.Invoke();float deadline=Time.realtimeSinceStartup+120;while(session.IsLoading&&Time.realtimeSinceStartup<deadline)yield return null;yield return new WaitForSecondsRealtime(.6f);Check(session.State==WarSandboxEntryState.Battle&&!session.HelpOpen,"Load failed");c=session.Controller;var d=c.GetComponent<WarSandboxRuntimeDeployment>();Check(d.IsEditing&&d.Draft.Snapshot().Sum(e=>e.count)==2048,"Default count changed");B("deployment-start").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(c.Phase==WarSandboxBattlePhase.Running&&c.manager.TerrainGpuAllocated,"Start failed");r.units=c.manager.Buffers.AgentCount;Check(r.units==2048,"Count changed");agents=new AgentData[r.units];teams=new int[r.units];targets=new int[r.units];hp=new int[r.units];slots=new int[c.manager.Buffers.combatBuffers.engagementSlotAssignmentBuffer.count];c.manager.Buffers.combatBuffers.teamIdBuffer.GetData(teams);
r.stage="approach";deadline=Time.realtimeSinceStartup+120;bool found=false;while(Time.realtimeSinceStartup<deadline){yield return new WaitForSecondsRealtime(.5f);Read();Check(c.Phase==WarSandboxBattlePhase.Running,"Ended before contact");if(Enumerable.Range(0,r.units).Count(i=>teams[i]==0&&agents[i].currentState==3)>=20){found=true;break;}}Check(found,"No contact");
var ids=Enumerable.Range(0,r.units).Where(i=>agents[i].currentState!=4&&Mathf.Abs(agents[i].position.z)<24).ToArray();selected=new[]{0,1}.SelectMany(team=>new[]{3,2,1}.SelectMany(state=>ids.Where(i=>teams[i]==team&&agents[i].currentState==state).OrderBy(i=>Mathf.Abs(agents[i].position.x)).Take(32))).Distinct().ToArray();r.cohort=selected.Length;Check(r.cohort>=64,"Insufficient tracked cohort");Snapshot("contact-start");
controls=FindFirstObjectByType<MyCameraManager>();Check(controls!=null&&controls.MainCamera!=null,"No camera");camera=controls.MainCamera;r.originalCameraPosition=camera.transform.position;r.originalCameraEuler=camera.transform.eulerAngles;ScreenCapture.CaptureScreenshot(Path.Combine(output,"default-view.png"));yield return new WaitForSecondsRealtime(.3f);controls.enabled=false;var contactIds=ids.Where(i=>agents[i].currentState==3).ToArray();Vector3 focus=Vector3.zero;foreach(int i in contactIds)focus+=agents[i].position;focus/=Math.Max(1,contactIds.Length);camera.transform.position=focus-camera.transform.forward*45;r.diagnosticCameraPosition=camera.transform.position;
csv=new StreamWriter(Path.Combine(output,"motion.csv"));csv.WriteLine("frame,t,id,team,x,z,vx,vz,yaw,state,presentation,speed,target,targetDistance,hp,slot,waiting,rangedStatus");r.stage="natural-contact";start=Time.realtimeSinceStartup;float nextCapture=0;while(Time.realtimeSinceStartup-start<12){Read();Record();float elapsed=Time.realtimeSinceStartup-start;if(elapsed>=nextCapture){CaptureView(Path.Combine(output,"view-"+r.captureRequests.ToString("D3")+".png"));r.captureRequests++;nextCapture=elapsed+.25f;}if(elapsed>3)Check(r.frames/elapsed>=10,"Under10fps; stop observation");if(c.Phase!=WarSandboxBattlePhase.Running)break;yield return null;}r.elapsed=Time.realtimeSinceStartup-start;r.averageFps=r.frames/Mathf.Max(.001f,r.elapsed);r.phaseAtEnd=c.Phase.ToString();Snapshot("contact-end");csv.Flush();yield return new WaitForSecondsRealtime(.5f);Check(Directory.GetFiles(output,"view-*.png").Length>=8,"Missing visual sequence");c.PauseBattle();r.stage="complete";
}
}}
#endif
