using UnityEngine;
#if UNITY_EDITOR || DEVELOPMENT_BUILD
using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using UnityEngine.UI;
#endif
namespace MassEngine.Game {
 public sealed class Deploy32PlayerSmoke:MonoBehaviour {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
 [Serializable]class Receipt{public bool passed,osInputTest=false;public string stage,error,buildGuid;public string[] checks;}
 Receipt r=new Receipt();List<string> checks=new List<string>();string output;WarSandboxRuntimeDeployment d;WarSandboxBattleController c;
 [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Install(){var a=Environment.GetCommandLineArgs();if(!a.Contains("--deploy32-smoke"))return;var g=new GameObject("Deploy32 isolated smoke");DontDestroyOnLoad(g);g.AddComponent<Deploy32PlayerSmoke>().output=a.First(x=>x.StartsWith("--terrain-output=")).Substring("--terrain-output=".Length);}
 static void Check(bool b,string e){if(!b)throw new Exception(e);}
 static Button B(string n){var b=FindObjectsByType<Button>(FindObjectsSortMode.None).SingleOrDefault(b=>b.name==n&&b.gameObject.activeInHierarchy);Check(b!=null,"Missing button "+n);return b;}
 static bool Visible(string n)=>GameObject.Find(n)!=null;
 static Text T(string n){var g=GameObject.Find(n);Check(g!=null,"Missing text object "+n);var t=g.GetComponentInChildren<Text>();Check(t!=null,"Missing text on "+n);return t;}
 static InputField Field(string n)=>FindObjectsByType<InputField>(FindObjectsSortMode.None).Single(f=>f.name==n&&f.gameObject.activeInHierarchy);
 void Shot(string n)=>ScreenCapture.CaptureScreenshot(Path.Combine(output,n+".png"));
 void Fit(){var t=T("deployment-validation");Check(t.preferredHeight<=t.rectTransform.rect.height+2,"Validation text clipped");}
 void Blocked(ScenarioConfig scenario){Check(d.IsEditing&&c.Phase==WarSandboxBattlePhase.Setup&&c.manager.scenarioConfig==scenario,"Invalid attempt applied/started/replaced scenario");}
 IEnumerator Start(){Directory.CreateDirectory(output);r.buildGuid=Application.buildGUID;var stack=new Stack<IEnumerator>();stack.Push(Run());while(stack.Count>0){bool moved;object next;try{moved=stack.Peek().MoveNext();next=moved?stack.Peek().Current:null;}catch(Exception ex){r.error=ex.ToString();Finish(1);yield break;}if(!moved){stack.Pop();continue;}if(next is IEnumerator e)stack.Push(e);else yield return next;}r.passed=true;Finish(0);}
 void Finish(int code){r.checks=checks.ToArray();File.WriteAllText(Path.Combine(output,"receipt.json"),JsonUtility.ToJson(r,true));Debug.Log("DEPLOY32_RESULT "+JsonUtility.ToJson(r));Application.Quit(code);}
 IEnumerator Run(){
  r.stage="load";yield return new WaitForSecondsRealtime(3);var session=WarSandboxSceneSession.Instance;bool winter=Environment.GetCommandLineArgs().Contains("--winter");B("home-play").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);int season=winter?2:0;B("card-"+season).onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("card-"+season+"-enter").onClick.Invoke();float end=Time.realtimeSinceStartup+120;while(session.IsLoading&&Time.realtimeSinceStartup<end)yield return null;yield return new WaitForSecondsRealtime(.7f);
  Check(session.State==WarSandboxEntryState.Battle&&!session.HelpOpen,"Load/isolated guide suppression failed");c=session.Controller;d=c.GetComponent<WarSandboxRuntimeDeployment>();var hud=c.GetComponent<WarSandboxDeploymentHUD>();Check(DeploymentCheck32.Active(d)&&RosterInfo31.Active(d)&&d.IsEditing,"Not opt-in32");Check(d.Draft.Snapshot().Sum(e=>e.count)==2048,"Not default2048");d.PlanStore=new WarSandboxLocalPlanStore(Path.Combine(output,"isolated-plans"));Check(d.TrySavePlan("KEEP32","Keep unchanged",false,out var error),error);var files=Directory.GetFiles(d.PlanStore.DirectoryPath).ToDictionary(p=>p,p=>File.ReadAllBytes(p));
  Check(T("deployment-validation").text.Contains("开战会自动应用")&&!Visible("deployment-fix32"),"Default explanation/locator wrong");Fit();Shot("01-ready");yield return new WaitForSecondsRealtime(.3f);
  if(winter){r.stage="untouched-default-start";B("deployment-start").onClick.Invoke();yield return new WaitForSecondsRealtime(.4f);Check(!d.IsEditing&&c.Phase==WarSandboxBattlePhase.Running&&c.GetArmy(0).initialUnitCount+c.GetArmy(1).initialUnitCount==2048&&!Visible("tight-dialog-confirm"),"Legal default did not start directly");c.PauseBattle();c.ResetBattle();yield return new WaitForSecondsRealtime(.3f);hud.RequestEdit();yield return new WaitForSecondsRealtime(.4f);Check(d.IsEditing&&!hud.Confirming,"Default reset to setup failed");checks.Add("Untouched default2048 starts in one click without extra confirmation");}
  var scenario=c.manager.scenarioConfig;var original0=d.Draft[0];var original1=d.Draft[1];
  r.stage="boundary";var bad=original1;bad.center.x=999;d.Draft.Set(1,bad);yield return new WaitForSecondsRealtime(.3f);Check(T("deployment-validation").text.Contains("守方 · 编成 02")&&T("deployment-validation").text.Contains("越出"),"Boundary problem scope wrong");Fit();string invalid=PlanState28.For(c).Current;B("deployment-start").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Blocked(scenario);B("deployment-apply").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Blocked(scenario);Check(PlanState28.For(c).Current==invalid,"Rejected actions changed draft");B("deployment-fix32").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(!hud.LegionOpen&&T("placement-unit").text.Contains("守方 · 编成 02")&&Field("input-x").text=="999","Boundary locator selected wrong editor");Check(PlanState28.For(c).Current==invalid,"Locator changed configuration");Fit();Shot("02-boundary-location");yield return new WaitForSecondsRealtime(.3f);Field("input-x").text=original1.center.x.ToString(System.Globalization.CultureInfo.InvariantCulture);B("field-update").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(d.TryValidate(out error),error);Check(!Visible("deployment-fix32")&&T("deployment-validation").text.Contains("校验通过"),"Fixed problem still stale");
  r.stage="overlap";bad=d.Draft[1];bad.center=original0.center;d.Draft.Set(1,bad);yield return new WaitForSecondsRealtime(.3f);Check(T("deployment-validation").text.Contains("守方 · 编成 02")&&T("deployment-validation").text.Contains("重叠"),"Overlap not attributed");B("deployment-fix32").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(T("placement-unit").text.Contains("编成 02"),"Overlap locator wrong");Fit();Shot("03-overlap");yield return new WaitForSecondsRealtime(.3f);B("roster-undo").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(d.TryValidate(out error)&&!Visible("deployment-fix32"),"Undo did not refresh readiness");checks.Add("Boundary/overlap retain existing rejection; apply/start do not allocate; exact army/formation locator preserves draft; correction and Undo refresh status");
  r.stage="invalid-input";Field("input-x").text="NaN";B("deployment-start").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Blocked(scenario);Check(d.Draft[1].center==original1.center&&T("deployment-validation").text.Contains("输入尚未写入"),"Nonfinite input leaked into draft");B("deployment-fix32").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(Field("input-x").text=="NaN","Locator discarded pending text");Fit();Field("input-x").text=original1.center.x.ToString(System.Globalization.CultureInfo.InvariantCulture);B("field-update").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);
  r.stage="count-location";bad=d.Draft[1];bad.count=0;d.Draft.Set(1,bad);yield return new WaitForSecondsRealtime(.3f);Check(T("deployment-validation").text.Contains("人数"),"Draft count error missing");B("deployment-fix32").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);
  Check(hud.LegionOpen&&T("legion-name").text.Contains("守方")&&Field("input-count").text=="0","Count locator did not expose invalid input");B("legion-update-count").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(d.Draft[1].count==0,"Rejected count changed draft");B("deployment-fix32").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(Field("input-count").text=="0","Count input discarded");Fit();Shot("04-count-input");yield return new WaitForSecondsRealtime(.3f);Field("input-count").text="900";B("legion-done").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(d.Draft[1].count==900&&d.Draft[0].Equals(original0)&&d.TryValidate(out error),"Count correction changed other formation or remains invalid");Check(T("deployment-validation").text.Contains("尚未应用")&&T("deployment-start").text.Contains("应用并开战"),"Changed/applied distinction unclear");checks.Add("Nonfinite and nonpositive inputs remain uncommitted/recoverable; count locator uses correct legion; corrected draft is marked unapplied");
  r.stage="unknown-diagnostic";Check(DeploymentCheck32.Index("总兵力不能超过限制。",d.Draft)==-1&&DeploymentCheck32.Index("编成 999：无效",d.Draft)==-1,"Invented target for global/unknown error");
  r.stage="apply-start";
  if(!winter){B("deployment-apply").onClick.Invoke();yield return new WaitForSecondsRealtime(.5f);Check(!d.IsEditing&&c.Phase==WarSandboxBattlePhase.Setup&&PlanState28.For(c).Applied,"Apply unexpectedly started or failed");Check(c.GetArmy(1).initialUnitCount==900&&T("setup-note").text.Contains("已应用到本局"),"Applied state/count not synchronized");Shot("05-applied-setup");yield return new WaitForSecondsRealtime(.3f);B("edit").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(d.IsEditing&&!PlanState28.For(c).DraftChanged&&T("deployment-validation").text.Contains("与本局已应用配置一致"),"Reopen applied state wrong");B("deployment-cancel").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(c.GetArmy(1).initialUnitCount==900,"Cancel lost applied count");B("start").onClick.Invoke();}
  else B("deployment-start").onClick.Invoke();
  yield return new WaitForSecondsRealtime(.5f);Check(!d.IsEditing&&c.Phase==WarSandboxBattlePhase.Running&&c.GetArmy(1).initialUnitCount==900&&!Visible("tight-dialog-confirm")&&!hud.Confirming,"Corrected deployment failed to start directly");Check(c.manager.Buffers!=null&&c.manager.Buffers.IsAllocated,"No GPU allocation");Shot("06-running");yield return new WaitForSecondsRealtime(.3f);c.PauseBattle();foreach(var f in files)Check(File.ReadAllBytes(f.Key).SequenceEqual(f.Value),"Apply/start changed saved plan");Check(Directory.GetFiles(d.PlanStore.DirectoryPath).Length==files.Count,"Unexpected autosave");checks.Add(winter?"Corrected draft applies and starts in one click, applied count900 is used, no extra dialog":"Apply alone stays Setup with actual count900 and applied status; reopen/cancel preserves it; existing start enters Running");checks.Add("GPU buffers allocated; original saved plan bytes unchanged; no autosave");r.stage="complete";
 }
#endif
 }
}
