using UnityEngine;
#if UNITY_EDITOR || DEVELOPMENT_BUILD
using System;using System.Collections;using System.Collections.Generic;using System.IO;using System.Linq;using UnityEngine.UI;
#endif
namespace MassEngine.Game {
 public sealed class Details26PlayerSmoke:MonoBehaviour {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
 [Serializable]class Receipt{public bool passed,osInputTest=false;public string stage,error,buildGuid;public int units,accepted,rejected;public string[] checks;}
 Receipt r=new Receipt();List<string> checks=new List<string>();string output;
 [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Install(){var args=Environment.GetCommandLineArgs();if(!args.Contains("--details26-smoke"))return;var p=args.FirstOrDefault(a=>a.StartsWith("--terrain-output="));if(p==null){Application.Quit(2);return;}var go=new GameObject("Details26 input-path smoke");DontDestroyOnLoad(go);go.AddComponent<Details26PlayerSmoke>().output=p.Substring("--terrain-output=".Length);}
 static void Check(bool ok,string text){if(!ok)throw new Exception(text);}
 static Button B(string n)=>FindObjectsByType<Button>(FindObjectsSortMode.None).Single(b=>b.name==n&&b.gameObject.activeInHierarchy);
 static string Text(string n)=>GameObject.Find(n).GetComponentInChildren<Text>().text;
 void Shot(string n)=>ScreenCapture.CaptureScreenshot(Path.Combine(output,n+".png"));
 IEnumerator Start(){Directory.CreateDirectory(output);r.buildGuid=Application.buildGUID;var e=Run();while(true){object n;try{if(!e.MoveNext())break;n=e.Current;}catch(Exception ex){r.error=ex.ToString();Finish(1);yield break;}yield return n;}r.passed=true;Finish(0);}
 void Finish(int code){r.checks=checks.ToArray();File.WriteAllText(Path.Combine(output,"receipt.json"),JsonUtility.ToJson(r,true));Debug.Log("DETAILS26_RESULT "+JsonUtility.ToJson(r));Application.Quit(code);}
 IEnumerator Run(){r.stage="load";yield return new WaitForSecondsRealtime(3);var session=WarSandboxSceneSession.Instance;B("home-play").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);int idx=Environment.GetCommandLineArgs().Contains("--winter")?2:0;B("card-"+idx).onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);B("card-"+idx+"-enter").onClick.Invoke();float end=Time.realtimeSinceStartup+120;while(session.IsLoading&&Time.realtimeSinceStartup<end)yield return null;Check(session.State==WarSandboxEntryState.Battle,"Load failed");yield return new WaitForSecondsRealtime(1);var c=session.Controller;var d=c.GetComponent<WarSandboxRuntimeDeployment>();Check(d.IsEditing&&d.Draft[0].count+d.Draft[1].count==2048,"Default count changed");B("deployment-start").onClick.Invoke();yield return new WaitForSecondsRealtime(.4f);Check(c.Phase==WarSandboxBattlePhase.Running,"Start failed");B("start").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);var hud=c.GetComponent<WarSandboxCommandHUD>();var f=c.GetComponent<CommandFeedback25>();Check(f!=null,"Missing feedback");r.units=c.manager.scenarioConfig.unitTypes.Sum(u=>u.spawnConfig.unitCount);Check(r.units==2048,"Count");Check(FindFirstObjectByType<BattlefieldCameraComfort24>()!=null,"Camera24 lost");foreach(var u in c.manager.scenarioConfig.unitTypes){var resolved=ResolvedUnitTypeRuntime.Resolve(u,1.5f);for(int k=0;k<3;k++)Check(resolved.GetMaterial(k)!=null&&resolved.GetMaterial(k).GetTexture("_BaseMap")!=null,"Actor texture missing");}
 r.stage="selection";var old=c.SelectedArmy.currentOrder;B("move").onClick.Invoke();Check(hud.AwaitingMove25,"Move didn't arm");B("team-select-1").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(!hud.AwaitingMove25&&c.selectedTeam==1&&c.Phase==WarSandboxBattlePhase.Paused,"Selection should cancel only picking, not resume");Check(Text("order-status").Contains("全阵营"),"Missing scope");B("team-select-0").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(c.SelectedArmy.currentOrder.type==old.type,"Selection changed command");checks.Add("Selection scope explicit; switch cancels pending pick without order/phase mutation");Shot("01-selection");yield return new WaitForSecondsRealtime(.3f);
 r.stage="rejected";B("move").onClick.Invoke();Check(!hud.TestMove25(new Vector3(9000,0,9000)),"Invalid target accepted");yield return new WaitForSecondsRealtime(.3f);Check(f.Rejected&&f.Accepted==0&&!f.HasTarget&&c.Phase==WarSandboxBattlePhase.Paused&&c.SelectedArmy.currentOrder.type==old.type,"Rejected receipt mutated state");Check(Text("feedback-text").Contains("未下达"),"Missing reject reason");checks.Add("Invalid move shows failure, no marker/order replacement/resume");Shot("02-rejected");yield return new WaitForSecondsRealtime(.3f);
 r.stage="move";Check(hud.TestMove25(Vector3.zero),"Valid move rejected");yield return new WaitForSecondsRealtime(.25f);Check(f.Accepted==1&&!f.Rejected&&f.HasTarget&&c.Phase==WarSandboxBattlePhase.Running&&Text("feedback-text").Contains("战斗已恢复"),"Move receipt not authoritative");Check(c.SelectedArmy.currentOrder.type==ArmyOrderType.Move&&Vector3.Distance(c.SelectedArmy.currentOrder.target,f.Target)<.01f,"Marker mismatch");Check(GameObject.Find("target-caption")!=null,"No target UI");var canvas=GameObject.Find("Command25 target feedback");Check(canvas!=null&&canvas.GetComponentsInChildren<Graphic>().All(g=>!g.raycastTarget),"Marker intercepts clicks");checks.Add("Accepted move resumes; marker equals committed ground target and is click-through");Shot("03-move-receipt");yield return new WaitForSecondsRealtime(.3f);
 r.stage="append-paused";B("start").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);int count=c.GetMoveRoutePointCount(0);Check(hud.TestMove25(new Vector3(40,0,40),true),"Append rejected");yield return new WaitForSecondsRealtime(.25f);Check(c.Phase==WarSandboxBattlePhase.Paused&&c.GetMoveRoutePointCount(0)==count+1&&f.Message.Contains("仍保持暂停"),"Append paused rule changed");Check(c.TryGetMoveRoutePoint(0,count,out var appended)&&Vector3.Distance(appended,f.Target)<.01f,"Append marker not last committed point");checks.Add("Paused Shift append stays paused and highlights new waypoint");Shot("04-paused-append");yield return new WaitForSecondsRealtime(.3f);
 r.stage="cancel";B("move").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("move-cancel").onClick.Invoke();yield return new WaitForSecondsRealtime(.25f);Check(!hud.AwaitingMove25&&c.GetMoveRoutePointCount(0)==count+1&&c.Phase==WarSandboxBattlePhase.Paused&&Text("feedback-text").Contains("已取消"),"Cancel feedback/state wrong");checks.Add("Cancel visible even paused; route preserved");
 r.stage="attack";B("attack").onClick.Invoke();yield return new WaitForSecondsRealtime(.25f);Check(c.SelectedArmy.currentOrder.type==ArmyOrderType.Attack&&c.Phase==WarSandboxBattlePhase.Running&&!f.HasTarget&&Text("feedback-text").Contains("已下达进攻"),"Attack receipt/semantics wrong");checks.Add("Attack accepted without inventing a fixed target");Shot("05-attack");yield return new WaitForSecondsRealtime(.3f);
 r.stage="hold";B("hold").onClick.Invoke();yield return new WaitForSecondsRealtime(.25f);Check(c.SelectedArmy.currentOrder.type==ArmyOrderType.Hold&&!f.HasTarget&&Text("feedback-text").Contains("已下达防守"),"Hold receipt");checks.Add("Hold receipt correct; no fake target");
 r.stage="retreat";B("retreat").onClick.Invoke();yield return new WaitForSecondsRealtime(.25f);Check(c.SelectedArmy.currentOrder.type==ArmyOrderType.Retreat&&f.HasTarget&&Vector3.Distance(c.SelectedArmy.currentOrder.target,f.Target)<.01f,"Retreat target mismatch");checks.Add("Retreat marker equals actual resolved spawn target");Shot("06-retreat");yield return new WaitForSecondsRealtime(.3f);B("start").onClick.Invoke();yield return new WaitForSecondsRealtime(4.8f);Check(!f.Fresh&&!f.HasTarget&&GameObject.Find("target-caption")==null,"Expired marker remains visible");Check(Text("feedback-text").Contains("Shift追加已有路线仍暂停"),"Pause nuance missing");checks.Add("Receipt and marker expire on unscaled time; pause guidance accurate");
 r.stage="pause-receipt-sync";Check(hud.TestMove25(Vector3.zero),"Move for status sync");yield return new WaitForSecondsRealtime(.2f);B("start").onClick.Invoke();yield return new WaitForSecondsRealtime(.25f);Check(c.Phase==WarSandboxBattlePhase.Paused&&Text("feedback-text").Contains("当前已暂停")&&!Text("feedback-text").Contains("战斗已恢复"),"Stale resumed receipt after pause");checks.Add("Fresh accepted receipt reflects subsequent pause instead of claiming resumed");Shot("07-pause-current-state");yield return new WaitForSecondsRealtime(.3f);
 Check(hud.TestMove25(new Vector3(35,0,35),true),"Append for status sync");yield return new WaitForSecondsRealtime(.2f);B("start").onClick.Invoke();yield return new WaitForSecondsRealtime(.25f);Check(c.Phase==WarSandboxBattlePhase.Running&&Text("feedback-text").Contains("当前战斗进行中")&&!Text("feedback-text").Contains("仍保持暂停"),"Stale paused receipt after resume");checks.Add("Fresh append receipt reflects subsequent resume");
 r.stage="running-dialog";B("battle-tools").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("reset").onClick.Invoke();yield return new WaitForSecondsRealtime(.25f);Check(hud.DecisionPending26&&c.Phase==WarSandboxBattlePhase.Running,"Dialog should not auto-pause");Check(Text("decision26-state").Contains("仍在交战"),"Running dialog warning");B("decision26-cancel").onClick.Invoke();yield return new WaitForSecondsRealtime(.25f);Check(!hud.DecisionPending26&&c.Phase==WarSandboxBattlePhase.Running,"Cancel running dialog changed phase");checks.Add("Destructive action requests do not auto-pause; cancel preserves running state");B("start").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);
 r.stage="focus-cancel";B("move").onClick.Invoke();int routeBefore=c.GetMoveRoutePointCount(0);var orderBefore=c.SelectedArmy.currentOrder;hud.TestFocus26(false);hud.TestFocus26(true);yield return new WaitForSecondsRealtime(.25f);Check(!hud.AwaitingMove25&&c.Phase==WarSandboxBattlePhase.Paused&&c.GetMoveRoutePointCount(0)==routeBefore&&c.SelectedArmy.currentOrder.type==orderBefore.type,"Focus cancel mutated order");Check(Text("feedback-text").Contains("窗口失去焦点"),"Focus explanation missing");checks.Add("Focus loss cancels only pending target picking; existing route/phase unchanged");Shot("08-focus-cancel");yield return new WaitForSecondsRealtime(.3f);
 r.stage="modal-gate";B("move").onClick.Invoke();B("reset").onClick.Invoke();yield return new WaitForSecondsRealtime(.25f);Check(hud.DecisionPending26&&!hud.AwaitingMove25&&c.Phase==WarSandboxBattlePhase.Paused,"Request reset should only open dialog/cancel picking");int accepted=f.Accepted;Check(hud.TestHotkeyGate26(),"Battle hotkeys not gated");Check(!hud.TestMove25(Vector3.zero)&&f.Accepted==accepted&&c.GetMoveRoutePointCount(0)==routeBefore,"Underlying command bypassed dialog");Check(!B("attack").interactable&&GameObject.Find("decision26-shade").GetComponent<Graphic>().raycastTarget,"Modal click shield missing");Check(Text("decision26-state").Contains("保持暂停"),"Paused dialog warning");checks.Add("Modal blocks command dispatch/hotkeys and shields underlying UI; pending pick cleared");Shot("09-reset-confirmation");yield return new WaitForSecondsRealtime(.3f);B("decision26-cancel").onClick.Invoke();yield return new WaitForSecondsRealtime(.25f);Check(c.Phase==WarSandboxBattlePhase.Paused&&c.GetMoveRoutePointCount(0)==routeBefore&&!hud.DecisionPending26,"Cancel reset mutated battle");
 r.stage="cancel-end";B("end-battle").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);Check(hud.DecisionPending26&&c.Phase==WarSandboxBattlePhase.Paused,"End applied before confirmation");B("decision26-cancel").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);Check(c.Phase==WarSandboxBattlePhase.Paused&&c.GetMoveRoutePointCount(0)==routeBefore,"Cancel end mutated battle");checks.Add("Cancel reset and end both preserve paused battle and route");
 r.stage="confirm-reset";B("reset").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("decision26-confirm").onClick.Invoke();yield return new WaitForSecondsRealtime(.4f);Check(c.Phase==WarSandboxBattlePhase.Setup&&!hud.DecisionPending26&&!hud.AwaitingMove25&&!f.HasTarget&&!f.Fresh&&c.GetMoveRoutePointCount(0)==0,"Reset leaves stale state");Check(GameObject.Find("decision26-card")==null&&GameObject.Find("target-caption")==null,"Old overlays remain after reset");checks.Add("Confirmed reset returns to setup and clears transient UI/old routes");Shot("10-reset-ready");yield return new WaitForSecondsRealtime(.3f);
 r.stage="setup-reset-dialog";B("battle-tools").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("reset").onClick.Invoke();yield return new WaitForSecondsRealtime(.35f);Check(c.Phase==WarSandboxBattlePhase.Setup&&hud.DecisionPending26&&GameObject.Find("decision26-card")!=null,"Setup reset dialog disappeared");Shot("13-setup-reset-confirmation");yield return new WaitForSecondsRealtime(.3f);B("decision26-confirm").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(c.Phase==WarSandboxBattlePhase.Setup&&!hud.DecisionPending26&&!f.Fresh,"Setup reset confirmation failed");checks.Add("Setup reset also retains confirmation dialog until explicit decision");
 r.stage="confirm-end";B("start").onClick.Invoke();yield return new WaitForSecondsRealtime(.4f);Check(c.Phase==WarSandboxBattlePhase.Running,"Restart after reset failed");Check(hud.TestMove25(Vector3.zero),"New round move");yield return new WaitForSecondsRealtime(.2f);B("battle-tools").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("end-battle").onClick.Invoke();yield return new WaitForSecondsRealtime(.25f);Shot("11-end-confirmation");yield return new WaitForSecondsRealtime(.3f);B("decision26-confirm").onClick.Invoke();yield return new WaitForSecondsRealtime(.4f);Check(c.Phase==WarSandboxBattlePhase.Ended&&!hud.DecisionPending26&&!hud.AwaitingMove25&&!f.HasTarget&&!f.Fresh,"End leaves stale state");Check(GameObject.Find("target-caption")==null&&GameObject.Find("command-bar")==null,"Battle command UI remains on result");Check(!hud.TestMove25(Vector3.zero),"Ended battle accepted move");checks.Add("Confirmed manual end clears transient UI and blocks further commands");Shot("12-ended-clean");yield return new WaitForSecondsRealtime(.3f);
r.accepted=f.Accepted;r.rejected=f.Failures;r.stage="complete";
 }
#endif
 }
}
