#if UNITY_EDITOR
using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using UnityEngine;using UnityEngine.UI;
namespace MassEngine.Game {
public sealed class Ending36Probe:MonoBehaviour {
[Serializable]class Round{public string name,reason,phase;public int winner;public float realSeconds,battleSeconds;public int[] reported,hpAlive,stateAlive;public float captureProgress;}
[Serializable]class Receipt{public bool passed,osInputTest=false,forcedVictory=false;public string stage,error;public List<string> checks=new List<string>(),failures=new List<string>();public List<Round> rounds=new List<Round>();}
Receipt r=new Receipt();string output;WarSandboxSceneSession session;WarSandboxBattleController c;WarSandboxRuntimeDeployment d;WarSandboxDeploymentEntry[] expected;
[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Install(){var a=Environment.GetCommandLineArgs();if(!a.Contains("--ending36-probe"))return;var go=new GameObject("Ending36 isolated check");DontDestroyOnLoad(go);var p=go.AddComponent<Ending36Probe>();p.output=a.First(x=>x.StartsWith("--terrain-output=")).Substring(17);}
static void Check(bool b,string s){if(!b)throw new Exception(s);}void Verify(bool b,string s){if(b)r.checks.Add(s);else r.failures.Add(s);}
static Button B(string n)=>FindObjectsByType<Button>(FindObjectsSortMode.None).Single(b=>b.name==n&&b.gameObject.activeInHierarchy);static string Txt(string n)=>GameObject.Find(n).GetComponentInChildren<Text>().text;
IEnumerator Start(){Directory.CreateDirectory(output);var stack=new Stack<IEnumerator>();stack.Push(Run());while(stack.Count>0){bool moved;object next;try{moved=stack.Peek().MoveNext();next=moved?stack.Peek().Current:null;}catch(Exception ex){r.error=ex.ToString();Finish(1);yield break;}if(!moved){stack.Pop();continue;}if(next is IEnumerator e)stack.Push(e);else yield return next;}r.passed=r.failures.Count==0;Finish(r.passed?0:1);}
void Finish(int code){File.WriteAllText(Path.Combine(output,"receipt.json"),JsonUtility.ToJson(r,true));Debug.Log("ENDING36_RESULT "+JsonUtility.ToJson(r));Application.Quit(code);}
void SaveProgress(){File.WriteAllText(Path.Combine(output,"progress.json"),JsonUtility.ToJson(r,true));}
void Gpu(out int[] health,out int[] state){int count=c.manager.Buffers.AgentCount;var agents=new AgentData[count];var ids=new int[count];var hp=new int[count];c.manager.Buffers.agentBuffer.GetData(agents);c.manager.Buffers.combatBuffers.teamIdBuffer.GetData(ids);c.manager.Buffers.combatBuffers.hpReadBuffer.GetData(hp);health=new int[c.ArmyCount];state=new int[c.ArmyCount];for(int i=0;i<count;i++){if(hp[i]>0)health[ids[i]]++;if(agents[i].currentState!=4)state[ids[i]]++;}}
void CompareDraft(){var actual=d.Draft.Snapshot();Verify(actual.Length==expected.Length,"Draft entry count preserved");if(actual.Length!=expected.Length)return;for(int i=0;i<actual.Length;i++){var a=actual[i];var e=expected[i];Verify(a.template==e.template&&a.count==e.count&&a.teamId==e.teamId&&a.Name==e.Name&&Vector3.Distance(a.center,e.center)<.001f&&Mathf.Abs(a.density-e.density)<.0001f&&Mathf.Abs(a.aspect-e.aspect)<.0001f&&Vector3.Distance(a.manualSize,e.manualSize)<.001f,"Draft identity/placement preserved "+i);}}
void ResetChecks(string label,bool running){Gpu(out var health,out var states);Verify(c.manager.Buffers.AgentCount==2048&&health.SequenceEqual(new[]{1024,1024})&&states.SequenceEqual(health),label+" restored all units");Verify(!c.BattleResult.valid&&c.Phase==(running?WarSandboxBattlePhase.Running:WarSandboxBattlePhase.Setup),label+" phase/result reset");Verify(c.GetMoveRoutePointCount(0)==0&&c.GetMoveRoutePointCount(1)==0&&Mathf.Abs(c.SimulationSpeed-1)<.001f&&Mathf.Abs(Time.timeScale-1)<.001f,label+" routes/speed reset");Verify(c.ControlPointOwnerTeamId==-1&&c.ControlPointCaptureProgress==0,label+" point progress reset");Verify(GameObject.Find("result-card")==null&&!c.GetComponent<CommandFeedback25>().HasTarget,label+" result UI/target cleared");}
IEnumerator Natural(string name,WarSandboxVictoryReason reason){r.stage=name;float start=Time.realtimeSinceStartup;int frame=Time.frameCount;while(!c.BattleResult.valid){float t=Time.realtimeSinceStartup-start;Check(t<180,"Natural settlement timeout "+name);if(t>10)Check((Time.frameCount-frame)/t>=10,"Under10fps stop");yield return null;}yield return null;Gpu(out var hp,out var state);var report=c.BattleResult;var row=new Round{name=name,reason=report.victoryReason.ToString(),phase=c.Phase.ToString(),winner=report.winnerTeamId,realSeconds=Time.realtimeSinceStartup-start,battleSeconds=report.battleSeconds,hpAlive=hp,stateAlive=state,reported=Enumerable.Range(0,2).Select(i=>report.GetArmy(i).survivors).ToArray(),captureProgress=c.ControlPointCaptureProgress};r.rounds.Add(row);Verify(report.victoryReason==reason,name+" expected natural reason");Verify(row.reported.SequenceEqual(hp),name+" frozen totals equal final GPU health");Verify(hp.SequenceEqual(state),name+" health/state counts agree");for(int i=0;i<2;i++){var a=report.GetArmy(i);Verify(a.initial==1024&&a.survivors+a.Casualties==1024,name+" arithmetic team "+i);}if(reason==WarSandboxVictoryReason.Annihilation)Verify(report.winnerTeamId>=0&&hp[1-report.winnerTeamId]==0&&hp[report.winnerTeamId]>0,name+" elimination winner correct");else Verify(report.winnerTeamId==0&&c.ControlPointCaptureProgress>=1,name+" capture winner/progress correct");string frozen=JsonUtility.ToJson(report);Verify(!c.IssueOrder(ArmyOrder.Attack(0))&&!c.EndBattle(),name+" terminal commands rejected");c.StartOrResumeBattle();yield return new WaitForSecondsRealtime(.8f);Gpu(out var later,out _);Verify(frozen==JsonUtility.ToJson(c.BattleResult)&&later.SequenceEqual(hp),name+" frozen result/GPU stable");for(int i=0;i<2;i++){var a=report.GetArmy(i);Verify(Txt("result-army-"+i+"-initial")==a.initial.ToString("N0")&&Txt("result-army-"+i+"-alive")==a.survivors.ToString("N0")&&Txt("result-army-"+i+"-losses")==a.Casualties.ToString("N0"),name+" visible UI counts agree "+i);}SaveProgress();}
void Rules(WarSandboxGameMode mode){var rules=d.Draft.Rules;rules.gameMode=mode;d.Draft.Replace(d.Draft.Snapshot(),rules,d.Draft.Stats);Check(d.TryValidate(out var error),error);}
IEnumerator Enter(int season){B("card-"+season).onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);B("card-"+season+"-enter").onClick.Invoke();float limit=Time.realtimeSinceStartup+120;while(session.IsLoading&&Time.realtimeSinceStartup<limit)yield return null;yield return new WaitForSecondsRealtime(.6f);Check(session.State==WarSandboxEntryState.Battle&&!session.HelpOpen,"Load failed");c=session.Controller;d=c.GetComponent<WarSandboxRuntimeDeployment>();Check(d.IsEditing&&d.Draft.Snapshot().Sum(e=>e.count)==2048,"Default deployment changed");}
IEnumerator Run(){r.stage="load";yield return new WaitForSecondsRealtime(3);session=WarSandboxSceneSession.Instance;B("home-play").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);yield return Enter(0);expected=d.Draft.Snapshot();Rules(WarSandboxGameMode.Annihilation);B("deployment-start").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);yield return Natural("annihilation",WarSandboxVictoryReason.Annihilation);
r.stage="result-restart";B("result-restart").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);ResetChecks("Restart",true);
r.stage="manual-end-after-orders";Check(c.IssueMoveOrder(0,new Vector3(-80,0,40),false)&&c.IssueMoveOrder(0,new Vector3(-40,0,40),true),"Could not seed route");Check(c.IssueOrder(ArmyOrder.Hold(1)),"Could not seed hold");c.SetSimulationSpeed(2);yield return new WaitForSecondsRealtime(.5f);Check(c.EndBattle(),"Manual end rejected");yield return new WaitForSecondsRealtime(.4f);Verify(c.BattleResult.victoryReason==WarSandboxVictoryReason.ManualEnd&&c.BattleResult.winnerTeamId==-1,"Manual end does not invent a winner");B("result-edit").onClick.Invoke();yield return new WaitForSecondsRealtime(.4f);Check(d.IsEditing,"Result edit failed");ResetChecks("Edit",false);CompareDraft();
r.stage="control-point";Rules(WarSandboxGameMode.ControlPoint);B("deployment-start").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);Check(c.IssueOrder(ArmyOrder.Hold(1))&&c.IssueMoveOrder(0,c.controlPointCenter,false),"Capture orders failed");yield return Natural("capture",WarSandboxVictoryReason.ControlPoint);
r.stage="catalog-reentry";B("result-menu").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);if(session.ConfirmationOpen)B("modal-confirm").onClick.Invoke();float deadline=Time.realtimeSinceStartup+120;while(session.IsLoading&&Time.realtimeSinceStartup<deadline)yield return null;yield return new WaitForSecondsRealtime(.6f);Check(session.State==WarSandboxEntryState.Menu&&session.Controller==null,"Catalog retained controller");Verify(GameObject.Find("result-card")==null,"Catalog cleared result UI");yield return Enter(2);Verify(d.Draft.Snapshot().All(e=>e.count==1024),"New battlefield starts default counts");ResetChecks("Reentry",false);CompareDraft();r.stage="complete";
}
}}
#endif
