using UnityEngine;
#if UNITY_EDITOR || DEVELOPMENT_BUILD
using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using UnityEngine.UI;
#endif
namespace MassEngine.Game {
 public sealed class Help30PlayerSmoke:MonoBehaviour {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
 [Serializable]class Receipt{public bool passed,osInputTest=false;public string mode,stage,error,buildGuid;public string[] checks;}
 Receipt r=new Receipt();List<string> checks=new List<string>();string output;WarSandboxSceneSession session;Guide30 guide;
 [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Install(){var args=Environment.GetCommandLineArgs();if(!args.Contains("--help30-smoke"))return;var g=new GameObject("Help30 isolated smoke");DontDestroyOnLoad(g);var t=g.AddComponent<Help30PlayerSmoke>();t.output=args.First(a=>a.StartsWith("--terrain-output=")).Substring("--terrain-output=".Length);t.r.mode=args.First(a=>a.StartsWith("--help30-mode=")).Substring("--help30-mode=".Length);}
 static void Check(bool b,string e){if(!b)throw new Exception(e);}
 static Button B(string n){var b=FindObjectsByType<Button>(FindObjectsSortMode.None).SingleOrDefault(b=>b.name==n&&b.gameObject.activeInHierarchy);if(b==null)throw new Exception("Missing active button: "+n);return b;}
 static InputField Field(string n)=>FindObjectsByType<InputField>(FindObjectsSortMode.None).Single(f=>f.name==n&&f.gameObject.activeInHierarchy);
 static Text T(string n)=>GameObject.Find(n).GetComponentInChildren<Text>();
 void Shot(string n)=>ScreenCapture.CaptureScreenshot(Path.Combine(output,n+".png"));
 void Fit(){foreach(string n in new[]{"help30-title","help30-body","help30-note"}){var t=T(n);Check(t.preferredHeight<=t.rectTransform.rect.height+2,n+" clipped");}}
 IEnumerator Start(){Directory.CreateDirectory(output);r.buildGuid=Application.buildGUID;var stack=new Stack<IEnumerator>();stack.Push(Run());while(stack.Count>0){bool moved;object next;try{moved=stack.Peek().MoveNext();next=moved?stack.Peek().Current:null;}catch(Exception ex){r.error=ex.ToString();Finish(1);yield break;}if(!moved){stack.Pop();continue;}if(next is IEnumerator e)stack.Push(e);else yield return next;}r.passed=true;Finish(0);}
 void Finish(int code){r.checks=checks.ToArray();File.WriteAllText(Path.Combine(output,"receipt.json"),JsonUtility.ToJson(r,true));Debug.Log("HELP30_RESULT "+JsonUtility.ToJson(r));Application.Quit(code);}
 IEnumerator Enter(int index,bool home){if(home){B("home-play").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);}B("card-"+index).onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("card-"+index+"-enter").onClick.Invoke();float end=Time.realtimeSinceStartup+120;while(session.IsLoading&&Time.realtimeSinceStartup<end)yield return null;Check(session.State==WarSandboxEntryState.Battle,"Load failed");yield return new WaitForSecondsRealtime(.7f);}
 IEnumerator Close(){B("help30-close").onClick.Invoke();Check(session.HelpInputBlocked30,"Closing frame allows input through");yield return new WaitForSecondsRealtime(.3f);Check(!session.HelpOpen,"Help did not close");}
 IEnumerator Run(){r.stage="startup";yield return new WaitForSecondsRealtime(3);session=WarSandboxSceneSession.Instance;guide=Guide30.For(session);Check(guide!=null,"No Guide30 marker");bool restart=r.mode.StartsWith("restart");Check(guide.Seen==restart,"Unexpected remembered flag");var audio=WarSandboxAudio.Ensure();Check(audio.SaveSettings(),"Isolated audio seed failed");byte[] sound=File.ReadAllBytes(audio.SettingsPath);
  if(r.mode=="skip"){B("menu-help").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(session.HelpOpen&&!guide.Intro,"Manual menu help wrong");Fit();yield return Close();Check(!File.Exists(guide.FilePath),"Manual help unexpectedly wrote first-entry progress");checks.Add("Menu help opens without battle or changing first-entry record");}
  yield return Enter(0,true);var c=session.Controller;var d=c.GetComponent<WarSandboxRuntimeDeployment>();Check(d.IsEditing&&d.Draft.Snapshot().Sum(e=>e.count)==2048,"Not default draft");string initial=PlanState28.For(c).Current;
  if(restart){Check(!session.HelpOpen,"First guide repeated across EXE restart");B("nav-help").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(!guide.Intro&&session.HelpOpen,"Remembered guide blocks manual help");Fit();yield return Close();Check(PlanState28.For(c).Current==initial,"Manual help changed draft");checks.Add("Fresh EXE process suppresses automatic guide after completion/skip while retaining manual access");}
  else{Check(session.HelpOpen&&guide.Intro&&session.InputBlocked,"First deployment guide missing");Check(!WarSandboxSceneSession.AllowsBattleCommands(c),"Guide lets commands through");Fit();Shot("01-first-deployment");yield return new WaitForSecondsRealtime(.3f);
   for(int i=1;i<3;i++){B("help30-tab-"+i).onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);Fit();}Shot("02-plan-result-help");yield return new WaitForSecondsRealtime(.3f);Check(PlanState28.For(c).Current==initial,"Guide tabs modified draft");
   if(r.mode=="failure"){B("help30-skip").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(guide.Seen&&!guide.Intro&&session.HelpOpen&&guide.Error.Contains("保存失败"),"Persistence failure not safely explained");Fit();Shot("03-progress-write-failure");yield return new WaitForSecondsRealtime(.3f);yield return Close();Check(!File.Exists(guide.FilePath),"Failed record wrote file");checks.Add("Actual blocked directory fails progress write, reports session-only dismissal, and allows continued play");}
   else{B(r.mode=="skip"?"help30-skip":"help30-close").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(!session.HelpOpen&&guide.Seen&&File.Exists(guide.FilePath)&&File.ReadAllText(guide.FilePath).Contains("true"),"Dismissal not persisted");checks.Add("First guide shows once on deployment and completion/skip persists to separate real file");}
  }
  if(r.mode=="skip"){
   r.stage="draft-safety";d.PlanStore=new WarSandboxLocalPlanStore(Path.Combine(output,"isolated-plans"));Check(d.TrySavePlan("KEEP30","Keep through help",false,out var error),error);string plan=Path.Combine(d.PlanStore.DirectoryPath,"KEEP30.json");byte[] saved=File.ReadAllBytes(plan);
   B("army-details-0").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Field("input-count").text="1100";B("nav-help").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(session.HelpOpen&&d.Draft[0].count==1024,"Help committed raw input");yield return Close();Check(Field("input-count").text=="1100"&&d.Draft[0].count==1024,"Help lost pending input");Field("input-count").text="1024";B("legion-done").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(PlanState28.For(c).Current==initial&&File.ReadAllBytes(plan).SequenceEqual(saved),"Help altered deployment or plan");checks.Add("Raw uncommitted input, draft and real plan file survive help without being silently applied/saved");
   r.stage="battle-help";B("deployment-start").onClick.Invoke();yield return new WaitForSecondsRealtime(.4f);Check(c.Phase==WarSandboxBattlePhase.Running,"Not running");B("nav-help").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(c.Phase==WarSandboxBattlePhase.Paused&&!WarSandboxSceneSession.AllowsBattleCommands(c),"Help did not pause/block");B("help30-tab-1").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Fit();Shot("04-battle-controls");yield return new WaitForSecondsRealtime(.3f);yield return Close();Check(c.Phase==WarSandboxBattlePhase.Running,"Running battle not resumed");c.PauseBattle();B("battle-tools").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);B("help").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(session.HelpOpen,"Existing help entry did not route");yield return Close();Check(c.Phase==WarSandboxBattlePhase.Paused,"Previously paused battle resumed");
   B("nav-settings").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);guide.Open();Check(!session.HelpOpen&&session.SettingsOpen,"Help overlaps settings");B("settings-cancel").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);checks.Add("Both battle help entries work; running/paused state preserved and settings/help cannot stack");
   r.stage="post-battle-help";B("battle-tools").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);B("end-battle").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);B("decision26-confirm").onClick.Invoke();yield return new WaitForSecondsRealtime(.4f);Check(c.BattleResult.valid,"No result");B("nav-help").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);yield return Close();Check(c.BattleResult.valid&&c.Phase==WarSandboxBattlePhase.Ended,"Help cleared battle result");B("result-edit").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(!session.HelpOpen&&d.IsEditing,"Guide repeated after result-edit");B("deployment-apply").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(session.TryReturnToMenu(false,out error),error);float end=Time.realtimeSinceStartup+60;while(session.IsLoading&&Time.realtimeSinceStartup<end)yield return null;yield return new WaitForSecondsRealtime(.4f);yield return Enter(2,false);Check(!session.HelpOpen&&session.Controller.GetComponent<WarSandboxRuntimeDeployment>().IsEditing,"Guide repeated on next season");Check(File.ReadAllBytes(plan).SequenceEqual(saved),"Scene changes altered plan");checks.Add("Result preserved, no repeated intro after result-edit or switching to winter");
  }
  Check(File.ReadAllBytes(audio.SettingsPath).SequenceEqual(sound),"Help modified sound settings");checks.Add("Audio settings bytes unchanged");r.stage="complete";
 }
#endif
 }
}
