using UnityEngine;
#if UNITY_EDITOR || DEVELOPMENT_BUILD
using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using UnityEngine.UI;
#endif
namespace MassEngine.Game {
 public sealed class Plans28PlayerSmoke:MonoBehaviour {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
 [Serializable]class Receipt{public bool passed,osInputTest=false,isolatedPlanDirectory=true;public string stage,error,buildGuid;public int units=2048;public string[] checks;}
 Receipt r=new Receipt();List<string> checks=new List<string>();string output,dir,file;WarSandboxBattleController c;WarSandboxRuntimeDeployment d;PlanState28 state;
 [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Install(){var a=Environment.GetCommandLineArgs();if(!a.Contains("--plans28-smoke"))return;var p=a.FirstOrDefault(v=>v.StartsWith("--terrain-output="));if(p==null){Application.Quit(2);return;}var go=new GameObject("Plans28 isolated persistence smoke");DontDestroyOnLoad(go);go.AddComponent<Plans28PlayerSmoke>().output=p.Substring("--terrain-output=".Length);}
 static void Check(bool b,string e){if(!b)throw new Exception(e);}
 static Button B(string n)=>FindObjectsByType<Button>(FindObjectsSortMode.None).Single(b=>b.name==n&&b.gameObject.activeInHierarchy);
 static string Txt(string n)=>GameObject.Find(n).GetComponentInChildren<Text>().text;
 static InputField Field(string n)=>FindObjectsByType<InputField>(FindObjectsSortMode.None).Single(f=>f.name==n&&f.gameObject.activeInHierarchy);
 void Shot(string n)=>ScreenCapture.CaptureScreenshot(Path.Combine(output,n+".png"));
 IEnumerator Start(){Directory.CreateDirectory(output);r.buildGuid=Application.buildGUID;var stack=new Stack<IEnumerator>();stack.Push(Run());while(stack.Count>0){object n;bool moved;try{moved=stack.Peek().MoveNext();n=moved?stack.Peek().Current:null;}catch(Exception ex){r.error=ex.ToString();Finish(1);yield break;}if(!moved){stack.Pop();continue;}if(n is IEnumerator nested)stack.Push(nested);else yield return n;}r.passed=true;Finish(0);}
 void Finish(int code){r.checks=checks.ToArray();File.WriteAllText(Path.Combine(output,"receipt.json"),JsonUtility.ToJson(r,true));Debug.Log("PLANS28_RESULT "+JsonUtility.ToJson(r));Application.Quit(code);}
 void Change(int first,float shift){for(int i=0;i<2;i++){var e=d.Draft[i];e.count=i==0?first:2048-first;e.center.z=i==0?shift:-shift;d.Draft.Set(i,e);}Check(d.TryValidate(out var err),err);}
 void FileCount(int count){var fresh=new WarSandboxLocalPlanStore(dir);Check(fresh.TryLoad("QA28",out var p,out var err),err);Check(p.entries.Length==2&&p.entries[0].count==count&&p.entries.Sum(e=>e.count)==2048,"Persisted count mismatch");}
 IEnumerator CancelNav(string id){B(id).onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(WarSandboxSceneSession.Instance.ConfirmationOpen,"Leave warning missing");Check(Txt("modal-body").Contains("保存"),"Save distinction missing");B("modal-cancel").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(!WarSandboxSceneSession.Instance.ConfirmationOpen,"Cancel failed");}
 IEnumerator Run(){r.stage="load";yield return new WaitForSecondsRealtime(3);var session=WarSandboxSceneSession.Instance;B("home-play").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);int index=Environment.GetCommandLineArgs().Contains("--winter")?2:0;B("card-"+index).onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("card-"+index+"-enter").onClick.Invoke();float end=Time.realtimeSinceStartup+120;while(session.IsLoading&&Time.realtimeSinceStartup<end)yield return null;Check(session.State==WarSandboxEntryState.Battle,"Load failed");yield return new WaitForSecondsRealtime(1);c=session.Controller;d=c.GetComponent<WarSandboxRuntimeDeployment>();state=PlanState28.For(c);Check(state!=null&&d.IsEditing,"Missing opt-in draft");dir=Path.Combine(output,"isolated-plans");file=Path.Combine(dir,"QA28.json");d.PlanStore=new WarSandboxLocalPlanStore(dir);Check(!state.NeedsLeaveWarning,"Untouched default incorrectly dirty");
 r.stage="pending-input";B("army-details-0").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Field("input-count").text="1100";yield return new WaitForSecondsRealtime(.25f);Check(state.NeedsLeaveWarning&&Txt("deployment-validation").Contains("输入未更新"),"Pending fields not warned");yield return CancelNav("nav-menu");Check(Field("input-count").text=="1100"&&d.Draft[0].count==1024,"Cancel modified raw input or committed draft");Field("input-count").text="1024";B("legion-done").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);checks.Add("Uncommitted text warns before leave; cancel retains input without silently applying it");
 r.stage="save-draft";Change(1100,18);yield return new WaitForSecondsRealtime(.3f);Check(state.DraftChanged&&!state.CurrentStored&&state.NeedsLeaveWarning,"Dirty draft state wrong");B("deployment-plans").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Field("plans-slot").text="QA28";Field("plans-name").text="QA28 isolated roundtrip";B("plans-save").onClick.Invoke();yield return new WaitForSecondsRealtime(.35f);Check(Txt("plans-message").Contains("已保存到本地")&&state.CurrentStored&&state.DraftChanged&&d.IsEditing&&c.Phase==WarSandboxBattlePhase.Setup,"Save conflated with apply");Check(c.manager.scenarioConfig.unitTypes[0].spawnConfig.unitCount==1024,"Save applied runtime roster");FileCount(1100);checks.Add("Save writes real file, remains editable/unapplied; fresh store reads 1100/948");Shot("01-saved-not-applied");yield return new WaitForSecondsRealtime(.3f);
 r.stage="overwrite-cancel";B("plans-back").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);Change(1180,22);yield return new WaitForSecondsRealtime(.3f);byte[] old=File.ReadAllBytes(file);B("deployment-plans").onClick.Invoke();yield return new WaitForSecondsRealtime(.25f);B("plans-save").onClick.Invoke();yield return new WaitForSecondsRealtime(.25f);Check(GameObject.Find("plans-confirm")!=null,"No overwrite confirmation");B("plans-confirm-no").onClick.Invoke();yield return new WaitForSecondsRealtime(.25f);Check(File.ReadAllBytes(file).SequenceEqual(old)&&!state.CurrentStored&&d.Draft[0].count==1180,"Cancelled overwrite wrote or discarded draft");checks.Add("Overwrite cancel preserves old file and current edited draft");
 r.stage="overwrite-failure";B("plans-save").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);using(var held=new FileStream(file,FileMode.Open,FileAccess.Read,FileShare.None)){B("plans-confirm-yes").onClick.Invoke();}yield return new WaitForSecondsRealtime(.3f);Check(Txt("plans-message").Contains("失败")&&!Txt("plans-message").Contains("已保存")&&!state.CurrentStored&&File.ReadAllBytes(file).SequenceEqual(old),"Failure reported success or damaged original");checks.Add("Real locked-file overwrite failure preserves original and keeps draft unsaved");Shot("02-save-failure");yield return new WaitForSecondsRealtime(.3f);
 r.stage="overwrite-success";B("plans-save").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("plans-confirm-yes").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(state.CurrentStored,"Overwrite not marked saved");FileCount(1180);old=File.ReadAllBytes(file);checks.Add("Confirmed overwrite succeeds after lock release and updates saved snapshot");
 r.stage="load-roundtrip";B("plans-back").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);Change(1060,12);yield return new WaitForSecondsRealtime(.3f);var originalTemplate=d.Draft[0].template;B("deployment-plans").onClick.Invoke();yield return new WaitForSecondsRealtime(.25f);B("plan-item-0").onClick.Invoke();B("plans-load").onClick.Invoke();yield return new WaitForSecondsRealtime(.25f);B("plans-confirm-no").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);Check(d.Draft[0].count==1060,"Cancel load replaced draft");B("plans-load").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);File.WriteAllText(file,"not valid JSON");B("plans-confirm-yes").onClick.Invoke();yield return new WaitForSecondsRealtime(.25f);Check(d.Draft[0].count==1060&&!state.CurrentStored&&Txt("plans-message").Contains("失败"),"Corrupt file accepted or false success");File.WriteAllBytes(file,old);B("plans-load").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("plans-confirm-yes").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(d.Draft[0].count==1180&&d.Draft[1].count==868&&Mathf.Abs(d.Draft[0].center.z-22)<.001f&&d.Draft[0].template==originalTemplate&&state.CurrentStored&&d.IsEditing,"Load lost roster/placement or auto-applied");checks.Add("Cancel/corrupt load preserves draft; repaired file loads identities/counts/placement without applying");Shot("03-loaded-draft");yield return new WaitForSecondsRealtime(.3f);
 r.stage="applied-unsaved";Change(1080,14);yield return new WaitForSecondsRealtime(.3f);B("deployment-apply").onClick.Invoke();yield return new WaitForSecondsRealtime(.4f);Check(!d.IsEditing&&c.Phase==WarSandboxBattlePhase.Setup&&state.Applied&&state.NeedsLeaveWarning&&!state.CurrentStored,"Applied mistaken for disk saved");Check(Txt("setup-note").Contains("方案未保存"),"Applied unsaved status missing");B("nav-menu").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(session.ConfirmationOpen&&Txt("modal-body").Contains("应用到本局不等于保存"),"Setup lost unsaved warning");Shot("04-applied-leave-warning");yield return new WaitForSecondsRealtime(.3f);B("modal-cancel").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);yield return CancelNav("nav-quit");Check(c.Phase==WarSandboxBattlePhase.Setup&&c.manager.scenarioConfig.unitTypes[0].spawnConfig.unitCount==1080,"Leave/quit cancel changed applied config");checks.Add("Applied-only setup warns on catalog and quit; both cancellations preserve 1080/968 config");
 r.stage="terminal-leave";B("start").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(c.Phase==WarSandboxBattlePhase.Running,"Start failed");B("battle-tools").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("end-battle").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("decision26-confirm").onClick.Invoke();yield return new WaitForSecondsRealtime(.4f);B("result-menu").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(session.ConfirmationOpen&&Txt("modal-title").Contains("离开"),"Result-menu bypassed or failed to open warning");B("modal-cancel").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(c.BattleResult.valid&&c.Phase==WarSandboxBattlePhase.Ended,"Terminal cancel changed result");checks.Add("Result-menu routes through unsaved confirmation, not silent blocked navigation");
 r.stage="save-applied-and-return";B("result-edit").onClick.Invoke();yield return new WaitForSecondsRealtime(.35f);Check(d.Draft[0].count==1080,"Committed configuration lost");B("deployment-plans").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);B("plans-save").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("plans-confirm-yes").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);FileCount(1080);B("plans-back").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("deployment-apply").onClick.Invoke();yield return new WaitForSecondsRealtime(.35f);Check(state.CurrentStored&&!state.NeedsLeaveWarning&&Txt("setup-note").Contains("方案已保存"),"Saved/applied did not become clean");B("nav-menu").onClick.Invoke();end=Time.realtimeSinceStartup+60;while(session.IsLoading&&Time.realtimeSinceStartup<end)yield return null;yield return new WaitForSecondsRealtime(.4f);Check(session.State==WarSandboxEntryState.Menu&&!session.ConfirmationOpen,"Clean setup should return normally");FileCount(1080);Check(!Directory.GetFiles(dir,"*.tmp-*").Any(),"Leaked temporary save files");checks.Add("Saved+applied becomes clean; catalog exit retains file and leaves no temporary save files");r.stage="complete";
 }
#endif
 }
}
