using UnityEngine;
#if UNITY_EDITOR || DEVELOPMENT_BUILD
using System;using System.Collections;using System.Collections.Generic;using System.IO;using System.Linq;using UnityEngine.UI;
#endif
namespace MassEngine.Game {
 public sealed class Results27PlayerSmoke:MonoBehaviour {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
 [Serializable]class Receipt{public bool passed,osInputTest=false,naturalVictoryTest=false;public string stage,error,buildGuid;public int units;public string[] checks;}
 Receipt r=new Receipt();List<string> checks=new List<string>();string output;WarSandboxBattleController c;WarSandboxRuntimeDeployment d;WarSandboxDeploymentEntry[] expected;
 [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Install(){var args=Environment.GetCommandLineArgs();if(!args.Contains("--results27-smoke"))return;var path=args.FirstOrDefault(a=>a.StartsWith("--terrain-output="));if(path==null){Application.Quit(2);return;}var go=new GameObject("Results27 modified roster roundtrip");DontDestroyOnLoad(go);go.AddComponent<Results27PlayerSmoke>().output=path.Substring("--terrain-output=".Length);}
 static void Check(bool b,string e){if(!b)throw new Exception(e);}
 static Button B(string n)=>FindObjectsByType<Button>(FindObjectsSortMode.None).Single(b=>b.name==n&&b.gameObject.activeInHierarchy);
 static string Txt(string n)=>GameObject.Find(n).GetComponentInChildren<Text>().text;
 void Shot(string n)=>ScreenCapture.CaptureScreenshot(Path.Combine(output,n+".png"));
 IEnumerator Start(){Directory.CreateDirectory(output);r.buildGuid=Application.buildGUID;var e=Run();while(true){object n;try{if(!e.MoveNext())break;n=e.Current;}catch(Exception ex){r.error=ex.ToString();Finish(1);yield break;}yield return n;}r.passed=true;Finish(0);}
 void Finish(int code){r.checks=checks.ToArray();File.WriteAllText(Path.Combine(output,"receipt.json"),JsonUtility.ToJson(r,true));Debug.Log("RESULTS27_RESULT "+JsonUtility.ToJson(r));Application.Quit(code);}
 void Compare(WarSandboxDeploymentEntry[] actual,bool draft){Check(actual.Length==expected.Length,"Composition count changed");for(int i=0;i<actual.Length;i++){var a=actual[i];var e=expected[i];Check(a.count==e.count&&a.teamId==e.teamId&&a.Name==e.Name,"Roster identity/count changed "+i);Check(Vector2.Distance(new Vector2(a.center.x,a.center.z),new Vector2(e.center.x,e.center.z))<.001f,"XZ changed");if(draft)Check(Vector3.Distance(a.center,e.center)<.001f&&a.template==e.template,"Committed draft identity/Y changed");Check(Mathf.Abs(a.density-e.density)<.0001f&&Mathf.Abs(a.aspect-e.aspect)<.0001f&&Vector3.Distance(a.manualSize,e.manualSize)<.001f,"Formation changed");}}
 void RuntimeCheck(){Check(WarSandboxDeploymentDraft.TryCapture(c.manager.scenarioConfig,out var captured,out var error),error);Compare(captured.Snapshot(),false);r.units=c.manager.scenarioConfig.unitTypes.Sum(u=>u.spawnConfig.unitCount);Check(r.units==2048,"Total changed");}
 IEnumerator EndRound(){B("battle-tools").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("end-battle").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("decision26-confirm").onClick.Invoke();yield return new WaitForSecondsRealtime(.35f);Check(c.BattleResult.valid&&c.Phase==WarSandboxBattlePhase.Ended&&c.BattleResult.winnerTeamId<0,"Manual end should not assign winner");}
 IEnumerator Run(){r.stage="load";yield return new WaitForSecondsRealtime(3);var session=WarSandboxSceneSession.Instance;B("home-play").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);int idx=Environment.GetCommandLineArgs().Contains("--winter")?2:0;B("card-"+idx).onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("card-"+idx+"-enter").onClick.Invoke();float timeout=Time.realtimeSinceStartup+120;while(session.IsLoading&&Time.realtimeSinceStartup<timeout)yield return null;Check(session.State==WarSandboxEntryState.Battle,"Load failed");yield return new WaitForSecondsRealtime(1);c=session.Controller;d=c.GetComponent<WarSandboxRuntimeDeployment>();Check(d.IsEditing&&d.Draft.Count==2,"Expected two compositions");Check(BattleResult27.Active(c),"Missing marker");
 r.stage="modified-roster";for(int i=0;i<2;i++){var e=d.Draft[i];e.count=i==0?1100:948;e.center.z+=i==0?18:-18;d.Draft.Set(i,e);}expected=d.Draft.Snapshot();Check(d.TryValidate(out var error),error);yield return new WaitForSecondsRealtime(.4f);B("deployment-start").onClick.Invoke();yield return new WaitForSecondsRealtime(.35f);Check(c.Phase==WarSandboxBattlePhase.Running&&!d.IsEditing,"Apply/start failed");RuntimeCheck();checks.Add("Applied modified 1100/948 composition and shifted XZ; total remains 2048");
 var hud=c.GetComponent<WarSandboxCommandHUD>();Check(hud.TestMove25(Vector3.zero),"Seed route failed");c.SetSimulationSpeed(2);yield return new WaitForSecondsRealtime(.2f);
 r.stage="manual-result";yield return EndRound();RuntimeCheck();Check(Txt("result-title").Contains("手动结束")&&Txt("result-reason").Contains("不判定胜负"),"Manual result wording");for(int i=0;i<2;i++){Check(c.BattleResult.TryGetArmy(i,out var army)&&army.initial==expected[i].count&&army.survivors+army.Casualties==army.initial,"Result totals mismatch");Check(Txt("result-army-"+i+"-initial")==expected[i].count.ToString("N0"),"Displayed totals mismatch");}Check(Txt("result-next-note").Contains("已应用编成")&&Txt("result-next-note").Contains("进度和路线不保留"),"Missing next-action meaning");var note=GameObject.Find("result-next-note").GetComponentInChildren<Text>();Check(note.preferredHeight<=note.rectTransform.rect.height+.5f&&note.cachedTextGenerator.lineCount>=2,"Result note visually clipped");checks.Add("Two-line result note fits actual Text content box");checks.Add("Manual-end result shows committed 1100/948 counts and no winner; continuation note visible");Shot("01-modified-result");yield return new WaitForSecondsRealtime(.3f);
 r.stage="restart";B("result-restart").onClick.Invoke();yield return new WaitForSecondsRealtime(.35f);Check(c.Phase==WarSandboxBattlePhase.Running&&!c.BattleResult.valid&&!d.IsEditing,"Restart failed");RuntimeCheck();Check(Mathf.Abs(c.SimulationSpeed-1)<.001f&&c.GetMoveRoutePointCount(0)==0&&c.GetMoveRoutePointCount(1)==0,"Restart retained old speed/route");Check(!c.GetComponent<CommandFeedback25>().HasTarget&&GameObject.Find("result-card")==null,"Stale result/target");checks.Add("Result restart preserves applied identities/counts/XZ/formation; resets routes/speed/result");Shot("02-restarted");yield return new WaitForSecondsRealtime(.3f);
 r.stage="back-to-edit";yield return EndRound();B("result-edit").onClick.Invoke();yield return new WaitForSecondsRealtime(.4f);Check(d.IsEditing&&c.Phase==WarSandboxBattlePhase.Setup&&!c.BattleResult.valid,"Result edit failed");Compare(d.Draft.Snapshot(),true);Check(!c.GetComponent<WarSandboxDeploymentHUD>().Confirming,"Terminal edit should not request ending again");checks.Add("Result-to-editor restores committed template references, counts, authored XYZ and formation; no extra end prompt");Shot("03-restored-draft");yield return new WaitForSecondsRealtime(.3f);
 r.stage="discard-unapplied";var change=d.Draft[0];change.count=1120;change.center.z+=6;d.Draft.Set(0,change);yield return new WaitForSecondsRealtime(.3f);B("deployment-cancel").onClick.Invoke();yield return new WaitForSecondsRealtime(.35f);Check(!d.IsEditing&&c.Phase==WarSandboxBattlePhase.Setup,"Cancel draft failed");RuntimeCheck();B("edit").onClick.Invoke();yield return new WaitForSecondsRealtime(.35f);Compare(d.Draft.Snapshot(),true);checks.Add("Cancelled un-applied 1120-count draft does not overwrite committed 1100-count configuration");
 r.stage="apply-second-config";for(int i=0;i<2;i++){var e=d.Draft[i];e.count=i==0?1080:968;e.center.z+=i==0?4:-4;d.Draft.Set(i,e);}expected=d.Draft.Snapshot();Check(d.TryValidate(out error),error);yield return new WaitForSecondsRealtime(.3f);B("deployment-start").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);RuntimeCheck();yield return EndRound();B("result-restart").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);RuntimeCheck();Check(c.Phase==WarSandboxBattlePhase.Running&&!c.BattleResult.valid,"Second restart failed");checks.Add("Second committed 1080/968 configuration replaces first and survives another restart");
 r.stage="menu";yield return EndRound();B("result-menu").onClick.Invoke();timeout=Time.realtimeSinceStartup+60;while(session.IsLoading&&Time.realtimeSinceStartup<timeout)yield return null;yield return new WaitForSecondsRealtime(.5f);Check(session.State!=WarSandboxEntryState.Battle&&GameObject.Find("result-card")==null,"Return to catalog failed");checks.Add("Result return-to-other-battlefield exits battle and clears old result UI");Shot("04-returned-menu");yield return new WaitForSecondsRealtime(.3f);r.stage="complete";
 }
#endif
 }
}
