using UnityEngine;
#if UNITY_EDITOR || DEVELOPMENT_BUILD
using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using UnityEngine.UI;
#endif
namespace MassEngine.Game {
 public sealed class Roster31PlayerSmoke:MonoBehaviour {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
 [Serializable]class Receipt{public bool passed,osInputTest=false,rangedChoice;public string stage,error,buildGuid;public string[] checks;}
 Receipt r=new Receipt();List<string> checks=new List<string>();string output;WarSandboxRuntimeDeployment d;
 [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Install(){var a=Environment.GetCommandLineArgs();if(!a.Contains("--roster31-smoke"))return;var g=new GameObject("Roster31 isolated smoke");DontDestroyOnLoad(g);g.AddComponent<Roster31PlayerSmoke>().output=a.First(x=>x.StartsWith("--terrain-output=")).Substring("--terrain-output=".Length);}
 static void Check(bool b,string e){if(!b)throw new Exception(e);}
 static Button B(string n){var b=FindObjectsByType<Button>(FindObjectsSortMode.None).SingleOrDefault(b=>b.name==n&&b.gameObject.activeInHierarchy);Check(b!=null,"Missing button "+n);return b;}
 static Text T(string n){var g=GameObject.Find(n);Check(g!=null,"Missing text object "+n);var t=g.GetComponentInChildren<Text>();Check(t!=null,"Missing text on "+n);return t;}
 static InputField Field(string n)=>FindObjectsByType<InputField>(FindObjectsSortMode.None).Single(f=>f.name==n&&f.gameObject.activeInHierarchy);
 void Shot(string n)=>ScreenCapture.CaptureScreenshot(Path.Combine(output,n+".png"));
 void Fit(string n){var t=T(n);Check(t.preferredHeight<=t.rectTransform.rect.height+2,n+" clipped");}
 void Dossier(UnitTypeConfig t){var keys=new[]{WarSandboxUnitStat.MaxHp,WarSandboxUnitStat.AttackDamage,WarSandboxUnitStat.AttackInterval};for(int i=0;i<3;i++){var def=WarSandboxUnitStats.Get(keys[i]);var v=d.DraftStats.Resolve(t,def);Check(T("legion-stat-value-"+i).text==def.Format(v.effective)+def.Unit,"Dossier value mismatch");Check(T("legion-stat-source31-"+i).text==RosterInfo31.Origin(v,def),"Dossier origin mismatch");Fit("legion-stat-source31-"+i);}Fit("legion-unit-role");}
 IEnumerator Start(){Directory.CreateDirectory(output);r.buildGuid=Application.buildGUID;var stack=new Stack<IEnumerator>();stack.Push(Run());while(stack.Count>0){bool moved;object next;try{moved=stack.Peek().MoveNext();next=moved?stack.Peek().Current:null;}catch(Exception ex){r.error=ex.ToString();Finish(1);yield break;}if(!moved){stack.Pop();continue;}if(next is IEnumerator e)stack.Push(e);else yield return next;}r.passed=true;Finish(0);}
 void Finish(int code){r.checks=checks.ToArray();File.WriteAllText(Path.Combine(output,"receipt.json"),JsonUtility.ToJson(r,true));Debug.Log("ROSTER31_RESULT "+JsonUtility.ToJson(r));Application.Quit(code);}
 IEnumerator Run(){r.stage="load";yield return new WaitForSecondsRealtime(3);var session=WarSandboxSceneSession.Instance;B("home-play").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);int season=Environment.GetCommandLineArgs().Contains("--winter")?2:0;B("card-"+season).onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("card-"+season+"-enter").onClick.Invoke();float end=Time.realtimeSinceStartup+120;while(session.IsLoading&&Time.realtimeSinceStartup<end)yield return null;yield return new WaitForSecondsRealtime(.7f);Check(session.State==WarSandboxEntryState.Battle&&!session.HelpOpen,"Load/isolated intro suppression failed");d=session.Controller.GetComponent<WarSandboxRuntimeDeployment>();Check(RosterInfo31.Active(d)&&d.IsEditing,"Not Roster31 draft");d.PlanStore=new WarSandboxLocalPlanStore(Path.Combine(output,"isolated-plans"));var original=d.Draft[0].template;var other=d.Draft[1];string initial=PlanState28.For(session.Controller).Current;Check(T("army-name-0").text.Contains("当前")&&T("army-composition31-0").text==RosterInfo31.Composition(d.Draft,0),"Overview composition/selection wrong");Fit("army-composition31-0");Shot("01-overview");yield return new WaitForSecondsRealtime(.3f);
  r.stage="sources";B("army-details-0").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Dossier(original);Check(T("formation-role-0").text.Contains("正在编辑"),"Selected formation missing");Check(PlanState28.For(session.Controller).Current==initial,"Reading dossier mutates draft");var def=WarSandboxUnitStats.Get(WarSandboxUnitStat.AttackDamage);var official=d.DraftStats.Resolve(original,def).official;Check(d.Draft.SetStat(original,WarSandboxUnitStat.AttackDamage,57),"Set isolated override failed");Check(d.TryPushStats(original,true,out var error),error);yield return new WaitForSecondsRealtime(.3f);Dossier(original);Check(T("legion-stat-source31-1").text.Contains("全局")&&T("legion-stat-value-1").text=="57","Global source missing");Shot("02-global-source");yield return new WaitForSecondsRealtime(.3f);
  B("field-unit-stats").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(Field("st-r-attackDamage-field").text=="57","Detailed value disagrees");Field("st-r-attackDamage-field").onEndEdit.Invoke("69");yield return new WaitForSecondsRealtime(.3f);Check(Field("st-r-attackDamage-field").text=="69"&&T("st-r-attackDamage-src-text").text.Contains("本局"),"Detail local edit failed");B("st-done").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Dossier(original);Check(T("legion-stat-source31-1").text.Contains("本局")&&T("legion-stat-value-1").text=="69","Local source not synchronized");Shot("03-local-source");yield return new WaitForSecondsRealtime(.3f);
  d.Draft.SetStat(original,WarSandboxUnitStat.AttackDamage,official);yield return new WaitForSecondsRealtime(.25f);Check(T("legion-stat-source31-1").text.Contains("本局"),"Equal-to-official override lost its true source");d.Draft.ClearStat(original,WarSandboxUnitStat.AttackDamage);yield return new WaitForSecondsRealtime(.25f);Check(T("legion-stat-value-1").text=="57"&&T("legion-stat-source31-1").text.Contains("全局"),"Clearing local did not reveal global");Check(d.Draft.SetStat(original,WarSandboxUnitStat.AttackDamage,69),"Restore local failed");yield return new WaitForSecondsRealtime(.3f);checks.Add("Official/global/local values match resolver and detailed page; equal-value local remains labeled local; clearing reveals global");
  r.stage="picker";int current=d.ChoiceTemplates.ToList().IndexOf(original);B("field-template").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);string before=PlanState28.For(session.Controller).Current;Check(T("picker-title").text.Contains("攻方")&&T("picker-title").text.Contains("01"),"Picker does not identify edited army/formation");Check(T("picker-source31-"+current).text==RosterInfo31.Sources(d,original)&&T("picker-stats-"+current).text.Contains("69"),"Picker local value/source stale");Fit("picker-source31-"+current);Fit("picker-extra31-"+current);Shot("04-picker-values");yield return new WaitForSecondsRealtime(.3f);B("picker-filter-2").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(PlanState28.For(session.Controller).Current==before,"Filter changes draft");B("picker-back").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(d.Draft[0].template==original&&PlanState28.For(session.Controller).Current==before,"Cancel picker changes composition");
  int alternate=Enumerable.Range(0,d.ChoiceTemplates.Count).FirstOrDefault(i=>WarSandboxUnitStats.IsRanged(d.ChoiceTemplates[i])&&d.ChoiceTemplates[i]!=original);if(d.ChoiceTemplates[alternate]==original)alternate=Enumerable.Range(0,d.ChoiceTemplates.Count).First(i=>d.ChoiceTemplates[i]!=original);var replacement=d.ChoiceTemplates[alternate];r.rangedChoice=WarSandboxUnitStats.IsRanged(replacement);var expected=d.rosterPolicy!=null?d.rosterPolicy.Select(d.Draft[0],replacement):d.Draft[0];expected.template=replacement;
  B("field-template").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);B("template-"+alternate).onClick.Invoke();yield return new WaitForSecondsRealtime(.4f);Check(d.Draft[0].template==replacement&&d.Draft[0].count==expected.count&&d.Draft[0].center==expected.center&&d.Draft[0].teamId==0,"Selection changed existing policy semantics");Check(T("legion-unit-name").text==d.Draft[0].Name&&T("formation-name-0").text==d.Draft[0].Name,"Names not synchronized");Dossier(replacement);Check(d.Draft[1].template==other.template&&d.Draft[1].count==other.count,"Changed other army");checks.Add("Picker identifies scope, filters/cancel do not mutate; replacement follows existing policy, preserves other army and synchronizes names/values");
  r.stage="counts-and-undo";int prior=d.Draft[0].count;Field("input-count").text="900";Check(d.Draft[0].count==prior,"Raw input prematurely committed");B("legion-update-count").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(d.Draft[0].count==900&&T("formation-count-0").text.Contains("900")&&T("legion-total").text.Contains("900"),"Count not synchronized");B("legion-done").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(T("army-summary-0").text.Contains("900")&&T("army-composition31-0").text==RosterInfo31.Composition(d.Draft,0),"Overview stale after count edit");Shot("05-updated-overview");yield return new WaitForSecondsRealtime(.3f);Check(d.Draft.Undo(),"Undo missing");yield return new WaitForSecondsRealtime(.3f);Check(d.Draft[0].count==prior&&T("army-composition31-0").text==RosterInfo31.Composition(d.Draft,0),"Undo did not update overview");Check(d.Draft.Redo(),"Redo missing");yield return new WaitForSecondsRealtime(.3f);Check(d.Draft[0].count==900,"Redo mismatch");B("army-details-1").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(T("legion-name").text.Contains("守方")&&T("formation-role-1").text.Contains("正在编辑"),"Selected army/formation wrong");Dossier(other.template);B("legion-done").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(T("army-name-1").text.Contains("当前")&&!T("army-name-0").text.Contains("当前"),"Selected marker stale");checks.Add("Count edit/Undo/Redo updates summaries; selection follows the correct army and formation");
  r.stage="persistence";Check(d.TrySavePlan("QA31","Isolated roster check",false,out error),error);string saved=PlanState28.For(session.Controller).Current;var changed=d.Draft[0];changed.count=800;d.Draft.Set(0,changed);Check(d.TryLoadPlan("QA31",out error),error);yield return new WaitForSecondsRealtime(.3f);Check(PlanState28.For(session.Controller).Current==saved&&T("army-summary-0").text.Contains("900"),"Reload stale or lost data");Check(WarSandboxUnitStats.TryGetOfficial(original,def,out var unchanged)&&unchanged==official,"Official asset modified");checks.Add("Real saved plan reload keeps names/counts/templates/stats; official template value unchanged");r.stage="complete";
 }
#endif
 }
}
