using UnityEngine;
#if UNITY_EDITOR || DEVELOPMENT_BUILD
using System;using System.IO;using System.Linq;using System.Collections;using System.Collections.Generic;using System.Reflection;using UnityEngine.UI;
#endif
namespace MassEngine.Game {
 public sealed class Settings29PlayerSmoke:MonoBehaviour {
#if UNITY_EDITOR || DEVELOPMENT_BUILD
 [Serializable]class Receipt{public bool passed,osInputTest=false,isolatedSettings=true;public string mode,stage,error,buildGuid;public float volume;public bool muted;public string[] checks;}
 Receipt r=new Receipt();List<string> checks=new List<string>();string output;WarSandboxAudio a;WarSandboxSceneSession session;SettingsSafety29 safety;
 [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Install(){var args=Environment.GetCommandLineArgs();if(!args.Contains("--settings29-smoke"))return;var path=args.First(v=>v.StartsWith("--terrain-output=")).Substring(17);var go=new GameObject("Settings29 isolated smoke");DontDestroyOnLoad(go);var s=go.AddComponent<Settings29PlayerSmoke>();s.output=path;s.r.mode=args.First(v=>v.StartsWith("--settings29-mode=")).Substring(18);}
 static void Check(bool b,string e){if(!b)throw new Exception(e);}
 static Button B(string n)=>FindObjectsByType<Button>(FindObjectsSortMode.None).Single(b=>b.name==n&&b.gameObject.activeInHierarchy);
 static string Txt(string n)=>GameObject.Find(n).GetComponentInChildren<Text>().text;
 static Slider Slider()=>FindObjectsByType<Slider>(FindObjectsSortMode.None).Single(s=>s.name=="settings-volume"&&s.gameObject.activeInHierarchy);
 void Values(float volume,bool muted){Check(Mathf.Abs(a.Settings.volume-volume)<.0001f&&a.Settings.muted==muted,"Settings values differ");Check(Mathf.Abs(a.Source.volume-volume)<.0001f&&a.Source.mute==muted,"Audio source differs from settings");}
 void Disk(float volume,bool muted){Check(new WarSandboxSettingsStore(a.SettingsPath).TryLoad(out var s,out var e),e);Check(Mathf.Abs(s.volume-volume)<.0001f&&s.muted==muted,"Fresh store read mismatch");}
 void Shot(string n)=>ScreenCapture.CaptureScreenshot(Path.Combine(output,n+".png"));
 void Escape()=>FindFirstObjectByType<WarSandboxFrontEnd>().GetType().GetMethod("SettingsEscape",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(FindFirstObjectByType<WarSandboxFrontEnd>(),null);
 IEnumerator Open(){B(session.State==WarSandboxEntryState.Battle?"nav-settings":"menu-settings").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(session.SettingsOpen,"Settings not open");}
 IEnumerator Start(){Directory.CreateDirectory(output);r.buildGuid=Application.buildGUID;var stack=new Stack<IEnumerator>();stack.Push(Run());while(stack.Count>0){bool moved;object next;try{moved=stack.Peek().MoveNext();next=moved?stack.Peek().Current:null;}catch(Exception ex){r.error=ex.ToString();Finish(1);yield break;}if(!moved){stack.Pop();continue;}if(next is IEnumerator e)stack.Push(e);else yield return next;}r.passed=true;Finish(0);}
 void Finish(int code){r.checks=checks.ToArray();if(a!=null){r.volume=a.Settings.volume;r.muted=a.Settings.muted;}File.WriteAllText(Path.Combine(output,"receipt.json"),JsonUtility.ToJson(r,true));Debug.Log("SETTINGS29_RESULT "+JsonUtility.ToJson(r));Application.Quit(code);}
 IEnumerator Run(){r.stage="startup";yield return new WaitForSecondsRealtime(3);a=WarSandboxAudio.Ensure();session=WarSandboxSceneSession.Instance;safety=SettingsSafety29.For(session);Check(safety!=null,"Not Settings29 menu");
  if(r.mode=="seed"){Check(!File.Exists(a.SettingsPath)&&!session.SettingsOpen,"Fresh profile was written or prompted");Values(.65f,false);yield return Open();Slider().value=.37f;B("settings-mute").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Values(.37f,true);Check(safety.Pending&&Txt("settings-status").Contains("尚未保存")&&!File.Exists(a.SettingsPath),"Live adjustment unexpectedly persisted");Shot("01-pending");yield return new WaitForSecondsRealtime(.3f);B("settings-save").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(!session.SettingsOpen,"Save failed");Disk(.37f,true);checks.Add("Missing file defaults silently; slider/mute apply live; explicit save writes 37 percent and muted");}
  else if(r.mode=="verify"){Values(.37f,true);Check(!session.SettingsOpen,"Healthy startup incorrectly prompted");byte[] before=File.ReadAllBytes(a.SettingsPath);yield return Open();Check(Txt("settings-volume-value")=="37%"&&Txt("settings-mute").Contains("已静音"),"UI differs after process restart");checks.Add("Fresh EXE process loads saved 37 percent/muted into UI and AudioSource");Slider().value=.12f;B("settings-mute").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("settings-cancel").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);Values(.37f,true);Check(File.ReadAllBytes(a.SettingsPath).SequenceEqual(before),"Cancel wrote file");yield return Open();Slider().value=.42f;B("settings-defaults").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(safety.ConfirmDefaults,"Defaults lacks confirmation");Shot("02-defaults-confirm");yield return new WaitForSecondsRealtime(.3f);Escape();yield return new WaitForSecondsRealtime(.2f);Check(session.SettingsOpen&&!safety.ConfirmDefaults,"Esc should only dismiss defaults confirmation");Values(.42f,true);B("settings-defaults").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("settings-defaults-confirm").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);Values(.65f,false);Escape();yield return new WaitForSecondsRealtime(.2f);Values(.37f,true);Check(!session.SettingsOpen&&File.ReadAllBytes(a.SettingsPath).SequenceEqual(before),"Esc/default cancel saved changes");checks.Add("Cancel and Escape restore opened values without disk writes; restore-default confirmation can be dismissed");
   r.stage="locked-save";yield return Open();Slider().value=.53f;B("settings-mute").onClick.Invoke();using(var held=new FileStream(a.SettingsPath,FileMode.Open,FileAccess.Read,FileShare.None)){B("settings-save").onClick.Invoke();}yield return new WaitForSecondsRealtime(.3f);Check(session.SettingsOpen&&safety.Pending&&!string.IsNullOrEmpty(safety.Error)&&File.ReadAllBytes(a.SettingsPath).SequenceEqual(before),"Failed save closed dialog, cleaned status or damaged file");Values(.53f,false);Shot("03-save-failure");yield return new WaitForSecondsRealtime(.3f);B("settings-cancel").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);Values(.37f,true);Disk(.37f,true);yield return Open();Check(string.IsNullOrEmpty(safety.Error),"Cancelled write error leaked into next edit");Escape();yield return new WaitForSecondsRealtime(.2f);checks.Add("Real locked-file write failure leaves dialog/pending state and old bytes; cancel restores prior values");}
  else if(r.mode=="defaults"){Values(.37f,true);yield return Open();B("settings-defaults").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("settings-defaults-confirm").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);Values(.65f,false);Disk(.37f,true);B("settings-save").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Disk(.65f,false);checks.Add("Default restore only persists after explicit save");}
  else if(r.mode=="corrupt"||r.mode=="invalid"){Values(.65f,false);Check(session.SettingsOpen&&!string.IsNullOrEmpty(safety.Error)&&Txt("settings-error").Contains("默认音量"),"Bad settings not surfaced with fallback");byte[] before=File.ReadAllBytes(a.SettingsPath);Shot("04-invalid-fallback");yield return new WaitForSecondsRealtime(.3f);B("settings-cancel").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);Check(File.ReadAllBytes(a.SettingsPath).SequenceEqual(before),"Fallback auto-overwrote bad original");checks.Add("Invalid settings safely fall back and surface warning; cancel preserves original file");if(r.mode=="corrupt"){yield return Open();Slider().value=.48f;B("settings-save").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(!session.SettingsOpen,"Explicit recovery save failed");Disk(.48f,false);checks.Add("Explicit save replaces corrupt settings with verified valid values");}}
  else if(r.mode=="verify-default"){Values(.65f,false);Disk(.65f,false);Check(!session.SettingsOpen,"Default restart unexpected warning");checks.Add("Fresh EXE restart reads saved defaults correctly");r.stage="battle-isolation";B("home-play").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);B("card-0").onClick.Invoke();yield return new WaitForSecondsRealtime(.2f);B("card-0-enter").onClick.Invoke();float deadline=Time.realtimeSinceStartup+120;while(session.IsLoading&&Time.realtimeSinceStartup<deadline)yield return null;Check(session.State==WarSandboxEntryState.Battle,"Battle load failed");yield return new WaitForSecondsRealtime(1);var c=session.Controller;var d=c.GetComponent<WarSandboxRuntimeDeployment>();Check(d.IsEditing,"No draft");d.PlanStore=new WarSandboxLocalPlanStore(Path.Combine(output,"isolated-plans"));Check(d.TrySavePlan("KEEP29","Preserve plan",false,out var err),err);string plan=Path.Combine(d.PlanStore.DirectoryPath,"KEEP29.json");byte[] savedPlan=File.ReadAllBytes(plan);for(int i=0;i<2;i++){var e=d.Draft[i];e.count=i==0?1060:988;d.Draft.Set(i,e);}yield return new WaitForSecondsRealtime(.3f);string draft=PlanState28.For(c).Current;yield return Open();Slider().value=.22f;B("settings-defaults").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);B("settings-defaults-confirm").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);B("settings-save").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(d.IsEditing&&PlanState28.For(c).Current==draft&&File.ReadAllBytes(plan).SequenceEqual(savedPlan),"Sound defaults changed draft or plan");checks.Add("Defaults/save inside deployment preserve custom 1060/988 draft and real saved plan byte-for-byte");B("deployment-start").onClick.Invoke();yield return new WaitForSecondsRealtime(.4f);Check(c.Phase==WarSandboxBattlePhase.Running,"Battle not running");yield return Open();Check(c.Phase==WarSandboxBattlePhase.Paused,"Settings did not pause running battle");Slider().value=.45f;B("settings-cancel").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(c.Phase==WarSandboxBattlePhase.Running,"Cancel did not resume running battle");Values(.65f,false);c.PauseBattle();yield return Open();B("settings-cancel").onClick.Invoke();yield return new WaitForSecondsRealtime(.3f);Check(c.Phase==WarSandboxBattlePhase.Paused,"Settings resumed an already paused battle");checks.Add("Running battle pauses/resumes through settings; previously paused battle stays paused");}
  else throw new Exception("Unknown smoke mode: "+r.mode);Check(!Directory.GetFiles(Path.GetDirectoryName(a.SettingsPath),"*.tmp-*").Any(),"Temporary files leaked");r.stage="complete";
 }
#endif
 }
}
